### ISSUE TITLE
Links not shortening & not being written to database

### ISSUE THREAD

**Issue by mihawk90** [cydrobolt/polr#104]
Heya,
Soo, I was trying around a little more and I had an issue since I set up Polr the first time. When shortening URLs, they aren't passed to the database and obviously don't work.

So today I finally came around to track the issue, and promptly found it :P 

in createurl.php:134 there is this:
```PHP
$query2 = "INSERT INTO `redirinfo` (baseval,rurl,ip,user,iscustom,country) VALUES ('{$baseval}','{$urlr}','{$ip}','{$userinfo['username']}','{$iscustom}','{$country_code}');";
```

I printed out the resulting query and found this:
```SQL
INSERT INTO `redirinfo` (baseval,rurl,ip,user,iscustom,country) VALUES ('1','http://example.com','127.0.0.1','polr','no','');
```

And again, country is a field that is not allowed to be empty, which is totally fine, however the way `$country_code` is obtained won't work in most cases:
```PHP
$country_code = @$_SERVER["HTTP_CF_IPCOUNTRY"];
```

`HTTP_CF_IPCOUNTRY` is a header injected by CloudFlare, so it basically won't work unless the installation runs on CloudFlare (which I'm not sure even makes sense considering Polr doesn't actually serve any content but that's a different topic for a different time).
I tried solving the issue, and there is [geoip_country_code_by_name](http://php.net/manual/de/function.geoip-country-code-by-name.php), this however won't work unless GeoIP is enabled in the php settings (I suppose at least, because it doesn't work for me).

I tried coming up with a different field we could use, but I could only find `HTTP_ACCEPT_LANGUAGE` to be somewhat useful, but of course it doesn't return the country code but the browser accepted languages, which could be basically anything.

Also a little off-topic, storing full IP adresses is illegal in various countries, so that should be revised.
We could use the [code from Piwik](https://github.com/xrowgmbh/xrowpiwik/blob/master/src/piwik/plugins/AnonymizeIP/AnonymizeIP.php#L45)

**Comment by Cydrobolt** [comment]
Hmmm...all these weird NOT NULL errors are interesting. They've never happened to me before. Usually, a blank field *should* work. Can you reproduce this on c9? I haven't been able to reproduce any of these weird errors. Perhaps it has to do with your mariadb/mysql version

**Comment by mihawk90** [comment]
There are also various other fields that throw the same errors, what I saw now are `lkey` and `clicks`, not sure if there are more :|

I don't think it has something to do with the version but rather with the settings of the database.

If we think about it, `NOT NULL` is explicitely so that fields CAN'T remain empty (not empty string, that depends on the setup I think), so I'm not sure why C9 would allow to let them empty, that defeats the sole purpose of `NOT NULL` :/

**Comment by Cydrobolt** [comment]
`""` is not NULL

**Comment by mihawk90** [comment]
yep, that's what I meant ;)

Just tested it... works on C9 but I can't understand why they would allow NULL values in NOT NULL fields... Or at least it appears like that... I can't really explain why it would happen otherwise.

My MariaDB is a standard installation, did no setup at all so it's really just default state.

Is there a database browser in C9? I can't find one :D

**Comment by Cydrobolt** [comment]
Ah, yes ^^

**Comment by Cydrobolt** [comment]
Maybe the better option would be setting it to allow NULL values

**Comment by mihawk90** [comment]
Well yeah that depends where the values are needed of course :)

I guess you had your reasons when you added them as `NOT NULL`, no? I think while we're at #99 it might be a good idea to also re-evaluate all the possible field values, not just field names :)

**Comment by Cydrobolt** [comment]
Yeah, agreed.

**Comment by Cydrobolt** [comment]
country code should be fine empty, but if we change it to something else we could default it to "ANONYMOUS" then catch it in r.php (currently tries to catch empty str)
