### ISSUE TITLE
VARCHAR rurl limited to 80 characters !!!

### ISSUE THREAD

**Issue by Spheerys** [Cydrobolt/polr#108]
Hi,

In the database, the rurl field is limited to 80 characters, which is very few for some long URL (google documents for exemple).
I suggest to increase it to 255 to be quiet.

**Comment by Cydrobolt** [comment]
Hi @spheerys,

What version of Polr are you on? We increased this limit to around 65k 4 months ago. If you recreate your database using the new setup script,  or manually change the field length,  you should be okay. You can git pull or download the new clone of master to ensure you are up to date. 

Thanks! 

See https://github.com/Cydrobolt/polr/commit/a5929f02961c40b882eda02b09975795560b1546

**Comment by Spheerys** [comment]
Indeed, I have isnatlled Polr a long time ago and I just did a git pull to get the fresh code.
But my database stay on the old state.

Happy to see the issue was solved :)

**Comment by Cydrobolt** [comment]
You should be able to manually change the field type to a bigger field. I recommend you change it to the TEXT type with no length restrictions,  which is what Polr is currently using. Hope it works!

**Comment by Spheerys** [comment]
It's working :)

**Comment by Cydrobolt** [comment]
:+1:
