### ISSUE TITLE
PostgreSQL?

### ISSUE THREAD

**Issue by piwats** [Cydrobolt/polr#109]
Is it possible to add support fro PostgreSQL?

**Comment by mihawk90** [comment]
Currently there is a branch open regarding rewrite to PDO instead of mysqli, but I don't know how far the development is. I would guess that there are some other things to tackle first though before going through with it.

**Comment by Cydrobolt** [comment]
Yeah, @mihawk90 is correct. We're working on a migration to PDO, although we haven't finished yet. It is a milestone we've been trying to reach, although I simply haven't had enough time to migrate it myself.

If anyone is interested in helping, it would be greatly appreciated! We're open to PRs and questions about the codebase.
