### ISSUE TITLE
allow setting the default url scheme to https

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [cydrobolt/polr#117]
not just on the url shortening page where the input box starts with `http://`, there are several pages with messages, links etc which default to `http://` even if the polr instance is https only. needs better https support. links to the polr instance should be `https://` if im running it on https (e.g. on r.php when a secret key is invalid, it shows `Incorrect Key. (http://polr.instance/abc?keyhere)`

**Comment by allardhoeve** [comment]
:+1:

**Comment by cydrobolt** [comment]
You could enforce https server-side by changing some Apache configuration files,  your CloudFlare configuration,  or maybe the .htaccess

As for the front page pre-filled content, it is likely to change for 2.0. Likely it will be replaced with a placeholder in the field background.

**Comment by berrythesoftwarecodeprogrammar** [comment]
my websites are already https only
i think the config should store the default url scheme, either as part of the stored hostname or seperately, and then use that setting whenever dynamically writing the site's hostname on any page

**Comment by cydrobolt** [comment]
Agreed. That sounds like something we should implement in 2.0

**Comment by cydrobolt** [comment]
This is implemented in 2.0. 
Closing now.
