### ISSUE TITLE
javascriptless polr

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [cydrobolt/polr#118]
ive just installed polr and then went through all the files making it work without any javascript or external resources and it actually works fine

how do themes currently work? would javascript elements be considered part of the theme? i saw in #66 that template support is coming. currently polr spits out javascript from php for certain pages to work. i changed all that of course. but if there is any interest in a non-javascript template or theme being supported/distributed, those php pages would need to be changed too. im guessing its probably not worth it, with the majority of users in mind.

but just putting it out there that ive successfully made polr scriptless and cdnless, as this is how i prefer to make websites right now. the main functionality is all there and the interface looks the same apart from the ui things which are triggered by javascript. im going to change that though and make my own basic theme without bootstrap or anything else required.

i guess my issue is to see if theres any interest in this from the dev or other users and if future updates will make it easier for me to continue with my scriptless/custom 'theme'/version

**Comment by cydrobolt** [comment]
This could happen as soon as the end of the week.  I'm planning on releasing an alpha version of 2.0 soon,  which could encompass those changes. 

We're moving to Twig and Silex,  so plugin support will also become much better. Keep an eye out for 2.0

**Comment by berrythesoftwarecodeprogrammar** [comment]
cool :).  i guess ill close this for now
