### ISSUE TITLE
hyperlinks instead of text-only in 'MyUser' > Dashboard > My Links

### ISSUE THREAD

**Issue by mhow2** [cydrobolt/polr#120]
Hi,

Would be useful to have click-able links in 'My Links' section... WDYT ?

Thanks,

**Comment by cydrobolt** [comment]
Yeah,  this sounds like a good idea. It wouldn't be difficult to link the shirt URL value to the link.   As 2.0 is coming out soon,  I'll add this to its milestone. 

Thanks :)

**Comment by gitthismoney** [comment]
this would be very helpful

**Comment by mhow2** [comment]
Hi,
Do you think we can have an intermediate release for this ? Or I would have to modify the tweak code by hand...

**Comment by cydrobolt** [comment]
@mhow2 you can clone the master branch of the repo using `git`, or you can download the code as a zip from the GitHub repository.

If you're running 1.x, you shouldn't try to upgrade directly to 2.x, though.

**Comment by mhow2** [comment]
Hi @cydrobolt ,
Indeed i'm running the 1.x latest stable release... I was expecting an intermediate release on that version  :) But I understand cloning the master branch would be an upgrade to 2.x. Which does not seem recommended for now.
