### ISSUE TITLE
Not Registering.. Help

### ISSUE THREAD

**Issue by nitintater123** [cydrobolt/polr#121]
![screenshot_17](https://cloud.githubusercontent.com/assets/15836658/11152604/972ab0f4-8a59-11e5-8394-b548fe720295.jpg)

I've used polr at sh0rt.in , Help me in solving this. :) 
This message comes after I register a new account.

AND:
How to disable or Enable Register option?

**Comment by cydrobolt** [comment]
Go in `config.php` and set `$regtype` to `"none"`

Also, for this registration problem, I suspect it is because you set your registration type to `email`, but haven't set up your SMTP settings.

**Comment by nitintater123** [comment]
:) Thank you. But.. Can you help me with the smtp?

![screenshot_23](https://cloud.githubusercontent.com/assets/15836658/11161760/f93c86da-8aab-11e5-8899-e097386da8f5.jpg)

**Comment by cydrobolt** [comment]
To edit the SMTP settings, you can go to `YOURSITE/setup.php` and rerun the setup script (refill in the database details, etc), and include your SMTP information while performing the installation.

Alternatively, you can go in `config.php` and append this to the end:

```
$smtpCfg = array(
    "servers"  => "wc-124.atnoc.com",
    "from"     => "noreply@sh0rt.in",
    "username" => "noreply@sh0rt.in",
    "password" => "PASSWORD_GOES_HERE",
);
```
