### ISSUE TITLE
Polr server requires internet access to serve admin pages

### ISSUE THREAD

**Issue by ghostflame** [cydrobolt/polr#129]
Polr server attempts to access https://raw.githubusercontent.com/Cydrobolt/polr/notices/anotices while serving admin pages.  Instances of polr that exist inside restrictive firewalls time out attempting to access this url, resulting in very slow page load  or timeouts for admin pages.

While having notices is nice, it does not seem like sufficient reason to make the admin pages unusable.

grep -n github index.php 
211:        $status = file_get_contents('https://raw.githubusercontent.com/Cydrobolt/polr/notices/anotices'); // fetch notices from Github
221:        $status = file_get_contents('https://raw.githubusercontent.com/Cydrobolt/polr/notices/unotices'); // fetch notices from Github

**Comment by cydrobolt** [comment]
I'm fairly sure we've gotten rid of this months ago. 

Can you try doing a git pull or updating that file?

**Comment by ghostflame** [comment]
That's a recent download of 1.4.1

**Comment by ghostflame** [comment]
Yeah, I can see it gone in the current code.  Fair enough.
