### ISSUE TITLE
Allow forward slashes in the manually specified shortened URLs.

### ISSUE THREAD

**Issue by kcspamsplat** [cydrobolt/polr#138]
The setup of Polr already specifies where the shortened link suffix ends. For users who have a nicely laid out site but are subject to the tyranny of a CMS auto-generating links in a site, it would be nice to use Polr to reference with a perceived hierarchy.

For example. Say I have a nice tree such as:

/<CMS auto generated>/support/
/<CMS auto generated>/support/widget
/<CMS auto generated>/support/widget/docs
/<CMS auto generated>/support/widget/firmware
....

but where <CMS auto generated> = something awful like "http://h20566.www2.foobar.com/portal/site/"

It would be nice to replace that CMS string with "http://polr/support/widget/docs" which is easy to remember and have it redirect to ""http://h20566.www2.foobar.com/portal/site/support/widget/docs".

**Comment by cydrobolt** [comment]
It might be better to try using something like "http://h20566.www2.foobar.com/portal" instead. The sensitive nature of `/` forward slashes in URLs, their limitations, and the issues they cause when used as customisable routes can cause lots of conflicts and problems with the rest of the application. I don't think this is something that we can realistically support without causing problems elsewhere.

 :(

**Comment by kcspamsplat** [comment]
I'm not understanding the sensitivity. The setup of Polr requires the root
part of the URL to be specified so the application knows discard at the
beginning. After that is a string to be matched to one in the database so
it can be redirected. This is a 1:1 string mapping, so why would the
strings be interpreted as URLs by Polar? It has to eventually be a valid
URL but even then it is the browser who determines if the returned URL is
valid.

**Comment by cydrobolt** [comment]
Lumen's (our PHP library) router does not support catching slashes in path variables, so a workaround would be required. I don't think that having slashes as part of custom URLs is worth the trouble right now, because they could conflict with other paths and a lot of modifications to Lumen would be needed to achieve it.
