### ISSUE TITLE
Password field can be empty

### ISSUE THREAD

**Issue by ibiBgOR** [cydrobolt/polr#139]
I just changed my password to my account to "" without the "" ... I could also login in my account with just no password.
Maybe there should be a minimum length of the password?

**Comment by cydrobolt** [comment]
Hi @ibiBgOR! Thanks for reporting this issue!
I agree that an empty password shouldn't be allowed, but the code for Polr 1.x is currently frozen. I'm going to add this to the 2.0 milestone to make sure we don't allow empty passwords in 2.x.

Thanks! :+1:

**Comment by cydrobolt** [comment]
Fixed in 53809cba287058b3fe0809a3fdd6753cdccb2943
