### ISSUE TITLE
Allow generating user API keys in selfhosted Polr

### ISSUE THREAD

**Issue by strugee** [cydrobolt/polr#141]
Currently if you're selfhosting Polr you need to manually insert API keys into the db. This kinda sucks.

I should be able to provide a username and password and get back usable API keys. Furthermore links generated using those keys should be associated with the correct user, and the user should be able to revoke API keys.

**Comment by cydrobolt** [comment]
This is available in 2.0. Admins can toggle the status of API keys for each user or choose to reset their keys. I'm planning to allow users to reset or toggle this on their own as well. The keys link the created links to the user who owns the keys. 

They should be able to view these in their user panel. 

I'm going to leave this ticket open until I add the option for users (non admin users) to toggle and view their own keys. :)

**Comment by strugee** [comment]
@cydrobolt great! Almost hate to ask, but any idea when 2.0 will be out?

**Comment by cydrobolt** [comment]
@strugee really soon (tm)

**Comment by cydrobolt** [comment]
Admins should now be able to assign, reset, and manage API keys. 

We still need to implement key revocation from the user-side, and give admins the ability to change the quota from the admin panel.

**Comment by cydrobolt** [comment]
Closing in favour of #156
