### ISSUE TITLE
PHP 7 Compatibility

### ISSUE THREAD

**Issue by mckernanin** [cydrobolt/polr#145]
I'm running serverpilot on a DigitalOcean droplet, and I tried to install polr on PHP7. There's either not a package for mysqlnd, or the name isn't obvious. For now, I rolled back to 5.6, but would really like to run it on 7 for the performance and memory implications.
Thanks!

**Comment by cydrobolt** [comment]
@mckernanin hi! Polr 2.0 has full PHP 7.0 support with PDO. Could you try the development 2.0 branch instead?

`git checkout 2.0-dev`

You will need to set the `DocumentRoot` to `/public` within the Polr folder.

Thanks!

**Comment by cydrobolt** [comment]
@mckernanin did this work? If so, I'm going to close the ticket.

**Comment by mckernanin** [comment]
Sure thing, I'll check it out xD.

**Comment by cydrobolt** [comment]
The 2.0 branch was actually merged into master, so you'll only need to pull it :)
