### ISSUE TITLE
Add a fix permissions segment for docs

### ISSUE THREAD

**Issue by cydrobolt** [cydrobolt/polr#150]
Cloning the repository as root and not giving ownership of the repository in /var/www to www-data (ubuntu) or Apache (fedora) can cause permissions isssues.

**Comment by ekes** [comment]
Further, on Fedora SELinux is now enabled and enforcing by default so you need to change the context to httpd_sys_rw_content_t (`chcon -R -t httpd_sys_rw_content_t polr`)

However it would be nicer to document which directories actually _need_ the webserver to have write access to them (and if php code can be executed in those directories); and which require webserver write access only if you aren't using artisan.

**Comment by cydrobolt** [comment]
I've added a segment about permissions to the docs at http://docs.polr.me
@ekes do you want to submit a PR about changing the SELinux context for the folder(s)? The webserver needs write access to the `.env` file which is updated, and `storage/` in the folder tree.

**Comment by ekes** [comment]
OK, shall do. Just getting it going myself now I know what's what :-)

I assume once .env is written by the webserver config it can have write access removed?
