### ISSUE TITLE
Installation in the directory

### ISSUE THREAD

**Issue by jackxb** [cydrobolt/polr#153]
Hi, how can I set the polr in the http://site.ru/polr/ ? 
http://site.ru busy with another service, I would like to install polr next.

**Comment by cydrobolt** [comment]
Are you using nginx or apache?

**Comment by jackxb** [comment]
I use Apache

**Comment by cydrobolt** [comment]
You can try editing the `.htaccess` in the Polr `public/` folder to `RewriteBase /polr`, and then use something such as `Alias "/polr" "/var/www/polr/public"` in the httpd configuration file for the website.

You can try using both `RewriteBase` and `Alias`, or `Alias` without `RewriteBase` to see which one works.

**Comment by jackxb** [comment]
Thank you  @cydrobolt .

I tried to use `Alias` in Apache and `.htaccess`, the site is available at address `site.ru/polr/` but the css and js files and other requests are requested from the root of the site.

In files `polr/resources/views/*blade.php` reference written strictly from the root site, e.g. `<link rel='stylesheet' href='/css/admin.css' />` or `<form action='/admin/action/change_password' method='POST'>` in the end, `polr/.htaccess` file is powerless in such requests.

Is there any other way around this?

**Comment by jackxb** [comment]
I'm not strong in the RewriteRule, but maybe it is possible to determine that the request is coming from `site.ru/polr/` and all requests from `site.ru/` sent to `site.ru/polr/`? That would individually not to prescribe rules.

**Comment by cydrobolt** [comment]
Hmm, yeah. Most of the references to static files reference the root of the site. 

It's tough because I didn't intend 2.x to work with this kind of route. 

Is there a way you could host Polr on a sub domain and have a VirtualHost for that in Apache? 

E.g r.site.ru?

**Comment by jackxb** [comment]
Yes, I did, everything works fine. Thank you for your help and work.

**Comment by cydrobolt** [comment]
:+1:
