### ISSUE TITLE
toastr.js.map not included in js directory

### ISSUE THREAD

**Issue by typngeek** [cydrobolt/polr#158]
I had some problems initially getting some functions to work my Polr homepage, such as the tips not showing up, the Public/Secret selector not showing its current selection, and the availability check not working entirely.
After some digging around, I found that it was due to the browser getting a 404 trying to access "/js/toastr.js.map", which is not included in the repo. I found it online and put it in my installation, and everything works great now.

Just a heads up, and thanks for the great work.

[toastr.js.map.zip](https://github.com/cydrobolt/polr/files/201170/toastr.js.map.zip)

**Comment by cydrobolt** [comment]
Hmm, this is weird. `.map` files are usually used for matching minified or combined code with the source. A missing map file shouldn't cause any JavaScript issues.

Which browser are you using?

**Comment by typngeek** [comment]
I'm using Chrome Version 49.0.2623.110 m on Win 10. 
You're right. I just moved the file to another location, and while the Chrome error still appears, it seems that all is well now. 

Very perplexing... I'll see if I can replicate in a new build.
![image](https://cloud.githubusercontent.com/assets/16531060/14234714/7c6afc7e-f9b7-11e5-93ac-d109a1437dc5.png)

**Comment by typngeek** [comment]
Interesting, I can't replicate it. Must have been some weird browser thing then...

Thanks for the help.

**Comment by cydrobolt** [comment]
No worries, thanks for trying Polr :)
