### ISSUE TITLE
trouble with smtp deliveries

### ISSUE THREAD

**Issue by gitthismoney** [cydrobolt/polr#159]
Hello,

First of all thank you very much for a great looking and written project. We have set up a clone at our office and are having trouble with smtp deliveries. This is for 2.0-dev. We get the following in our log, any assistance would be greatly appreciated:
*let me know if i can provide any more information.

[2016-04-05 21:45:27] lumen.ERROR: exception 'Swift_TransportException' with message 'Expected response code 220 but got code "500", with message "500 #5.5.1 command not recognized^M
"' in /var/www/polr/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:383
Stack trace:
#0 /var/www/polr/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(281): Swift_Transport_AbstractSmtpTransport->_assertResponseCode('500 #5.5.1 comm...', Array)
#1 /var/www/polr/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(243): Swift_Transport_AbstractSmtpTransport->executeCommand('STARTTLS\r\n', Array, Array)
#2 /var/www/polr/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(286): Swift_Transport_EsmtpTransport->executeCommand('STARTTLS\r\n', Array)
#3 /var/www/polr/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(118): Swift_Transport_EsmtpTransport->_doHeloCommand()
#4 /var/www/polr/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#5 /var/www/polr/vendor/illuminate/mail/Mailer.php(395): Swift_Mailer->send(Object(Swift_Message), Array)
#6 /var/www/polr/vendor/illuminate/mail/Mailer.php(181): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#7 /var/www/polr/vendor/illuminate/support/Facades/Facade.php(222): Illuminate\Mail\Mailer->send('emails.activati...', Array, Object(Closure))
#8 /var/www/polr/app/Http/Controllers/UserController.php(111): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#9 /var/www/polr/app/Http/Controllers/UserController.php(111): Illuminate\Support\Facades\Mail::send('emails.activati...', Array, Object(Closure))
#10 [internal function]: App\Http\Controllers\UserController->performSignup(Object(Illuminate\Http\Request))
#11 /var/www/polr/vendor/illuminate/container/Container.php(507): call_user_func_array(Array, Array)
#12 /var/www/polr/vendor/laravel/lumen-framework/src/Application.php(1399): Illuminate\Container\Container->call(Array, Array)
#13 /var/www/polr/vendor/laravel/lumen-framework/src/Application.php(1364): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#14 /var/www/polr/vendor/laravel/lumen-framework/src/Application.php(1335): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\UserController), 'performSignup', Array)
#15 /var/www/polr/vendor/laravel/lumen-framework/src/Application.php(1303): Laravel\Lumen\Application->callControllerAction(Array)
#16 /var/www/polr/vendor/laravel/lumen-framework/src/Application.php(1288): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#17 /var/www/polr/vendor/laravel/lumen-framework/src/Application.php(1207): Laravel\Lumen\Application->handleFoundRoute(Array)
#18 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/polr/vendor/illuminate/pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /var/www/polr/vendor/laravel/lumen-framework/src/Http/Middleware/VerifyCsrfToken.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 [internal function]: Laravel\Lumen\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /var/www/polr/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#23 /var/www/polr/vendor/illuminate/session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /var/www/polr/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#26 /var/www/polr/vendor/illuminate/cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /var/www/polr/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#29 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/polr/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 /var/www/polr/vendor/laravel/lumen-framework/src/Application.php(1439): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 /var/www/polr/vendor/laravel/lumen-framework/src/Application.php(1213): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#33 /var/www/polr/vendor/laravel/lumen-framework/src/Application.php(1153): Laravel\Lumen\Application->dispatch(NULL)
#34 /var/www/polr/public/index.php(28): Laravel\Lumen\Application->run()
#35 {main}

**Comment by cydrobolt** [comment]
Hi! Thanks for opening a ticket! 

The 2.0-dev branch is now largely unmaintained. The branch was merged into master. The swiftmailer issue was a known issue, but fixed in master. 

Could you try switching branches and letting me know if that helps? You will also need to reinstall or edit `.env` with your SMTP credentials.

**Comment by gitthismoney** [comment]
thanks for the quick reply, i think i am on master... do you think that using a smtp server without a username / password will cause problems? I left both lines blank. 

also our smtp server doesn't have starttls, it is just plain old port 25...

**Comment by cydrobolt** [comment]
@gitthismoney hmm, that could be a problem.

I don't think you can use an SMTP server without a username or password. I am pretty sure it is required. You can specify the port in the installation. 

According to the error message, `[2016-04-05 21:45:27] lumen.ERROR: exception 'Swift_TransportException' with message 'Expected response code 220 but got code "500", with message "500 #5.5.1 command not recognized^M`, it looks like it is a problem with your SMTP server, since it is returning `500 Internal Server Error`

**Comment by fwilson42** [comment]
I'm going to guess that the server not supporting TLS is a problem. Perhaps
Swift has a configurable TLS option?

**Comment by cydrobolt** [comment]
I think @fwilson42 is right...what SMTP port do you have in `.env` right now?

**Comment by gitthismoney** [comment]
i was using port 25

i also just tried smtp.googlemail.com on port 465 using my personal gmail login but i received a slightly different error.

I use a few other web apps that allow sending mail thru smtp without authentication or tls. i can also telnet to the smtp server and send mail without a problem (from the host i am running polr on).

ie. 
telnet mail.domain.com 25
ehlo [127.0.0.1]
mail from: me@domain.com
rcpt to: me@domain.com
data
stuff here
.

**Comment by fwilson42** [comment]
@cydrobolt yeah, looks like you'll need a configuration option to disable swiftmailer encryption: [this](https://symfony.com/doc/current/reference/configuration/swiftmailer.html#encryption) might help

**Comment by cydrobolt** [comment]
@gitthismoney could you try adding `MAIL_ENCRYPTION=null` to the end of your `.env` configuration file?

**Comment by gitthismoney** [comment]
ha, it works! thank you both!

**Comment by cydrobolt** [comment]
@gitthismoney awesome!
