### ISSUE TITLE
Can't Install via FTP/PHPMyAdmin

### ISSUE THREAD

**Issue by unwork** [cydrobolt/polr#161]
I've downloaded the latest Polr build from here: https://github.com/cydrobolt/polr
And read installation instructions found here:
http://docs.polr.me/en/latest/user-guide/installation/#option-1-run-automatic-setup-script

Then I've mirrored all contents via FTP to a subdomain named like so: polr.mydomain.com
I've created a Polr database and database user via PHPMyAdmin
But when I go to: polr.mydomain.com/setup/ I get a 404 error.

Browsing through the downloading files, I can't see no 'setup' directory or 'setup.php' whatsoever.
Does anybody have an idea what might be going wrong here?

Thank you
Mariano

**Comment by cydrobolt** [comment]
Hi! Thanks for opening a ticket!

Polr uses a routing framework to create the routes. It doesn't employ separate folders for each route. Did you ensure that you set the `DocumentRoot` in your Apache configuration or vHost for your site to `polr/public`?

**Comment by unwork** [comment]
Thank you for your swift reply.

I did not set the `DocumentRoot` as you describe, that's probably the problem.
Is this something I have to do locally before uploading to my server? Or directly via my server's control panel?

**Comment by cydrobolt** [comment]
You have to edit your server's vhost configuration. Is this on shared hosting? You should be able to edit in your server's control panel what the "document root" for your Polr domain is set to.

**Comment by unwork** [comment]
I lack the knowledge to complete this step. I look at my shared hosting's control panel but can't figure out how to edit the vhost configuration for my Polr subdomain. I'll reach out to them and see if they can guide me.

Thank yo so much for your help.

**Comment by cydrobolt** [comment]
In the worst case, if your host does not allow you to edit your document root, you can try a 1.x legacy release such as 1.5.1

https://github.com/cydrobolt/polr/releases

**Comment by unwork** [comment]
Thank you for letting me know about this alternative. My shared hosting does not allow me to edit the document root, we are trying other methods, if none of them work I'll try this legacy version.
