### ISSUE TITLE
I can't see my stats & private key

### ISSUE THREAD

**Issue by r-a-n-y** [cydrobolt/polr#162]
I want to see the stats for my private links and the private key for another shortened link.

**Comment by cydrobolt** [comment]
At the moment, once the link is shortened you cannot see the key again. This is by design. You will need to recreate the link if you lose your key. You can see the destination of your link in your admin panel, however.

**Comment by cydrobolt** [comment]
You should be able to see your stats if you log into your admin panel. This is available in 2.0

**Comment by r-a-n-y** [comment]
how do i access my admin panel (i'm new)

**Comment by r-a-n-y** [comment]
is it the dashboard???

**Comment by r-a-n-y** [comment]
in dashboard, i only see the:
Link ending	Long Link	           Date (EST - NA)	             Secret

i don't see any of the link's stats

**Comment by cydrobolt** [comment]
You must be on 1.x, in that case. You should upgrade to 2.x for those features. You shouldn't directly git pull through, since there are breaking changes. You can start a new instance or wait until migrations are available.
