### ISSUE TITLE
url.domain.tld/1 tring to goto that dir

### ISSUE THREAD

**Issue by clevverent** [cydrobolt/polr#166]
Seems the tools is working correctly (setup process, db, etc), however when attempting to visit a created short url apache is actually trying to hit that direct (which obviously doesn't exist).

Thoughts version 1.5.1

**Comment by cydrobolt** [comment]
Hi, 

Do you have the .htaccess file at the root of your document root, and Polr at the root of your domain?

**Comment by cydrobolt** [comment]
Can you also check if mod_rewrite is available and turned on?

**Comment by clevverent** [comment]
No on .htaccess file
Polr is at doc root

# polr URL Shortener
<VirtualHost *:80>
 ServerName url.mjn.com
 ServerAlias url.mjn.com
 DocumentRoot /var/www/vhosts/url.mjn.com
 ErrorLog logs/url-error_log
 CustomLog logs/url-access_log combined
<Directory "/var/www/vhosts/url.mjn.com">
#  Require all granted
   Options Indexes FollowSymLinks
   AllowOverride All
   Order allow,deny
   Allow from all
</Directory>
</VirtualHost>

**Comment by clevverent** [comment]
mod_rewrite is enabled

Brent

**Comment by cydrobolt** [comment]
You need to make sure .htaccess is present. You can download it from the
git repo if you've lost it.

**Comment by cydrobolt** [comment]
Any luck? Have you tried 2.0 on branch `master`? Perhaps that can fix these problems.
