### ISSUE TITLE
[Feature Request] User can edit/delete own shortened URLs

### ISSUE THREAD

**Issue by robpomeroy** [cydrobolt/polr#173]
Hi,

I have Polr in use in two production sites, both private URL shorteners; we're using it for convenient marketing purposes. And it's great - thank you! Loving Polr for its simplicity, lightweightness and my company is committed to open source.

I'm not sure if I overlooked a setting somewhere, but there doesn't seem to be any way for my users to edit or delete their own shortened URLs. Is that possible? And if not, would you consider adding that as a feature? At the moment, I'm logging on as the administrator and doing it for them, which will become less sustainable as our use of Polr expands.

Many thanks,

Rob

**Comment by cydrobolt** [comment]
Hey @robpomeroy! Thanks for the feedback! 

At this point, users cannot edit or delete their own URLs. The reasoning behind this was that misleading links would be possible if users were able to edit or delete their own links. As with many other URL shorteners, allowing link deletion could possibly be dangerous.

For instance, user 1 could shorten a link to an innocuous site. Then, the same user could delete the link, and reshorten the link with a dangerous link. Since Polr offers links that come in order, user 2 could send the link thinking that it is a safe site, but actually redirect others to the dangerous link. 

Perhaps we can implement an option for situations where the users are trusted, in which this could be useful :)

**Comment by robpomeroy** [comment]
Understood. I guess my use case is quite niche.

**Comment by BrainStone** [comment]
Still being able to change the destination might be a good idea.

**Comment by fourprime** [comment]
@robpomeroy I'd just switch to Yourls if I were you. The excuse cydrobolt provided is ridiculous. You can edit, and see analytics of your shortlinks in Yourls.

@cydrobolt If you're going to go down "what-ifs" then you could just say someone with malicious intent could forward from one shortlink to another. They could change the page it's pointing to OR have that page forward anywhere they want. This feature missing is one of the only reasons I'm not implementing Polr, you've made it mostly useless for professional use.

**Comment by overint** [comment]
Do you mean editing the destination of an already created URL?
I don't think many site have this feature since it could potentially be abused, however it would be easy enough to add a setting to allow users to edit/delete their own links.

**Comment by overint** [comment]
@cydrobolt what are you thoughts on this?

**Comment by stevenklar** [comment]
Would like to see this feature, too.

**Comment by cydrobolt** [comment]
Yeah, I can see this working out if we have it as an option rather than a builtin

**Comment by stevenklar** [comment]
Would you like to see it in .env for activation or in admin as checkbox.
The first one would be more easy of cause with a default of false.

I might push a pull-request during the day.

Laravel Artisan here ;-)

**Comment by cydrobolt** [comment]
A standard option in the env would be best, I think :)

**Comment by acidjazz** [comment]
+1

**Comment by jacobgraf** [comment]
This would be really handy. Any progress on adding this functionality?

**Comment by cydrobolt** [comment]
https://editor.datatables.net/examples/inline-editing/simple seems like a way we could implement editing and creating new URLs without too much hassle. It also seems to support creating new rows. Although it doesn't seem like Laravel DataTables supports these features out of the box, we could try implementing the endpoints.

**Comment by cydrobolt** [comment]
#335
