### ISSUE TITLE
Allow user creation from the admin panel and allow "promotion" from admin panel

### ISSUE THREAD

**Issue by BrainStone** [cydrobolt/polr#177]
Having your site is quite nice and it's working great so far. The only hassle so far has been the issue that as an admin I cannot create a new account. This is an issue since we don't want random people singing up so by default account creation on the login page is disabled. And so when I want to create a new account I have to enable account creation and add the account through the registration panel.

Also being able to promote other users to the admin status might be a good idea.

**Comment by ashazar** [comment]
I added creating new users from admin panel.
You can also change user roles, and activate/deactivate user.
Made a pull request.
