### ISSUE TITLE
Improve error page when using invalid secrets and links

### ISSUE THREAD

**Issue by BrainStone** [cydrobolt/polr#179]
Links with invalid secrets and links generate a really ugly page.
A simple 404 in the page-style would be just fine.

Example links:
Invalid secret:
https://l.cb-net.work/1/xxxx
Invalid link:
https://l.cb-net.work/489

**Comment by cydrobolt** [comment]
There is actually a nice 404 page. Turn off APP_DEBUG in your env file and you should see it.

**Comment by BrainStone** [comment]
My bad.
