### ISSUE TITLE
If username contains a dot api info modal does not display on click

### ISSUE THREAD

**Issue by johno-av** [cydrobolt/polr#185]

**Comment by cydrobolt** [comment]
Looks like we need to escape the username to remove CSS selector symbols using https://learn.jquery.com/using-jquery-core/faq/how-do-i-select-an-element-by-an-id-that-has-characters-used-in-css-notation/

The problematic lines should be in `public/js/admin.js`

**Comment by mikefm** [comment]
same here, I used an email address as username/email to keep things simple. the css selector with "@" doesnt work...

btw: nice project, love it!

**Comment by cydrobolt** [comment]
Yeah. I need to fix this ASAP
