### ISSUE TITLE
Installation without composer

### ISSUE THREAD

**Issue by xunilarium** [cydrobolt/polr#189]
Hi
Is it possible to install Polr without composer? I want to install it on a host not a server....

**Comment by cydrobolt** [comment]
Yes. Simply clone the repository and you should be good. The composer vendor files are included in the repository.

**Comment by xunilarium** [comment]
But how? I can't understand your installation guide. I cloned it but I can't find setup folder in it.

**Comment by cydrobolt** [comment]
Polr uses Laravel routing. There isn't a physical folder, but you will be able to navigate to `yoursite.com/setup`. Have you tried to access the URL? You will need to use the `.htaccess` file provided.

**Comment by xunilarium** [comment]
Thanks, the problem was solved, I installed it successfully...

**Comment by cydrobolt** [comment]
Cool, great :+1:
