### ISSUE TITLE
Creation  Time

### ISSUE THREAD

**Issue by xunilarium** [cydrobolt/polr#190]
Hi
Creation times that shows in link section are wrong, I check my system time and php.ini timezone and both is correct.

**Comment by xunilarium** [comment]
Is there any update?

**Comment by cydrobolt** [comment]
I'm not sure what could be causing your error. It's likely that the time could be in UTC. Polr doesn't handle the creation of the timestamp; Laravel's ORM does. See https://github.com/cydrobolt/polr/blob/master/database/migrations/2015_11_04_015813_create_link_table.php#L33

https://laravel.com/docs/5.0/eloquent#timestamps
