### ISSUE TITLE
[Feature] How to inject script into redirect page?

### ISSUE THREAD

**Issue by joglomedia** [cydrobolt/polr#191]
Hi,

i am new to try Polr, i have a little question
is it possible to inject simple javascript (ex: analytic script) in to redirection page, so this script loaded in few miliseconds before url redirected to the real url?
how to do that?

Thanks

**Comment by cydrobolt** [comment]
Hm, we don't currently have a redirection page. We actually directly redirect the user to the page they requested. You can edit the code to create an intermediate page, though. Look into `LinkController.php` and `routes.php` to add a route for an intermediate page.
