### ISSUE TITLE
Question: what is the status of this project?

### ISSUE THREAD

**Issue by sveeke** [cydrobolt/polr#195]
Hi,

I was looking for url shorteners and came accross polr. But since the releases were rather old (official/stable 1.5.1 not supported anymore and 2.0.0 in alpha/beta) I don't know for sure which one to install and if it is still maintained. So what is the status of the project? It looks cool by the way!

Thanks in advance.

**Comment by cydrobolt** [comment]
Hey, 

Polr is still maintained and supported. I've been a bit busy recently, so I haven't had the opportunity to work on it as much. 

You should clone master to install 2.0 "beta". It has more features and is likely more stable than 1.5.1 at this point

**Comment by sveeke** [comment]
Hi Cydro,

Thanks for the quick reply. I also asked on IRC but no one responded so I didn't expect such a quick answer :+1: . Cool that it is still maintained, I will try to install the 2.0 beta version this week so I can test polr. 

Are you looking for any specific feedback or tests of polr? If I install it it's little effort to look at certain things more closely.

**Comment by cydrobolt** [comment]
@sveeke ah, yeah, usually not connected to IRC at work. 2.0 has been around for over 6 months, but I haven't had the time to finalise and test the release before launching 2.0 and replacing 1.5.1. It's being delayed by some nice-to-haves but no big issues with 2.0.

If you could make sure all the small components are working, that would be great :)

Thanks!

**Comment by sveeke** [comment]
Hi,

I tried to install polr tonight but it does not seem to work. The automatic setup script (after copying .env.setup -> .env) does not work since the /setup/ link is not available when I go there with the web browser. But the manual script also does not work since I get the following error:

`root@cupcake:/var/www/html/web/polr# php artisan migrate --force

  [PDOException]
  SQLSTATE[HY000] [2005] Unknown MySQL server host '{{{$localhost}}}' (29)`
I also tried with 127.0.0.1 but that also failed. I don't know PDO by the way, is this some kind of other way of using MariaDB/MySQL? 

Other scripts that use MySQL/MariaDB will work with this settings, so that is why I post it here :).

Thanks in advance!

**Comment by cydrobolt** [comment]
Did you properly add the Polr configs to Apache? What is the extra "web" folder? Is that considered in the Apache config?

**Comment by sveeke** [comment]
Hi,

These are my apache configs:

`root@cupcake:/etc/apache2/sites-available# cat i11.nl-http*

<VirtualHost *:80>
        ServerName www.i11.nl
        ServerAlias i11.nl
        ServerAdmin mail@sebasveeke.nl
        DocumentRoot /var/www/html/web/polr/public

        <Directory /var/www/html/web/polr/public>
        Require all granted
        Options Indexes FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
RewriteEngine on
RewriteCond %{SERVER_NAME} =www.i11.nl [OR]
RewriteCond %{SERVER_NAME} =i11.nl
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]
</VirtualHost>

<IfModule mod_ssl.c>

<VirtualHost *:443>
        ServerName www.i11.nl
        ServerAlias i11.nl
        ServerAdmin mail@sebasveeke.nl
        DocumentRoot /var/www/html/web/polr/public

        <Directory /var/www/html/web/polr/public>
        Require all granted
        Options Indexes FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
SSLCertificateFile /etc/letsencrypt/live/test.sebasveeke.nl/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/test.sebasveeke.nl/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
`
polr is placed in /var/www/html/web/polr.

I made this configuration file:

`root@cupcake:/var/www/html/web/polr# cat .env
APP_ENV=production

# Set to true if debugging
APP_DEBUG=false

# 32-character key (e.g 3EWBLwxTfh%*f&xRBqdGEIUVvn4%$Hfi)
APP_KEY={{$RdyPQbQBp5NFFtV39RyFX6xft3qEjOas}}

# Your app's name (shown on interface)
APP_NAME={{$iEleven Link Shortener}}

# Protocol to access your app. e.g https://
APP_PROTOCOL={{$https://}}

# Your app's external address (e.g example.com)
APP_ADDRESS={{$i11.nl}}

# Your app's bootstrap stylesheet
# e.g https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/flatly/bootstrap.min.css
APP_STYLESHEET={{$https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/flatly/bootstrap.min.css}}

# Set to today's date (e.g November 3, 2015)
POLR_GENERATED_AT={{$July 10, 2016}}

# Set to true after running setup script
# e.g true
POLR_SETUP_RAN={{$POLR_SETUP_RAN}}

DB_CONNECTION=mysql
# Set to your DB host (e.g localhost)
DB_HOST={{{$127.0.0.1}}}
# DB port (e.g 3306)
DB_PORT={{$3306}}
# Set to your DB name (e.g polr)
DB_DATABASE={{{$polr}}}
# DB credentials
# e.g root
DB_USERNAME={{{$polr}}}
DB_PASSWORD={{{$4NoQjUTGKl76q8xZ6NmAV3tMj7rbRDrf}}}

# Polr Settings

# Set to true to show an interface to logged off users
# If false, set the SETTING_INDEX_REDIRECT
# You may login by heading to /login if the public interface is off
SETTING_PUBLIC_INTERFACE={{$true}}

# Set to true to allow signups, false to disable (e.g true/false)
POLR_ALLOW_ACCT_CREATION={{$true}}

# Set to true to require activation by email (e.g true/false)
POLR_ACCT_ACTIVATION={{$false}}

# Set to true to require users to be logged in before shortening URLs
SETTING_SHORTEN_PERMISSION={{$false}}

# You must set SETTING_INDEX_REDIRETC if SETTING_PUBLIC_INTERFACE is false
# Polr will redirect logged off users to this URL
SETTING_INDEX_REDIRECT={{$ST_INDEX_REDIRECT}}

# Set to true to enable password recovery
SETTING_PASSWORD_RECOV={{$ST_PASSWORD_RECOV}}

# Set to true to generate API keys for each user on registration
SETTING_AUTO_API={{$ST_AUTO_API}}

# Set to true to allow anonymous API access
SETTING_ANON_API={{$ST_ANON_API}}

# Set each to blank to disable mail
@if($MAIL_ENABLED)
MAIL_DRIVER=smtp
# e.g mailtrap.io
MAIL_HOST={{$MAIL_HOST}}
# e.g 2525
MAIL_PORT={{$MAIL_PORT}}
MAIL_USERNAME={{$MAIL_USERNAME}}
MAIL_PASSWORD={{{$MAIL_PASSWORD}}}
# e.g noreply@example.com
MAIL_FROM_ADDRESS={{$MAIL_FROM_ADDRESS}}
MAIL_FROM_NAME={{$MAIL_FROM_NAME}}
@endif

APP_LOCALE=en
APP_FALLBACK_LOCALE=en

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=database

_API_KEY_LENGTH=15

# FILESYSTEM_DRIVER=local
# FILESYSTEM_CLOUD=s3

# S3_KEY=null
# S3_SECRET=null
# S3_REGION=null
# S3_BUCKET=null

# RACKSPACE_USERNAME=null
# RACKSPACE_KEY=null
# RACKSPACE_CONTAINER=null
# RACKSPACE_REGION=null

# Set to 32 or 62 -- do not touch after initial configuration
POLR_BASE={{$ST_BASE}}

# Do not touch
POLR_RELDATE={{env('VERSION_RELMONTH')}} {{env('VERSION_RELDAY')}}, {{env('VERSION_RELYEAR')}}
POLR_VERSION={{env('VERSION')}}
POLR_SECRET_BYTES=2

TMP_SETUP_AUTH_KEY={{$TMP_SETUP_AUTH_KEY}}
`

**Comment by sveeke** [comment]
I deleted my configuration file and tried it again with the default automatic setup, it seems to work now!

**Comment by sveeke** [comment]
It works now! I don't know what was wrong with the previous one, I didn't change the apache configs.

It runs on https://i11.nl (could not find beter domain names with three chars :P).

Thanks!

**Comment by sveeke** [comment]
One more question. I am probably looking in the wrong places, but I can't find where I can change the theme of polr. I found the link of the sites bootstrap css in .env, but I don't know what I should enter for things like Blue Metro, Orange and Midnight Black. I tried to find these with 'find' but there were no results. Do you know where I can find these skins so I can try them all out? :).

**Comment by cydrobolt** [comment]
@sveeke try this: https://www.bootstrapcdn.com/bootswatch/
