### ISSUE TITLE
Setup the Android App URL Manager

### ISSUE THREAD

**Issue by UdoKifferbrehl** [cydrobolt/polr#198]
Hi, I am not sure if it is possible to make a pull request for wiki pages. 
I wrote an article about the setup of the Android app URL Manager here in my fork: https://github.com/UdoKifferbrehl/polr/wiki/Setup-the-Android-App-URL-Manager
You are very welcome to use that. Thanks!

**Comment by cydrobolt** [comment]
I've added it to the wiki. Thank you!
