### ISSUE TITLE
Issue Behind Reverse Proxy

### ISSUE THREAD

**Issue by nprail** [cydrobolt/polr#204]
I recently setup Polr for testing and I am liking it a lot better then what we are using now. I have come across an issue though. I have Polr on a VM behind a reverse proxy. The issue is that all of the links go to the IP of the VM not the reverse proxy address. That makes for a quite useless URL shortener...

For example: If I go to https://fsft.us/admin/ it redirects me to http://backend.ip/login so that I can login. 

If I go to https://fsft.us/login, it works but when I try to login, it redirects to http://backend.ip which redirects to https://filiosoft.com since that is the default redirect. If I go back to the login page, it shows that I am logged in but all the links go to the virtual machine's IP. 

Here is my NGINX config:
```
server {
    server_name fsft.us;

    listen 443 ssl;

    location / {
    	proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        proxy_pass  http://<backend_ip>:80;
    }
}
```
I removed some of the SSL config because there was a lot.

**Comment by cydrobolt** [comment]
Hey @nprail! Thanks for opening an issue on GitHub. I've encountered this bug before, but we were able to solve it by changing some fastcgi_params for php-fpm.

However, it looks like you're using nginx to reverse proxy requests to port 80, which is an Apache server? 

Try adding this line above your proxy_pass:

`proxy_set_header Host $server_name`

Let me know if that works :)

**Comment by nprail** [comment]
I am using a NGINX server to reverse proxy Apache which is on another server. I tried adding that but it still has the incorrect links. You can see what it is doing for yourself. https://fsft.us/login should be reachable anywhere. 

Thanks for the help!

**Comment by cydrobolt** [comment]
Hmm, it is refusing my connection. Can you check if it's up?

**Comment by nprail** [comment]
Oh, yeah. I forgot that we are experimenting with our network currently so it is inaccessible outside our network...

**Comment by cydrobolt** [comment]
Ah, no worries. Can you try changing the X-Forwarded-For-Host to $server_name instead of $host?

**Comment by nprail** [comment]
It works now! As it turns out, all I needed was `proxy_set_header Host $server_name;` but it didn't work at first because I didn't have a semi-colon at the end! Thanks so much for the help!

**Comment by cydrobolt** [comment]
Ah, awesome! Yeah, I should definitely add some instructions re: reverse proxies into the troubleshooting section :)

Don't hesitate to ask if you need anything else :)
