### ISSUE TITLE
Allow Origin header is needed in order to make a chrome extension

### ISSUE THREAD

**Issue by ctodobom** [cydrobolt/polr#205]
Hi,

I've made changes to a chrome extension, [available on my github](https://github.com/ctodobom/URL-Shortener) adding support to Polr.

When dealing with it, the extension refused to accept the answer from Polr because the absence of a header authorizing it to use.

The missing header shoud be:
```
Access-Control-Allow-Origin: *
```

I've made a small patch that fixes this, but I think that you may want to place it on another part of your code.

My patch is attached here: [allow-origin.zip](https://github.com/cydrobolt/polr/files/425628/allow-origin.zip)

**Comment by ctodobom** [comment]
My contribution to URL-Shortener chrome extension was accepted ( https://github.com/Wassup789/URL-Shortener/pull/1 ) , but it doesn't work without adding the `Access-Control-Allow-Origin` header.

**Comment by overint** [comment]
This is a good idea, allows to the API to be used by JS outside the site. Fixed by #230
