### ISSUE TITLE
Create upgrade guide

### ISSUE THREAD

**Issue by cydrobolt** [cydrobolt/polr#208]
Create an upgrade guide with instructions to upgrade to any given version with breaking changes, DB changes, or `.env` changes. 

Emphasis should be placed on backing up DB, settings, and files with instructions.

**Comment by mhow2** [comment]
Hi, I'm running '1.4.1 Stable' and I would need those instructions to upgrade to 2.0.0. Thanks !

**Comment by Spheerys** [comment]
I'm also interested by keeping my old redirection's database after upgrading to 2.0.0

**Comment by mhow2** [comment]
@cydrobolt , would you agree to provide us preliminary instructions so we can test up and help with that task ? Thanks !

**Comment by Spheerys** [comment]
No time to help us to upgrade from 1.4 to 2.0 ? :(

**Comment by mhow2** [comment]
I don't understand why I has been closed. Maybe a duplicate with #123 ? I've been not able to run the instructions you sent me in PM. I did write you back. I would need help if possible, that might be useful to some people around too.
