### ISSUE TITLE
Allows to short url without entering long link

### ISSUE THREAD

**Issue by vishals321** [cydrobolt/polr#212]
I tried demo.polr.me and it allowed me to shorten url without entering any url.I got this link with custom option http://demo.polr.me/vishal/d059 and another one without custom option.please have a look at this

**Comment by cydrobolt** [comment]
Could you please elaborate on what issue you're reporting? Are you proposing to add URL validation? 
Yes, it is possible to create a link that is not a valid URL. We allow different protocols and URL formats (e.g mailto:).

What expected behaviour are you proposing?

**Comment by vishals321** [comment]
Try shortning link with just "http://".

**Comment by cydrobolt** [comment]
Hmm, maybe we can set the input field type to `url`. Chrome seems to validate this pretty loosely, at least.
