### ISSUE TITLE
toastr.js.map missing

### ISSUE THREAD

**Issue by ToeiRei** [cydrobolt/polr#216]
Chrome console bugs that this file isn't there.

Maybe it's https://raw.githubusercontent.com/CodeSeven/toastr/master/build/toastr.js.map ?

**Comment by cydrobolt** [comment]
This should be fine. Map files are used to map minified JS files to their source files for debugging. However, we're only using toastr as a library; we're not actually debugging or developing toastr, so it's totally fine that we don't have the map file.
