### ISSUE TITLE
Add shortcut URL to "Link Ending" in Dashboard

### ISSUE THREAD

**Issue by andreasscherbaum** [cydrobolt/polr#218]
The column "Link Ending" in the dashboard should really be a link, pointing to the shortcut URL. This way, people can copy and re-use the link.

## Expected Behavior
Make the text in the "Link Ending" column a link to the URL shortcut.

## Current Behavior
Right now, if I want to re-use a link, I have to build the link on my own, using the base URL and the shortcut.

## Your Environment
Polr 2.0rc1

**Comment by overint** [comment]
I think this is a good idea. I'll submit a pull soon.

**Comment by andreasscherbaum** [comment]
Thank you for implementing this!

**Comment by overint** [comment]
No worries :)
