### ISSUE TITLE
Create users from admin panel [enhancement]

### ISSUE THREAD

**Issue by lgg** [cydrobolt/polr#220]
It will be really cool to provide this functionality for those who needs only few users(e.g. admin friends). 

Also it will be ok to enable registration only with invite codes(with disabled email).

**Comment by overint** [comment]
That sounds like a good idea for a private URL shortener. 
Maybe we could have a new settings tab to manage options, create new users and other admins tasks?

**Comment by ashazar** [comment]
I added creating new users from admin panel. And made a pull request.
But not added registration with invite codes.

**Comment by BrainStone** [comment]
See #177
