### ISSUE TITLE
Future IFTTT implementation

### ISSUE THREAD

**Issue by cydrobolt** [cydrobolt/polr#222]
Implement an IFTTT integration to allow automatic shortening of URLs through IFTTT triggers

**Comment by spekulatius** [comment]
Great idea :)

**Comment by cydrobolt** [comment]
This was suggested on IRC, but through some further research, it seems unlikely that we can do this. Seems like publishing a channel on IFTTT has a cost. https://www.quora.com/How-can-I-create-a-new-IFTTT-channel-to-work-with-my-Internet-Of-Things-product
