### ISSUE TITLE
Show shortlink statistic by adding "+" at end of link (PR #244, #245, #246)

### ISSUE THREAD

**Issue by force73** [cydrobolt/polr#247]
I have updated two files and added one view file as a startpoint to integrate a statistic page for every shortlink.

Ideas for discusssion:

1. In next step I would outsource the ending for call the statistic page from hardcoded "+" to a self setted string (in .env file).
2. Is the statistic feature already in progress and is there already a framework for (diagrams etc.) prefered to use?
3. To make a useful stats page we should update the program to log also the timestamp and maybe (data protection) the parted (XXX.XXX.0.0) IP of link caller to get a better overview about called links.

Please let me know everything you all think about. :-)

Greetings,
Christian

**Comment by cydrobolt** [comment]
We're looking into adding more statistics for links, but we're not currently prioritising a public stats page. This used to be a feature, but we've removed it since. '

Current focus re: analytics will be in the direction of #231
