### ISSUE TITLE
Add support for database connection through unix socket instead of port

### ISSUE THREAD

**Issue by abba23** [cydrobolt/polr#248]
## Expected Behavior

During the setup (one the setup page) one should be able to specify the path to the socket of a mysql instance instead of a port.
## Current Behavior

You can only choose a port. Specifying the path to a socket is not possible.
## Possible Solution

I specified the socket path in the hostname field like this:
`localhost;/var/run/mysqld/mysqld.sock`
as a workaround.

http://stackoverflow.com/a/39509268
## Context

I tried to install Polr on my server. The mysql instance running there uses a socket for database connections. Polr didn't seem to support this.
## Your Environment

- Version or latest commit hash (`git rev-parse HEAD`):
  a5f1fda788e4c1eb5ad6f3852ebcf2a257719210
- Environment name and version (e.g. Chrome 39, PHP 7.0, etc):
  Ubuntu 16.04, PHP 7.0

**Comment by jcalonso** [comment]
You can edit the .env manually and the db connection details.
Btw, how did you install mysql?  by default uses host+port, do you really need to use unix sockets?

**Comment by cydrobolt** [comment]
We use Laravel to create a database connection, so we don't directly have control over then connection. Some StackOverflow answers suggested your workaround and potentially UNIX_SOCKET in the env

**Comment by abba23** [comment]
> how did you install mysql? by default uses host+port, do you really need to use unix sockets?

I didn't specifically set it up like that. It might be a preset in the Ubuntu image of the VPS service I'm using.

**Comment by jcalonso** [comment]
I see, thanks for clarifying, since most MySQL installations use TCP (host/port) that's why is the default option. It will be up to @cydrobolt  to decide if adding the Unix socket to the wizard worth the effort. In my opinion since its a small percentage of the cases I would leave it as it is, since you can always edit the `.env` manually to set it.

**Comment by overint** [comment]
As this can be fixed manually when required and is rare I do not think it's worth adding to the setup.
