### ISSUE TITLE
create a logo for polr

### ISSUE THREAD

**Issue by cydrobolt** [cydrobolt/polr#25]
preferably a silhouette for the navbar logo, and a rectangular logo to replace "polr" in the middle of the page. we might also try ascii art for the main logo

**Comment by JHSheridan** [comment]
Trying to make good on a resolution to bring more design to open source projects.

Thought behind the iceberg is that it represents what a URL shortener does and is a hat tip to the Polr name itself. Polr provides the tip of the iceberg (shortened URL), but there's so much more underneath (full website).

These are all very rough... no cleanup done, so excuse the rough edges and non-uniform line angles. I wanted to put the idea to paper and post it before I spent any significant time with it.

![polr](https://cloud.githubusercontent.com/assets/725786/7217607/cb5094ec-e5fa-11e4-9343-301e4e522adb.png)

Thoughts?

**Comment by sckasturi** [comment]
Hmm, I personally like number 1, I think that looks best. With number 2 at a close second.

So basically the order you placed 'em in is the order I like.

Although it does remind me of this… http://en.wikipedia.org/wiki/Wikisource#Logo_and_slogan

**Comment by Cydrobolt** [comment]
@JHSheridan the third one looks awesome! If we could get the project name ("Polr") in Open Sans Bold, I would add this as the official logo. Maybe try some colors in the peaks, but if not simply adding "Polr" in Open Sans Bold under the 3rd logo would be great!

**Comment by JHSheridan** [comment]
I'll try a few more iterations of the above including adding "Polr" somewhere in there.

Thanks for the feedback, all.

**Comment by Cydrobolt** [comment]
Complimentary colors would probably work best for the logo, I think

**Comment by Schokobecher** [comment]
Since it's been almost 8 months... I could recreate the above including some color variants and the 'Polr' tag/name

**Comment by cydrobolt** [comment]
I actually ended up making my own logo, but if anyone could implement that unique mountain design, I would be down

![image](https://cloud.githubusercontent.com/assets/1058150/11324808/d4e74c74-910a-11e5-83d6-e0b56898ce7b.png)

**Comment by Schokobecher** [comment]
![polr](https://cloud.githubusercontent.com/assets/1642634/11325144/ac053c08-9146-11e5-8eab-415a592cc690.png)

A quick sketch

**Comment by cydrobolt** [comment]
@Schokobecher I really like that! Maybe if we placed "Polr" to the right of the mountain logo, with the two next to each other horizontally, maybe that would look nicer.

Kind of like the Polr logo I created, but instead of the link icon, we can put the mountain logo there. 

What do you think?

**Comment by Schokobecher** [comment]
![polr_v2](https://cloud.githubusercontent.com/assets/1642634/11326162/03cd8c68-9162-11e5-8c96-d8b731ac1e0a.png)


Someting like that?
SVG is [here] (http://imgh.us/POLR_LOGO.svg)

**Comment by cydrobolt** [comment]
Yeah, something like that! I think I can edit it a little bit in Inkscape and I'll upload something soon

**Comment by Schokobecher** [comment]
Yeah, since I know nothing about Inkscape and vector-based graphics it's the best for all of us when you finetune it :+1:

**Comment by strugee** [comment]
@cydrobolt did you ever finish up the logo? I'm writing an Android client to Polr and it'd be great to have this logo :)

**Comment by cydrobolt** [comment]
@stringer yeah. We're using the one with the link and black text for right now, but that might change later

**Comment by strugee** [comment]
@cydrobolt s/stringer/strugee/? I'm still a little confused which logo you mean. [This one][1]?

 [1]: https://github.com/cydrobolt/polr/issues/25#issuecomment-158774697

**Comment by cydrobolt** [comment]
Oops, typo! Yes, you're correct about the logo. It is the black logo with the link icon.
