### ISSUE TITLE
'Dotenv: Environment file .env not found or not readable.

### ISSUE THREAD

**Issue by BPCreative** [cydrobolt/polr#256]
I am getting this php readout:

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Dotenv: Environment file .env not found or not readable. Create file with your environment settings at /home/polr9/b-px.xyz/polr/bootstrap/../.env' in /home/polr9/b-px.xyz/polr/bootstrap/vendor/vlucas/phpdotenv/src/Dotenv.php:33 Stack trace: #0 /home/polr9/b-px.xyz/polr/bootstrap/app.php(5): Dotenv::load('/home/polr9/b-p...') #1 /home/polr9/b-px.xyz/polr/public/index.php(14): require('/home/polr9/b-p...') #2 {main} thrown in /home/polr9/b-px.xyz/polr/bootstrap/vendor/vlucas/phpdotenv/src/Dotenv.php on line 33

I was on chat with my host provider for an hour or more last night.  We worked out many of the issues that I was having with setup, but this one we did not resolve. It is probably something I am overlooking, but if you could take a look at the error and give me your feed back, I would really appreciate it. 

-- Your Environment --
This is the path on the server: /home/polr9/b-px.xyz/polr/public
- I have it configured to pull from /public as the main directory

I installed Polr via ssh, but it didn't install the "vendor" directory.  I was getting an error in regards to this.  So, I manually added that via FTP (seems weird to me).
- Because of the path the previous error was throwing, I installed vendor here: /home/polr9/b-px.xyz/polr/bootstrap/vendor

**Comment by cydrobolt** [comment]
Did you copy .env.setup to .env in your root directory?

**Comment by BPCreative** [comment]
I copied the contents of .env.setup into .env in the root directory

**Comment by BPCreative** [comment]
I also ran the command in ssh

**Comment by cydrobolt** [comment]
Is there a reason you installed your vendor directory bootstrap/vendor? You should install the vendored files in /vendor at the root of the repository. 

Because you installed the vendored files incorrectly, it's looking for your env file elsewhere.

**Comment by BPCreative** [comment]
I was getting an error that showed it was looking for the vendor directory inside of the bootstrap directory.

**Comment by BPCreative** [comment]
I just put the vendor dir in: /home/polr9/b-px.xyz/polr

This is the new error: 

Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /home/polr9/b-px.xyz/polr/bootstrap/app.php on line 3

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/home/polr9/pear/share/pear') in /home/polr9/b-px.xyz/polr/bootstrap/app.php on line 3

**Comment by BPCreative** [comment]
This is what I have on line 3:    require_once __DIR__.'/../vendor/autoload.php';

**Comment by cydrobolt** [comment]
Right; that error doesn't imply that you should install the vendor files in the bootstrap directory. What seen the contents of the bootstrap folder? Did you use composer to install the vendor files? 

You can try deleting the vendor files and reinstalling them through composer in the root directory

**Comment by BPCreative** [comment]
I did not use composer to install the vendor files.  I used composer for the main install, but the vendor files weren't installed.

**Comment by cydrobolt** [comment]
If this is shared hosting, your PHP version might be out of date. What version if PHP are you running?

**Comment by BPCreative** [comment]
5.6

**Comment by BPCreative** [comment]
It is VPS, but I don't have sudo permissions, which makes it much like shared

**Comment by BPCreative** [comment]
Is there a tutorial for reinstalling the vendor directory via composer?
This is not my forte

**Comment by cydrobolt** [comment]
Okay, I see. You have to use composer to install the vendor files or the autoloader won't have the correct path. In the docs, there are instructions to download composer and install the dependencies. 

Alternatively, you can download the vendored files from a previous commit before we deleted the vendor files.

**Comment by cydrobolt** [comment]
Docs: http://docs.polr.me/en/latest/user-guide/installation/

There are instructions regarding composer

**Comment by BPCreative** [comment]
I followed those instructions previously, but I just retried this...

# download composer package
curl -sS https://getcomposer.org/installer | php
# update/install dependencies
php composer.phar install --no-dev -o

I received an error: 

[RuntimeException]
  Could not scan for classes inside "database/" which does not appear to be a
   file nor a folder

**Comment by BPCreative** [comment]
What file ties into the database? It seems to be searching for the database and not finding it.

**Comment by cydrobolt** [comment]
I'm not able to replicate your error. Perhaps try starting from scratch using the docs or download an older release (see releases tab)

**Comment by BPCreative** [comment]
I can give you access to the server to look at it...that may help

**Comment by cydrobolt** [comment]
You can email me if you'd like, but I won't have much time until the weekend.

**Comment by BPCreative** [comment]
Okay, what is your email?

**Comment by BPCreative** [comment]
Oh, found it

**Comment by BPCreative** [comment]
I sent the login data over.  Thanks again!

**Comment by BPCreative** [comment]
Wow, it seems that I have gotten past that problem, but there is now a totally different error: 

Fatal error: Class 'Yajra\Datatables\DatatablesServiceProvider' not found in /home/polr9/b-px.xyz/polr/vendor/laravel/lumen-framework/src/Application.php on line 268

Line 367-269:
```ssh
if (! $provider instanceof ServiceProvider) {
            $provider = new $provider($this);
        }
```

**Comment by BPCreative** [comment]
When I am in the setup page, under Application Settings, can I change this stuff later on?

**Comment by cydrobolt** [comment]
You can edit the env file later on if you'd like.

**Comment by birhannega** [comment]
I have same issue which is not solved yet
