### ISSUE TITLE
How to set time zone? 

### ISSUE THREAD

**Issue by Steve-luo** [cydrobolt/polr#257]
I'm running Polr on apache, Ubuntu 14.04. The time zone on Ubuntu is configured correctly, but the timestamp in Polr seems to be still UTC. How can I set time offset for Polr?

**Comment by jcalonso** [comment]
Php has its own time zone setting, look at the `php.ini` file there is a time zone parameter you can set. Don't forget to restart php-fpm (if using it)

**Comment by Steve-luo** [comment]
@jcalonso Hi, thanks for the tip. However, the timezone in php.ini is configured correctly as well.

**Comment by jcalonso** [comment]
Sorry @Steve-luo, aparently Lumen overwrites that variable for UTC, you can set that on Lumen, look at this: https://github.com/laravel/lumen-framework/issues/50

Just add a config to the `.env` file:

```
APP_TIMEZONE=Europe/London
```

**Comment by Steve-luo** [comment]
@jcalonso Thanks so much, this fixed the problem.
