### ISSUE TITLE
Allow input without http://

### ISSUE THREAD

**Issue by vhmrde** [cydrobolt/polr#259]
## Expected Behavior
User can copy and paste any URL, polr will use them and add automatically http://

## Current Behavior
Field is prefilled with the value 'http://'
Users copy an URL (mostly from the browsers adress bar, i guess) into the polr field. 
Now it looks like this: http://https://www.google.de/

They have to remove the prefilled value. Almost or all browsers show the protocoll in their adress bar and users mark the complete URL automatically by clicking into the adress bar.

But if you only use a placeholder (delete the value of the field) and an user want to insert an URL without http/https, polr will not process it.

For me, i only use a placeholder right now, it says 'http:// or https://'

## Your Environment
* Version or latest commit hash (`git rev-parse HEAD`):
Polr 2.0.0

**Comment by cydrobolt** [comment]
This has already been addressed. The latest git revision shouldn't be prefilling `http://`.

**Comment by vhmrde** [comment]
Oh sorry, i went through the list and didn't see an issue like this. Thank you!

**Comment by cydrobolt** [comment]
No worries :)
