### ISSUE TITLE
openshift install issues

### ISSUE THREAD

**Issue by zubair-xda** [cydrobolt/polr#260]
I am having hard time to figure out how can I install polr on openshift. Tried built in deployable app but getting error like server unable to handle request.
After searching little bit I came to know because of old php in openshift app is obsolete now.
But i just installed nginx php 7 using git on openshift can you please help me to install this on nginx with git.

**Comment by cydrobolt** [comment]
If I remember correctly, the process to install nginx with PHP 7 took a lot of tweaking. I can publish the configurations I used to install demo.polr.me on OpenShift when I get to my computer

**Comment by cydrobolt** [comment]
Try these configurations for the Nginx & PHP 7 cartridge: [nginx.d and php.d](https://github.com/cydrobolt/polr/files/623546/polrdemo.tar.gz)

Simply replace the `config` folder that the cartridge includes with the config folder from the archive. 

If I remember correctly, I used [this](https://github.com/pinodex/openshift-cartridge-nginx-php7) cartridge for Polr Demo.

**Comment by zubair-xda** [comment]
Thanks for replies. Tried your mentioned cartridge changed config from your given file. But what i have to do now? Tried installation tutorial but it gives no found error with setup :(

**Comment by cydrobolt** [comment]
Have you tried going to your site and accessing the setup script? Do you have the rest of the repo in the same folder?

**Comment by zubair-xda** [comment]
Sorry for late reply. I tried following installing instructions skipped Nginx modified part because used your given config file. Uploaded v2 polr source codes to repo/www folder but i am not sure what i have to do with env file where's that file :(

**Comment by cydrobolt** [comment]
Upload it directly to the root of the repository. There isn't any reason to put it in `www`

**Comment by zubair-xda** [comment]
Tried that now everything is in repo folder. But still getting 503 service unavailable error :( same with /setup.

**Comment by zubair-xda** [comment]
Anyhelp please :(

**Comment by cydrobolt** [comment]
Sorry, it's a bit difficult to debug the cartridge through text because I'm not sure what you've done with your configuration and folder structure. Have you tried Heroku? They have PHP 7 by default.

**Comment by zubair-xda** [comment]
No problem. Naah didn't tried

**Comment by zubair-xda** [comment]
Do i have to use your given config file with heroku? Or installation instructions are enough?

**Comment by cydrobolt** [comment]
No, you would need to read the heroku documentation.
