### ISSUE TITLE
Performance and scaling information

### ISSUE THREAD

**Issue by samtuke** [cydrobolt/polr#261]
Is there any documentation on Polr's performance and scalability? I would like to know whether it would be suitable for automatically shortening hundreds of millions of links over time, and what kind of resources and storage would be required. Thanks!

**Comment by cydrobolt** [comment]
I don't see why Polr would have trouble scaling properly. At larger loads, the database is usually the bottleneck; the framework is usually irrelevant. 

What kind of loads are you expecting? Are you expecting many concurrent requests or simply many links over time? 

Caching with redis or memcached with Laravel's caching feature would be helpful for many link lookups, while you might want to look at solutions like Amazon Kinesis or building a buffer for high volume concurrent insertions the database to avoid problems. 

Scaling the app shouldn't be an issue. IMHO you don't need to plan for thousands of millions of concurrent insertions before you reach a hundred. I'd suggest analysing for bottlenecks when a problem arises and adjusting then.

**Comment by samtuke** [comment]
That's very helpful, thanks @cydrobolt. Surges in demand would most likely be for writing, not reading, in our case (generating millions of links in a short time, then looking them up at varying intervals, spread out over days). I agree that testing with him dress/thousands and looking for bottlenecks would be a good idea. Also a fan of Redis.

**Comment by cydrobolt** [comment]
Yeah, I concur. You'll have to see how your specific situation pans out. Depending on where the bottlenecks are you can put resources and time where necessary. It's possible that you won't need to do any extra work to support the amount of traffic you expect to see.

**Comment by samtuke** [comment]
Thanks @cydrobolt
