### ISSUE TITLE
Can`t update to latest

### ISSUE THREAD

**Issue by urbels** [cydrobolt/polr#265]
git pull
composer install

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpunit/php-code-coverage 3.2.0 -> satisfiable by phpunit/php-code-coverage[3.2.0].
    - phpunit/php-code-coverage 3.2.0 requires php >=5.6 -> your PHP version (5.5.9) does not satisfy that requirement.
  Problem 2
    - Installation request for phpunit/phpunit 5.2.5 -> satisfiable by phpunit/phpunit[5.2.5].
    - phpunit/phpunit 5.2.5 requires php >=5.6 -> your PHP version (5.5.9) does not satisfy that requirement.
  Problem 3
    - Installation request for phpunit/phpunit-mock-objects 3.0.6 -> satisfiable by phpunit/phpunit-mock-objects[3.0.6].
    - phpunit/phpunit-mock-objects 3.0.6 requires php >=5.6 -> your PHP version (5.5.9) does not satisfy that requirement.
  Problem 4
    - Installation request for sebastian/code-unit-reverse-lookup 1.0.0 -> satisfiable by sebastian/code-unit-reverse-lookup[1.0.0].
    - sebastian/code-unit-reverse-lookup 1.0.0 requires php >=5.6 -> your PHP version (5.5.9) does not satisfy that requirement.
  Problem 5
    - Installation request for sebastian/resource-operations 1.0.0 -> satisfiable by sebastian/resource-operations[1.0.0].
    - sebastian/resource-operations 1.0.0 requires php >=5.6.0 -> your PHP version (5.5.9) does not satisfy that requirement.
  Problem 6
    - Installation request for sebastian/version 2.0.0 -> satisfiable by sebastian/version[2.0.0].
    - sebastian/version 2.0.0 requires php >=5.6 -> your PHP version (5.5.9) does not satisfy that requirement.

I can fix this only by updating php?

**Comment by cydrobolt** [comment]
You should be able to upgrade PHP to fix this. However, try `comppser install -no-dev -o`
That should skip phpunit, which isn't required to run Polr.

**Comment by cydrobolt** [comment]
@urbels I've released a patch for 2.1.0 in 2.1.1 to solve the class constant error. If you upgrade to 2.1.1 and run `composer install --no-dev -o`, you should be good to go :)

**Comment by urbels** [comment]
Thanks man!
