### ISSUE TITLE
Missing Glyphicons (Datatables)

### ISSUE THREAD

**Issue by overint** [cydrobolt/polr#271]
Seems datatables needs glyphicons for buttons, currently they render as grey squares ([screenshot](http://puu.sh/sUxd6/9e7ee06e79.png)).

Files Requested:
admin:1 GET http://localhost:8000/fonts/glyphicons-halflings-regular.woff2 
admin:1 GET http://localhost:8000/fonts/glyphicons-halflings-regular.woff 
admin:1 GET http://localhost:8000/fonts/glyphicons-halflings-regular.ttf 

It seems font-awesome is included now (did the project switch)? If so, we need to update the datatables to display font-awesome icons.

**Comment by cydrobolt** [comment]
I attempted to reproduce this issue, but I was unable to reproduce this issue either on an iPad not on a Windows desktop with Chrome. 

Can you provide more details?

**Comment by overint** [comment]
Strange, seems to have fixed itself. Guess it was just an issue with my browser.
