### ISSUE TITLE
Maximum people connected in the page

### ISSUE THREAD

**Issue by kenygamer** [cydrobolt/polr#272]
Hello,

I get an error when there are over 3 people connected at the same time in the website, it displays a limit in lib-core.php but I cannot find it.

Thank you.

**Comment by cydrobolt** [comment]
If you can give us the specific error you're receiving and your stack (e.g apache, mysql, polr, php versions), we might be able to help out.

Keep in mind that 1.x is deprecated and we don't officially support it besides providing security patches. Please try to use 2.x if possible.
