### ISSUE TITLE
Nginx 1.10.2 and polr wont work

### ISSUE THREAD

**Issue by Fytcher** [cydrobolt/polr#273]
I tried to install polr on my nginx webserver. After importing the database and saving it to the .env i get "403 Forbidden" 
Error in log: "[error] 13433#13433: *132 directory index of "/usr/share/nginx/polr/public/" is forbidden"

* Version or latest commit hash (`git rev-parse HEAD`): 91b9def4aa603a329194e2dcf8f2b4badbd66cb9
* Environment name and version (e.g. Chrome 39, PHP 7.0, etc): nginx 1.10.2, PHP 5.6 on debian 8

**Comment by cydrobolt** [comment]
Have you tried setting the permissions appropriately to make sure nginx can read the public directory? Have you given nginx access to the public folder in a configuration block in your conf? Could you do a ls -lah in your /var/www/polr/public and post your nginx configuration? You shouldn't need to place it in /var/www if you are using nginx, but it should still work.

**Comment by Fytcher** [comment]
The permissions are correctly. if i go to mydomain.com/admin for example everything works fine. Only if i go to mydomain.com/ i get the error. I guess something wont work with the rewrite 100% correct

**Comment by cydrobolt** [comment]
Okay. Maybe you can try adding `index index.php` in your nginx configuration block below `root /usr/share/nginx/polr/public`.

It would still be helpful if you could provide the permissions you have set for the directory and your nginx configuration, so I can look to see if you've correctly configured them.

**Comment by Fytcher** [comment]
"It would still be helpful if you could provide the permissions you have set for the directory and your nginx configuration, so I can look to see if you've correctly configured them."
I guess that wont be needed. Adding "index index.php;" already helped

**Comment by cydrobolt** [comment]
Does that work?

**Comment by cydrobolt** [comment]
Cool, sounds good.
