### ISSUE TITLE
indexes on links table

### ISSUE THREAD

**Issue by nickmoline** [cydrobolt/polr#274]
## Expected Behavior
- `short_url` should have a `UNIQUE` index for fast querying and prevention of duplicates
- `long_url` should have an `INDEX` for fast querying

To prevent slow `lookup` queries, I would recommend also adding a hash column to hash the long url down to a hash, and put the index on both the url and the hash, this makes for faster queries, especially when using particularly short (or integer) hashes like a `crc32()`

## Current Behavior
The only index on the `links` table is the primary auto-incrementing id on the `id` column

## Possible Solution

Create new migration to add the additional indexes and hash column.  Haven't tested the crc32 update part of this, but the rest of it should work fine
```php
class AddLinkTableIndexes extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('links', function (Blueprint $table)
        {
            $table->unique('short_url');
            $table->string('long_url_hash', 10)->nullable();
            $table->index(['long_url_hash', 'long_url'], 'links_long_url_index');
        });

        DB::query("UPDATE links SET long_url_hash = crc32(long_url)");
    }

    public function down()
    {
        Schema::table('links', function (Blueprint $table)
        {
            $table->dropUnique('links_short_url_unique');
            $table->dropIndex('links_long_url_index');
            $table->dropColumn('long_url_hash');
        });
    }
}
```

## Context
I'm trying to migrate a large data set of links (over 500k pre-shortened urls) from an existing antequated url shortener codebase, while I can handle the database translation just fine, I'm concerned to see no indexes on the links table, the performance both of looking up existing shortened urls and on creating new short urls is likely to be very poor.

**Comment by cydrobolt** [comment]
Thank you for this suggestion! I totally agree. There should definitely be an index on the `links` table to ensure queries run quickly even with large datasets. 

Would you like to create a PR to add your migration to `polr/database/migrations`? I can create a file myself, but it would be helpful and give you credit for your contributions if you could submit a PR.

In regards to adding a new column with a crc32 hash for looking up long URLs (it seems like this type of lookup is only performed while creating a new URL), how would we handle potential collisions? Since this query seems to be performed sparingly (as of now), does it justify adding a new column to speed up the lookup? Would also need to create the hash each time we create a new link?

Thank you!

**Comment by nickmoline** [comment]
I'd be happy to send a pull request with the migration and the hash handling

As for why the crc32, it would actually be used either to see if the long url has already been shortened by the same user (so it can return the same url instead of shortening again) and for doing a reverse lookup using the `/api/v2/action/lookup` endpoint for looking up a short url from the long url.  Yes the crc would have to be calculated when inserting new links, and then when you query you are querying both columns, the crc32 first, which would limit the result set down to a very small number, and the actual long url second, which would handle any collisions

```php
$hash = crc32($longUrl);
Link::where('long_url_hash', $hash)->where('long_url', $longUrl);
```

To simplify, I'd add a mutator to the model so that whenever the long_url is set, the hash is set immediately, and a scope that lets you then query with a simple `Link::longUrl($longUrl)`

```php
public function setLongUrlAttribute($longUrl)
{
  $hash = crc32($longUrl);
  $this->attributes['long_url'] = $longUrl;
  $this->attributes['long_url_hash'] = $hash;
}

public function scopeLongUrl($query, $longUrl)
{
  $hash = crc32($longUrl);
  return $query->where('long_url_hash', $hash)->where('long_url', $longUrl);
}
```

**Comment by cydrobolt** [comment]
Thanks for the examples :)
I'll wait for your PR and continue the discussion there.

**Comment by cydrobolt** [comment]
Hey there,

Are you planning on submitting a PR for this change? If not, I may be planning on implementing these changes myself in the upcoming days.
