### ISSUE TITLE
Installation PHP 7.0

### ISSUE THREAD

**Issue by sublimeload** [cydrobolt/polr#275]
Hey all! New to github and dev in general, and I think this is one of the coolest projects I have ever heard of! Can't seem to get it working though, but I am a noob. Please be gentle.

I spun up a vm lamp server, which installed php 7.0 (on Ubuntu) and I've noticed all the instructions are fairly current and up to date, but I see loads of references to php 5.x. Should I be using php 5? Also, upon installing composer, the '--no-dev' command comes back with an error stating this is an invalid argument, and a list of arguments to choose from. '-o' also apparently doesn't exist, and I cannot locate anything on google implicating that the arguments were removed and why.

running a 'git clone' in terminal, or running composer against the cloned repository left it where the git command left it, on my home directory. per reading through the lines, I moved the repository to /var/www/, but the documentation didn't specify that I should. I know I am a noob, but is that were I should have moved it to/at all?

My end game is that after moving the repository, pointing my apache config file to '/var/www/polr/public', updating php, running composer (without '--no-dev -o' cause that did nothing but tell me my syntax was bad) installing all of the prereqs, updating them, when I go to localhost in my browser, nothing displays, and I cannot find any documentation to point me in the direction to start troubleshooting this. If lots of people were able to spin up this web app, I am doing something wrong. I would humbly and respectfully like to ask for assistance.

Thank you, and have a great day!

**Comment by cydrobolt** [comment]
Hey there! 

Thanks for opening a ticket.

Here are the docs: http://docs.polr.me/en/latest/user-guide/installation/

I'm not sure if you've read the docs yet, but I'll do my best to help you out. PHP 7.0 is fine. The docs indicate that you should be running PHP >= 5.5.9, so 7.0 is okay. 

I'm not sure why `composer install --no-dev -o` is not working for you, but it should work. Omitting `--no-dev` and `-o` shouldn't make a big difference if you are running PHP 7. 

The documentation specifies that you should clone the repository in `/var/www`. Since you seem to be running Apache, you should clone the repository there and create an Apache VirtHost as specified. This should be pointed out in the docs above.

Are you trying to run the app on your own computer? What kind of VM are you using (are you using something like XAMPP)? It is on your own computer, or is it a remote server? If it is on your own computer, you may need to open certain ports in your firewall and configure your server to run correctly. 

You will also need to fix the permissions for the folder and ensure the VirtHost has the `/public` folder as the document root. See: http://docs.polr.me/en/latest/user-guide/installation/#running-polr-on

**Comment by sublimeload** [comment]
Cydrobolt!

Thank you very much for the fast reply! I firstly would like to thank you so much for creating this project for all of us to enjoy! There are so many applications for this, again, I can't thank you enough.

Thank you for clarifying the PHP question about using PHP 7 as I thought that might be the culprit. Per your question; I am running a Ubuntu 16.04 virtual machine on Virtual Box, on my personal computer. Apache is running, and the virtual host has one entry and the document root is pointed at the var/www/polr/public root, as this VM was spun up for the purpose of checking out this awesome project. when I go to local host, the browser displays nothing. there are no errors, all I see is a blank screen. composer threw errors that I was missing packages, so I installed them via terminal, and the install did complete. MySQL is running as well. 

Is it possible I missed something?

Thanks again for the reply! Please have yourself a great day!

**Comment by cydrobolt** [comment]
I see. You're getting a WSOD. Can you go to /var/www/polr and run `ls -lah`? Can you look in `/var/log/apache2` and see if there are any errors?

Could you provide the path to your VirtualHost and what lies within the VirtualHost? 

Thanks

**Comment by sublimeload** [comment]
drwxr-xr-x 14 user user 4.0K Jan  7 08:46 .
drwxr-xr-x  4 root root 4.0K Jan  7 09:35 ..
drwxr-xr-x 12 user user 4.0K Jan  7 07:41 app
-rwxr-xr-x  1 user user 1.1K Jan  7 07:41 artisan
drwxr-xr-x  2 user user 4.0K Jan  7 07:41 bootstrap
-rwxr-xr-x  1 user user  854 Jan  7 07:41 composer.json
-rwxr-xr-x  1 user user 146K Jan  7 07:41 composer.lock
-rwxr-xr-x  1 user user 1.8M Jan  7 08:24 composer.phar
drwxr-xr-x  5 user user 4.0K Jan  7 07:41 database
drwxr-xr-x  6 user user 4.0K Jan  7 07:41 docs
-rwxr-xr-x  1 user user  371 Jan  7 07:41 .env.setup
drwxr-xr-x  8 user user 4.0K Jan  7 07:41 .git
drwxr-xr-x  2 user user 4.0K Jan  7 07:41 .github
-rwxr-xr-x  1 user user   79 Jan  7 07:41 .gitignore
-rwxr-xr-x  1 user user   23 Jan  7 07:41 .jshintrc
-rwxr-xr-x  1 user user  18K Jan  7 07:41 LICENSE
-rwxr-xr-x  1 user user  549 Jan  7 07:41 mkdocs.yml
-rwxr-xr-x  1 user user 1022 Jan  7 07:41 phpunit.xml
drwxr-xr-x  6 user user 4.0K Jan  7 07:41 public
-rwxr-xr-x  1 user user 3.2K Jan  7 07:41 README.md
drwxr-xr-x  4 user user 4.0K Jan  7 07:41 resources
-rwxr-xr-x  1 user user  424 Jan  7 07:41 server.php
drwxr-xr-x  5 user user 4.0K Jan  7 07:41 storage
drwxr-xr-x  2 user user 4.0K Jan  7 07:41 tests
-rwxr-xr-x  1 user user  244 Jan  7 07:41 .travis.yml
drwxr-xr-x  2 user user 4.0K Jan  7 07:41 util
drwxrwxr-x 31 user user 4.0K Jan  7 09:30 vendor


and I see this too:
Sat Jan 07 09:47:57.265399 2017] [:error] [pid 7178] [client 127.0.0.1:36570] PHP Fatal error:  Uncaught InvalidArgumentException: Dotenv: Environment file .env not found or not readable. Create file with your environment settings at /var/www/polr/bootstrap/../.env in /var/www/polr/vendor/vlucas/phpdotenv/src/Dotenv.php:33\nStack trace:\n#0 /var/www/polr/bootstrap/app.php(5): Dotenv::load('/var/www/polr/b...')\n#1 /var/www/polr/public/index.php(14): require('/var/www/polr/b...')\n#2 {main}\n  thrown in /var/www/polr/vendor/vlucas/phpdotenv/src/Dotenv.php on line 33
[Sat Jan 07 09:48:02.124513 2017] [:error] [pid 7180] [client 127.0.0.1:36574] PHP Fatal error:  Uncaught InvalidArgumentException: Dotenv: Environment file .env not found or not readable. Create file with your environment settings at /var/www/polr/bootstrap/../.env in /var/www/polr/vendor/vlucas/phpdotenv/src/Dotenv.php:33\nStack trace:\n#0 /var/www/polr/bootstrap/app.php(5): Dotenv::load('/var/www/polr/b...')\n#1 /var/www/polr/public/index.php(14): require('/var/www/polr/b...')\n#2 {main}\n  thrown in /var/www/polr/vendor/vlucas/phpdotenv/src/Dotenv.php on line 33

**Comment by cydrobolt** [comment]
I see. I think I've found your issue. Try running these commands as `root` (`sudo su`), as described in the installation docs:

```bash
# from /var/www
# set appropriate permissions to folder
chmod -R 755 polr
# allow apache to read necessary files
chown -R www-data polr
```

Let me know if that works.

**Comment by sublimeload** [comment]
Cydrobolt, thank you for all the help, I greatly appreciate it! For some reason now, Apache will only serve up index.html from /var/www/html. I have 'service apache2 stop', and confirmed it is off, but it keeps serving up that page... I have deleted the VM in the past 2 hours, and rebuilt it, and confirmed all settings per this thread, and apache is still serving up index.html.

**Comment by sublimeload** [comment]
Virtual host looks like this in between the tags: 
	"ServerAdmin webmaster@localhost
	DocumentRoot /var/www/polr/public
	<Directory "/var/www/polr/public">
		Require all granted
		Options Indexes FollowSymLinks
		AllowOverride All
		Order allow,deny
		Allow from all
	</Directory>"

**Comment by sublimeload** [comment]
disregard. the new vm just needed reboot lol. old one was screwed up, serving up pages while the apache service was confirmed stopped. still getting a WSOD after all that :(   cydrobolt, I really appreciate your help in all of this

**Comment by cydrobolt** [comment]
What do you see in the Apache logs? Could you paste those messages here?

**Comment by sublimeload** [comment]
[Mon Jan 09 19:24:09.751464 2017] [:error] [pid 1191] [client 127.0.0.1:56456] PHP Fatal error:  Uncaught InvalidArgumentException: Dotenv: Environment file .env not found or not readable. Create file with your environment settings at /var/www/polr/bootstrap/../.env in /var/www/polr/vendor/vlucas/phpdotenv/src/Dotenv.php:33\nStack trace:\n#0 /var/www/polr/bootstrap/app.php(5): Dotenv::load('/var/www/polr/b...')\n#1 /var/www/polr/public/index.php(14): require('/var/www/polr/b...')\n#2 {main}\n  thrown in /var/www/polr/vendor/vlucas/phpdotenv/src/Dotenv.php on line 33

**Comment by cydrobolt** [comment]
Did you copy `.env.setup` to `.env` as I mentioned earlier?

**Comment by sublimeload** [comment]
I did not as I had to rebuilt the environment, but I did and its up and running! Thank you cydrobolt! You're the best!

**Comment by cydrobolt** [comment]
No problem, have fun :)
