### ISSUE TITLE
I don't have /setup URL

### ISSUE THREAD

**Issue by AntonTumasov** [cydrobolt/polr#276]
#### I guess it's connected with the fact I don't have `vendor` directory at all. 
```Warning: require_once(/var/www/polr/www/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/polr/www/bootstrap/app.php on line 2 Fatal error: require_once(): Failed opening required '/var/www/polr/www/bootstrap/../vendor/autoload.php' ``` <--- This is error I get in browser right now .
#### upd. I noticed you have /vendor in .gitignore

**Comment by cydrobolt** [comment]
You need to download the dependencies as indicated in the documentation using composer. 

Refer to the installation guide's section about composer
