### ISSUE TITLE
Getting an extra index.php added to URL when accessing the user dashboard

### ISSUE THREAD

**Issue by DeviantEng** [cydrobolt/polr#277]
Polr running http with nginx locally.  Have a separate box running nginx as a reverse proxy, also adding ssl.  All is working as expected, except when I click on `admin > dashboard`, the url returned is `https://polr.domain.com/index.php/admin?`, and I'm getting a `ERR_TOO_MANY_REDIRECTS` message.  If I remove `index.php/` from that URL, it works as expected.

```
[root@polr conf.d]# cat polr.conf
server {
  listen 80;
  server_name polr.domain.us;
  root /var/www/polr/public;
  index  index.htm index.html index.php;

  location / {
    try_files  $uri $uri/ /index.php?$query_string;
    if ($request_uri ~* "^(.*/)index\.php(/?)(.*)") {
      return 301 $1$3;
    }
  }

  if (!-d $request_filename) {
    rewrite ^/(.+)/$ /$1 permanent;
  }

  if ($request_uri ~* "\/\/") {
    rewrite ^/(.*) /$1 permanent;
  }

  location ~ \.php$ {
    try_files $uri =404;
    include /etc/nginx/fastcgi_params;

    fastcgi_index   index.php;
    fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param   HTTP_HOST       $server_name;
    fastcgi_pass    unix:/var/run/php-fpm/php-fpm.sock;
  }
}
```

Here is my reverse proxy config (only the relevant section):
```
server  {
  listen  443 ssl;
  server_name  polr.domain.us;
  ssl  on;
  location  / {
    proxy_pass  http://172.16.1.164/;
    #proxy_redirect  http://polr.domain.us https://polr.domain.us;
    proxy_set_header  Host $server_name;
    proxy_set_header  X-Forwarded-Host $host;
    proxy_set_header  X-Forwarded-Server $host;
    proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
```

No other changes have been made.  I'm running:
```
POLR_RELDATE=December 9, 2016
POLR_VERSION=2.1.1
```

Any ideas?  Thanks!

**Comment by cydrobolt** [comment]
Hey! Sorry for the slow reply. This usually happens if you don't have the path correctly rewritten.

Have you tried changing `try_files  $uri $uri/ /index.php?$query_string;` to `try_files  $uri $uri/ /index.php$is_args$query_string;`

Please reference docs.polr.me for a sample nginx configuration.

**Comment by DeviantEng** [comment]
Thanks @cydrobolt, but that actually causes more issues than anything.  The nginx config listed in the docs doesn't work for me when put behind a remote reverse proxy instance.  

This is a Laravel-based project, right?  I've had issues with another app, and the issues were very similar to this (when behind a reverse proxy).  I'm probably going to have to run apache locally and reverse proxy it that way.  Go ahead and close this, because I don't know when I'll actually get around to testing it.  I'll create a new issue if I run into trouble in the future.

**Comment by cydrobolt** [comment]
Okay. Sounds good. Polr runs on Lumen, which is similar to Laravel.
