### ISSUE TITLE
'Lookup' endpoint of API not working

### ISSUE THREAD

**Issue by michaelachmann** [cydrobolt/polr#278]
When trying to access the *lookup*-endpoint a Fatal error is returned:

`Fatal error: Class 'App\Http\Controllers\Api\Validator' not found in /var/www/polr/app/Http/Controllers/Api/ApiLinkController.php on line 46` 

The *shorten*-endpoint on the other hand is working just fine.

I am using Version 2.1.1 and just installed it.

**Comment by cydrobolt** [comment]
Thank you for pointing out this problem! It looks like it was using `Validator` from the API namespace and not from the global namespace. You can pull the repo to receive the patch.

**Comment by michaelachmann** [comment]
I'm sorry for reopening this issue, but it seems like it still wasn't working. 

Check this out: https://demo.polr.me/api/v2/action/lookup?key=f0f92036ac12d90ea49716e9a8c39e&ending=b

Error Message
> Whoops, looks like something went wrong.

**Comment by cydrobolt** [comment]
It looks like the problem should be fixed now. There was a data type mismatch in the validation of arguments. Also, your example request seems to be incorrect. The url ending should be passed as `url_ending=b`, not `ending=b` as mentioned in the API documentation.
