### ISSUE TITLE
Heroku Deployment

### ISSUE THREAD

**Issue by kevincolten** [cydrobolt/polr#280]
I just wanted to leave this here for anyone wanting to deploy to Heroku. You'll need to;

1. Make [these changes](https://github.com/cydrobolt/polr/compare/ee48d0346b01959f8fdf118e0e072b35e0b243e7...AustinCodingAcademy:heroku) (as of the time of this issue)

2. Add all these variables to your Heroku app

![screen shot 2017-01-28 at 2 06 06 pm](https://cloud.githubusercontent.com/assets/4411115/22399482/fea665b0-e562-11e6-8c3f-f12175a98574.png)
![screen shot 2017-01-28 at 2 06 24 pm](https://cloud.githubusercontent.com/assets/4411115/22399486/041053c6-e563-11e6-8ece-a6c57acce990.png)

**Comment by cydrobolt** [comment]
Thank you :)
