### ISSUE TITLE
Analytics API

### ISSUE THREAD

**Issue by michaelachmann** [cydrobolt/polr#281]
I just wanted to drop a line about a new open source project I just started: LnkShortener, an Android app for the use with Polr's API. It's source is available on [GitHub](https://github.com/michaelachmann/LnkShortener). It can easily be configured to use your own Polr Installation as long as you've got an API-Key

I know that there's plenty of other apps out there, some already supportings Polr. My goal is to incorporate the Polr Analytics System, which takes me to another question:

Are there any plans for an API for the new analytics system?

**Comment by cydrobolt** [comment]
Yep! We're hoping to release JSON data of clicks and provide filtering capabilities to find the right data for certain date ranges. 

If you could open another ticket or rename this one to "analytics API", that would be super helpful.

**Comment by michaelachmann** [comment]
Perfect, I'm quite looking forward to implementing the API.
