### ISSUE TITLE
[Question] Can this be used privately?

### ISSUE THREAD

**Issue by markaswift** [cydrobolt/polr#284]
Hello,

I'd like to use this as an alternative to YOURLS, is it possible to run this in a private mode for company internal use?

Ideally I'd like to forward to root of the shortening url to our homepage and hide the admin side somehow?

Any help is greatly appreciated. Thank you for providing such an awesome open source tool.

**Comment by cydrobolt** [comment]
Yep. This is an option in set up

**Comment by markaswift** [comment]
Thanks @cydrobolt
