### ISSUE TITLE
Change theme after install

### ISSUE THREAD

**Issue by markaswift** [cydrobolt/polr#285]
Hi,

Is there a link to the various theme files, so I can change the .env after install to try them out?

Cheers,

Mark

**Comment by cydrobolt** [comment]
Here's a good reference: https://www.bootstrapcdn.com/bootswatch/

**Comment by markaswift** [comment]
Thanks @cydrobolt, that's great.

Do you know if there's a quick and easy way to replace the default text brand in the navbar with a logo?

**Comment by cydrobolt** [comment]
You can edit the contents of the brand text in the navbar by editing the `navbar` template:

https://github.com/cydrobolt/polr/blob/master/resources/views/snippets/navbar.blade.php#L12

**Comment by markaswift** [comment]
Yeah, I've done that. Hopefully adding a logo could be an option for a future release, I'm trying not to hack your core files too much so I can still upgrade without too much pain ;)

**Comment by cydrobolt** [comment]
You should be able to remove the text field and replace it with an image. I'm fairly sure git won't have a problem with merging such an edit. 

I've seen it done before many times :)

**Comment by markaswift** [comment]
I guessed as much. Do you suggest I fork this repo, so I can customise things while maintaining the option to merge your updates as and when you make them? (off-topic I know).

**Comment by cydrobolt** [comment]
Yeah, that would be preferable. You could make a fork in your organisation and make the necessary edits. GitHub is a big help with keeping track of changes upstream.
