### ISSUE TITLE
Upgrading to Laravel 5.4?

### ISSUE THREAD

**Issue by marktopper** [cydrobolt/polr#291]
Are there any plans to upgrade to Laravel 5.4?

**Comment by cydrobolt** [comment]
Not at the moment. The version of Lumen we're using has many breaking changes with 5.4

**Comment by jeremykenedy** [comment]
@cydrobolt 

Hello, is there an interest in updating this to a current version of Laravel? 

If so, I would be up for the project of doing so. I can get it done, I am extremely experienced with Laravel. This would not be a learning experience for me to learn Laravel as I already understand it and the many opinions that have gone into it.

Let me know. I wanted to check before I just go full into it and have a PR stuck in limbo.

Thanks,

Jeremy
