### ISSUE TITLE
Installation documentation missing a step, and possible problem with passwords

### ISSUE THREAD

**Issue by cantonbecker** [cydrobolt/polr#300]
The installation page is missing an important step
http://docs.polr.me/en/latest/user-guide/installation/

Before downloading the composer package, you need to remind folks to

cd polr

If someone follows the instructions verbatim (as I did) they'll get the errror
"Composer could not find a composer.json file in /home/public_html/"
 
The other problem is a little weirder and I'm hoping someone can reproduce.

When I did my initial /setup/, I setup my admin as:
name: short
pass: $hort$tuff

After setup, I was unable to login. I looked in the MySQL database, and the admin name was 'polr', not 'short'. I tried logging in as polr/$hort$tuff, but that didn't work either.

So, I deleted everything, and re-installed, and this time accepted the username 'polr' and used a password that didn't contain dollar signs.

Anyway, I'm fairly certain I typed in everything properly, and I suspect there's a bug you can reproduce by running setup as admin name short password $hort$tuff

Thanks for this amazing software!

**Comment by cydrobolt** [comment]
I agree. I think the composer steps assume that the user is already `cd`'d into the correct directory, although an extra pointer could be useful.

In regards to the the `$hort$tuff` issue, I was unable to reproduce this error. Can you reproduce it again from scratch and provide the steps you took to create this bug?

**Comment by cantonbecker** [comment]
Regarding my problem with the password, since you tried to reproduce and couldn't, let's assume it was user error on my part. Perhaps when I copied and pasted the original password, I included a space or something.
