### ISSUE TITLE
Using Apache Environment Variables in .env

### ISSUE THREAD

**Issue by brianliyang** [cydrobolt/polr#301]
I just set up Polr on my server and everything is working great, I love it! I'm just wondering, is it possible, and if so, can I reference my Apache environment variables in my `.env` file?

I have things like my database username/password and SMTP server username/password storing in  `/etc/apache2/envvars` that usually can reference from my PHP scripts using `getevn('MY_ENV_VAR')`. I tried using `getenv('MY_ENV_VAR')` in the `.env` file to replace my usernames/passwords but it doesn't seem to work.

Is this functionality supported or do I need to use a different command/notation?

Thanks for this awesome open-source app!

**Comment by cydrobolt** [comment]
Could you change the name of the Apache environmental variable to "DB_PASSWORD" (or whichever variable you're trying to set) and remove the line in `.env` that sets the variable? That should allow Polr to use the variable directly.

**Comment by brianliyang** [comment]
Ah yes I can do that. Ok that does work, I'll just remake Apache environment variables with the names in the `.env` file. Thanks!
