### ISSUE TITLE
Consider moving /about to /about-polr

### ISSUE THREAD

**Issue by cydrobolt** [cydrobolt/polr#304]
Moving the Polr about page to `/about-polr` or something similar might be beneficial. Organisations may want to make use of `/about` to redirect to their own about page. However, this is currently not possible because the Polr about page at `/about` occupies the path.

**Comment by kbabioch** [comment]
I want to backup this request. `/about` is definitely something you want to use for branding, so occupying it with mostly _useless_ information (from the user's point of view), does not make to much sense.
