### ISSUE TITLE
Base table or view not found

### ISSUE THREAD

**Issue by DeJayDevelopment** [cydrobolt/polr#305]
## Expected Behavior

Expecting a smooth installation without Database errors and tables not creating.

## Current Behavior

Attempting to initial setup a polr installation, trying to navigate to /setup directory (with proper .env setup and debug mode toggled).
[Image](http://i.imgur.com/Xu4hCPy.png)

## Possible Solution
//

## Steps to Reproduce (for bugs)

//

## Context
The entire .env file (copied via cp resources/views/env.blade.php .env) has been edited to proper settings, nothing has been left untouched (excluding the "Do not touch" section)

## Your Environment

* Version or latest commit hash (`git rev-parse HEAD`):
* Environment name and version (e.g. Chrome 39, PHP 7.0, etc):
* Instance link (optional):

**Comment by DeJayDevelopment** [comment]
Note:

I've just ran:
`php artisan migrate`

To be faced with this error:
NotFoundHttpException in Application.php line 425:

**Comment by DeJayDevelopment** [comment]
🤦

After migrating with artisan, the issue was solved.

**Comment by cydrobolt** [comment]
Oh, that's good. I was going to mention that you should be copying `.env.setup` to `.env` rather than copying the `.env.blade.php` file to `.env` because `.env.setup` is the configuration that enables you to use the setup script.
