### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by gurgeng** [cydrobolt/polr#315]
Hello Polr Community,

I am working on changing the registration form to limit people signing up to a specific email domain. For example, users can only register if they have access to a person@example.com, only emails ending with "@example.com" can register otherwise it will throw up an error.

**Comment by cydrobolt** [comment]
Hey there!

This should be rather easy. You can implement a new configuration option for the required domain name, then add the validation logic in `UserController`

You can use various parsing functions to parse out the domain name from the email address, then verify the domain name against the configured domain.

Let me know if you need any pointers.

**Comment by gurgeng** [comment]
I would love if you could maybe walk me through this implementation. Although it may be easy for most, I am in my early stages of learning, and still am not necessarily familiar with parsing out the domain name.

I actually think this would be a great implantation option in the admin setting to be able to set the email required.

I really appreciate your quick response

**Comment by cydrobolt** [comment]
For sure! Here's a helpful function you could use to extract the domain name from the username:

```php
$parts = explode("@", "johndoe@domain.com");
$username = $parts[0];
```
(copied from http://stackoverflow.com/questions/1798368/using-regex-to-get-extract-username-from-email-address)

In order to add a new option to the setup, you'll need to first add a new configuration option to `.env.blade.php` in the templates folder. You should be able to use the other options as a rough template to write your new configuration option.

You'll need to add a new input and select field to determine whether the user wishes to enable the option, and if so, what domain should be required to register. Again, you can look at the other options to see how the variables and logic should be laid out. Here's a helpful commit that does something of a similar nature: https://github.com/cydrobolt/polr/commit/ab9546578678b2876b40b55700c30ed598d69ca0

To access your variable, you can use the `env('CONFIG_VAR_NAME')` helper function. You should always default to "disabled," however. i.e, if `env('CONFIG_VAR_NAME')` is empty, the feature should be disabled.

Registration logic can be found in `UserController`

Feel free to try it out and submit a PR. I can review it and provide you some helpful tips and comments :smile:

**Comment by gurgeng** [comment]
Awesome! Thank you for all of your advice, I will get started working on this now!

**Comment by gurgeng** [comment]
So I added the configuration settings:
`# Set to true to allow all emails to register
# If flase, set the SETTING_EMAIL_ACTIVATION
SETTING_SPECIFY_EMAIL={{$ST_SPECIFY_EMAIL}}

# You must set SETTING_EMAIL_ACTIVATION if SETTING_SPECIFY_EMAIL is false
# Polr will require emails to be registered with the specified domain.
SETTING_EMAIL_ACTIVATION={{$ST_EMAIL_ACTIVATION}}`

I am now adding the following in admin.blade.php
`            <div role="tabpanel" class="tab-pane" id="settings">
                <h3>Change Password</h3>
                <form action='/admin/action/change_password' method='POST'>
                    Old Password: <input class="form-control password-box" type='password' name='current_password' />
                    New Password: <input class="form-control password-box" type='password' name='new_password' />
                    <input type="hidden" name='_token' value='{{csrf_token()}}' />
                    <input type='submit' class='btn btn-success change-password-btn'/>
                </form>

                @if ($role == $admin_role)
                <h3>Specify Email</h3>
                <form action='/admin/action/' method='POST'>
                    Limit to Specific Emails: <select class="form-control" id="specify_email" name="specify_email"><option>yes</option><option>no</option></select>
                    <input type='submit' class='btn btn-success'/>
                </form>
            </div>`

I'm trying to figure out how to make the second input show up if option is yes, any advice?

**Comment by cydrobolt** [comment]
You should add the option in `setup.blade.php`, not the admin panel. All options except user options should be placed in the setup script and saved in the env file. You might also want to enable the feature only if the option is true, not false. Otherwise, there will be problems with backwards compatibility.

**Comment by gurgeng** [comment]
I have made the following changes to the env.blade.php

` # Set to false to allow all emails to register
# If true, set the SETTING_EMAIL_ACTIVATION
SETTING_SPECIFY_EMAIL={{$ST_SPECIFY_EMAIL}}

# You must set SETTING_EMAIL_ACTIVATION if SETTING_SPECIFY_EMAIL is true
# Polr will require emails to be registered with the specified domain.
SETTING_EMAIL_ACTIVATION={{$ST_EMAIL_ACTIVATION}}`

and I also add this to setup.blade.php as you suggested:
`            <p>
                Specify Email Domain:
                <button data-content="Specifying the email will allow you to limit who is able to register." type="button" class="btn btn-xs btn-default setup-qmark" data-toggle="popover">?</button>
            </p>
            <select name='setting:specify_email' class='form-control'>
                <option value='false'>Specify email disabled</option>
                <option value='true'>Specify email enabled</option>
            </select>
            <p class='text-muted'>
                Please ensure if you choose to limit to a specific email domain that the domain is properly setup.
            </p>`

How do I make sure this:
`'setting:specify_email'`

returns the value to what I have in my env.blade.php? what are my next steps at this point?

**Comment by cydrobolt** [comment]
You'll need to create a variable for `setting:specify_email` here: https://github.com/cydrobolt/polr/blob/master/app/Http/Controllers/SetupController.php#L120

You'll also need to pass that setting to the env template here:
https://github.com/cydrobolt/polr/blob/master/app/Http/Controllers/SetupController.php#L157

To save the specified domain to the env as well, you should create another text input field where users can specify the domain they would like to restrict registration to. It should be similar to the `<select>` toggle you've already implemented. Similarly, the text field would also need to be linked with the `setting:xxxxx` strings as you did with the select field :)

**Comment by gurgeng** [comment]
Is there a way to make the text input field disabled if they select false?

**Comment by cydrobolt** [comment]
There is, but we haven't implemented that for most other fields yet. We should definitely implement that interactivity in the setup page soon. 

You could do it easily using `ng-model` on the select field and `ng-disabled` on the input field, but we haven't created an Angular controller for the setup script yet. Once that's in place, we could strategically disable the input as needed :)

**Comment by gurgeng** [comment]
This is what I have added as my input:

```
  <p>
                Email Domain:
                <button data-content="Enter the domain of the emails you'd like to be able to register." type="button" class="btn btn-xs btn-default setup-qmark" data-toggle="popover">?</button>
            </p>
            <input type='text' class='form-control' name='app:email_activation' placeholder='gmail.com'>
```

I want to confirm if I should be using:
`app:email_activation ` or `setting:email_activation `
Im not sure what the proper naming convention/scheme looks like

**Comment by cydrobolt** [comment]
I think using `setting:` is more appropriate in this case. You might want to try something like `setting:allowed_email_domains` instead of `email_activation`, though, as it might be confused with the email activation settings.

**Comment by gurgeng** [comment]
Awesome I have implemented those changes, now the only thing Im left unsure is how to display the different registration page if you choose to require a specific email domain.

I know I would be changing the signup.blade.php, I'm just not sure how

**Comment by cydrobolt** [comment]
No problem! I'm happy to help.

Somewhere around here (https://github.com/cydrobolt/polr/blob/master/app/Http/Controllers/UserController.php#L69) you should place the check for the domain.

You could do something like this:

```php
$email_domain = explode("@", $email)[1];
if (env('ST_RESTRICT_EMAIL_DOMAIN')) {
    if ($email_domain != env('ST_RESTRICT_EMAIL_DOMAIN_NAME')) {
        // ... throw an error
    }
}
```

**Comment by gurgeng** [comment]
So this is what I have added as the error:
```
        $email_domain = explode("@", $email)[1];
        
        if (env('ST_RESTRICT_EMAIL_DOMAIN')) {
            if ($email_domain != env('ST_RESTRICT_EMAIL_DOMAIN_NAME')) {
                // ... throw an error
                return redirect(route('signup'))->with('error', 'Sorry, your email domain is not allowed to register. Try again.');
            }
            else {
                 $response = redirect(route('login'))->with('success', 'Thanks for signing up! Please confirm your email to continue.');
             }
        }
```

What exactly is the function looking for? I just want to confirm that it would be looking to take:
`test@example.com` and email_domain would be `example.com` or would it be `example`

And I just want to confirm this is the last part of the making of this correct? Im not sure what else would need to be done next.

My final question is, how can I make these updates to my existing site that is up/running?

**Comment by cydrobolt** [comment]
`$email_domain` would be `example.com`

In your nested if statement, you could leave out the else clause. The `$response` is set farther down the chain, so it's unnecessary to define a `$response` there. 

To apply those updates to your existing site, you could manually insert the new configuration options into your `.env` file and merge your updates, although it would be better if you could make a PR to this repo and pull from upstream once I merge this feature.

If you make a pull request, I can squash any bugs and polish some things to make sure nothing breaks :)
You can then merge it directly from upstream.

**Comment by gurgeng** [comment]
Awesome of I have made the final changes:

```
        $email_domain = explode("@", $email)[1];
        
        if (env('ST_RESTRICT_EMAIL_DOMAIN')) {
            if ($email_domain != env('ST_RESTRICT_EMAIL_DOMAIN_NAME')) {
                // ... throw an error
                return redirect(route('signup'))->with('error', 'Sorry, your email domain is not allowed to register. Try again.');
            }
        }
```

I will make the pull request now

**Comment by cydrobolt** [comment]
Looks good! Definitely make the PR so that I can make line comments :)

**Comment by gurgeng** [comment]
Awesome I've created the pull request (I hope I did it right first time doing it)

Once/if everything gets committed, you will have to let me know how to merge it

**Comment by gurgeng** [comment]
Im not sure if I should close this or if you will instruct me on how to update my site through this as well
