### ISSUE TITLE
GeoIP

### ISSUE THREAD

**Issue by gurgeng** [cydrobolt/polr#318]
Hello again,

I have been looking through the various helpers and am trying to understand how I would go about setting up an additional table in the link_stats.blade.php that would display where the clicks IP are from, and the day/time the clicked from that IP.

I see that there is a reference in the `getCountry` function:
`$country_iso = geoip()->getLocation($ip)`
I just can't figure out how to display this data along with the date/time of the click.

**Comment by cydrobolt** [comment]
What do you mean? Where do you want this table? The process would be rather lengthy. I doubt I could walk you through the entire process in a GitHub issue. 

Are you familiar with Laravel and SQL?

**Comment by overint** [comment]
Hey @gurgeng 
Can you clarify your issue?
