### ISSUE TITLE
Translation 

### ISSUE THREAD

**Issue by eallion** [cydrobolt/polr#319]
I built a new site
But users do not understand English
So I translated these files one by one
Hope you can provide some better way of translation
My English is also very poor, but I can help you translate it into Chinese
Google is amazing

https://github.com/eallion/polr/commit/79424dcc7d54f47ac8bfbc6ec99cd0789e000d95

https://tk.ci

**Comment by cydrobolt** [comment]
Thank you! We intend to implement localization with Laravel's built-in localization system in the future. Although that won't cover all strings, it should be helpful :)

**Comment by SSMIN** [comment]
That's good idea!
If localization is possible, I want contribute to Korean translation.
polr is very great project and I want to help you :)

**Comment by srishag** [comment]
I can help with Hindi translation!

**Comment by klezm** [comment]
are you using any efficient method for translating yet?
https://transifex.com is free for open source projects and makes it very easy to keep the translations up to date.
I could help setting up an account for the project.
