### ISSUE TITLE
Angularjs Uncaught Error

### ISSUE THREAD

**Issue by joglomedia** [cydrobolt/polr#325]
Hello, installing Polr 2.1.1 and getting this error, so the menu link is not working

> Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=polr&p1=Error%3A%20…%20%20%20at%20Bc%20(http%3A%2F%2Fpolr.dev%2Fjs%2Fangular.min.js%3A21%3A179)
>     at angular.min.js:6
>     at angular.min.js:40
>     at q (angular.min.js:7)
>     at g (angular.min.js:39)
>     at cb (angular.min.js:43)
>     at c (angular.min.js:20)
>     at Bc (angular.min.js:21)
>     at fe (angular.min.js:20)
>     at HTMLDocument.<anonymous> (angular.min.js:317)
>     at j (jquery-1.11.3.min.js:2)

How to solve this?

**Comment by cydrobolt** [comment]
What page does this occur on? Can you provide steps to reproduce this error?

**Comment by joglomedia** [comment]
this occur on home and admin page
i use

git clone https://github.com/cydrobolt/polr.git localhost/path/
composer install
composer update

**Comment by cydrobolt** [comment]
What browser and OS are you running?

**Comment by joglomedia** [comment]
Chrome 57 on LinuxMint 13
___

Sorry, This issue has been solved, after I upgrade my OS to LinuxMint 18, I don't know why

**Comment by cydrobolt** [comment]
That's weird. Maybe some browser glitch. 

I'm glad you got it fixed :)
