### ISSUE TITLE
Missing autoload.php file

### ISSUE THREAD

**Issue by MarioColuzzi** [cydrobolt/polr#328]
A whole directory is missing, file specified in /../bootstrap/app.php cannot be found in the bundle

require_once __DIR__.'/../vendor/autoload.php';

**Comment by cydrobolt** [comment]
You must install the composer dependencies using `composer install --no-dev -o`

**Comment by MarioColuzzi** [comment]
Thank you for the quick reply . . . over complex install, either it works or not.

I'll find another project that will do the same.

**Comment by cydrobolt** [comment]
Up to you.
