### ISSUE TITLE
Polr installation issue !

### ISSUE THREAD

**Issue by saivasanth** [cydrobolt/polr#329]
while  installation we are facing isuue 
NotFoundHttpException in /var/www/html/polr/vendor/laravel/lumen-framework/src/Application.php line 1256:

**Comment by cydrobolt** [comment]
#328

**Comment by saivasanth** [comment]
yes i have installed 
curl -sS https://getcomposer.org/installer | php
php composer.phar install --no-dev -o

when i hit polr/public/setup  after fill the form when i click install its shows 404 error

**Comment by cydrobolt** [comment]
You should be going to yourdomain.com/setup. What domain have you installed Polr in? What's the folder structure like?

**Comment by cydrobolt** [comment]
What page so you get the 404 on? (entire URL)

**Comment by saivasanth** [comment]
hi when hit -->  http://ebasta.chennai.cdac.in/polr/setup --> 404 error
for --> http://ebasta.chennai.cdac.in/polr/public/setup --> its show the config form but after i click the install its redirdct to  http://ebasta.chennai.cdac.in/setup and shows 404 error

**Comment by cydrobolt** [comment]
Did you set your document root to `/var/www/html/polr/public`? 

Your document root must be set to polr/public. It currently seems like your document root is set to `/var/www/html`. Follow the directions in the documentation in regards to editing your VirtualHost entry for Apache.

**Comment by saivasanth** [comment]
hi i have created polr.conf at/etc/apache2/sites-enabled and blow is my config details
<VirtualHost *:80>
    ServerName polr
    ServerAlias polr

    DocumentRoot "/var/www/html/polr/public"
    <Directory "/var/www/html/polr/public">
        Require all granted
        Options Indexes FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>

**Comment by cydrobolt** [comment]
ServerName and ServerAlias should be your site's external address (e.g ebasta.chennai.cdac.in). You should probably also disable your original VirtHost (the one that had its DocumentRoot at /var/www/html)

Is your new VirtHost working?

**Comment by saivasanth** [comment]
hi ,
MY env setup :
 OS           :  Debian 3.16.7-2
Apache 2   : Apache/2.4.10  Debian
 PHP          : PHP 5.6.29-0+deb8u1 (cli) (built : Dec 14 2016 13:13:28)
mysq         l : version: 5.5.43-0+deb8u1


Based on your suggestion  i have changed my  polr.conf at/etc/apache2/sites-enabled and below is my config details

<VirtualHost *:80>
    ServerName ebasta.chennai.cdac.in
    ServerAlias ebasta.chennai.cdac.in

    DocumentRoot "/var/www/html/polr/public"
    <Directory "/var/www/html/polr/public">
        Require all granted
        Options Indexes FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>

1. when i hit --> http://ebasta.chennai.cdac.in/polr/public/setup

Error : NotFoundHttpException in /var/www/html/polr/vendor/laravel/lumen-framework/src/Application.php line 1256:

2. when i hit http://ebasta.chennai.cdac.in/polr/setup
error : NotFoundHttpException in /var/www/html/polr/vendor/laravel/lumen-framework/src/Application.php line 425:

**Comment by cydrobolt** [comment]
Have you tried http://ebasta.chennai.cdac.in/setup?

**Comment by saivasanth** [comment]
yes ! finally solved the issue with file permission in polar/storage and bootstrap.
Now i installed the polr in my server its working fine.BUT

i don't have the secret link creation  option ? i have only custom link option.

How to enable secret link creation option ?

**Comment by cydrobolt** [comment]
You can enable pseudorandom endings for random endings.

**Comment by cydrobolt** [comment]
Set `SETTING_PSEUDORANDOM_ENDING=true` in your `.env` file.

**Comment by saivasanth** [comment]
HI thanks for your reply. 

is it possible to create polr short url with expiry date ?
 
or url will expair after first click ?

it will we great help for us if we enable this features.

**Comment by cydrobolt** [comment]
No, it's currently not possible. I believe there's already a ticket open about this.

**Comment by saivasanth** [comment]
is there any possibility in upcoming versions ?

**Comment by cydrobolt** [comment]
We're working on it, no ETA

**Comment by saivasanth** [comment]
hi,
I want to use this service where expected hits per day may go up to 1Lakh per day. Can our service withstand this many hits.
We have the following queries regarding this. 
1. which database would you suggest best suite for this scenario.
2. We have a requirement where in there is no expiry of shortened url.
3. How can we manage this situation.
4. which framework have you used to develop the tool.
5. currently the length of the shortened url is 5. how to increase the length of shortened url.

**Comment by cydrobolt** [comment]
1. MySQL would work fine.
2. The URLs won't expire on their own unless you delete them.
3. 100k requests per day isn't an extremely high load. Everything should work fine. I would suggest turning off advanced analytics (`SETTING_ADV_ANALYTICS=false`) to reduce load on your database.
4. We've used Lumen, a lighter version of Laravel.
5. Edit your `.env` file and set `_PSEUDO_RANDOM_KEY_LENGTH` to the length you would like.

In regards to performance, we're looking into merging a lot of performance fixes in the near future. We're focusing on reducing bottlenecks, implementing a task queue for analytics and caching all link requests hitting the main application. We're looking into incorporating `redis` for queuing and caching, which would be helpful for performance. 

You should also make sure to properly configure your Apache/nginx server to best handle the load. Unless you're hitting much higher loads, you shouldn't need a load balancer or anything of that sort. Make sure your server has enough resources (e.g CPU, RAM) to serve the requests.

**Comment by saivasanth** [comment]
hi ! how to change my polr  mysql database to PostgreSQL  
there is no option to select while first setup , by default its using mysql port 3306 . 

when i try to change in .env file
DB_CONNECTION=pgsql
DB_HOST=localhost
DB_DATABASE=DB_NAME
DB_USERNAME=USER
DB_PASSWORD=P
 its show somithing went wrong error. kindly help us to  change or setup polr in PostgreSQL
