### ISSUE TITLE
Missing Analytics Link 

### ISSUE THREAD

**Issue by DigitalBoffin** [cydrobolt/polr#330]
## Expected Behavior

When in Dashboard --> Links, there is supposed to be an analytics link on each of the entries.  When clicked, it will take you to detailed analytics info for the shotened link.  See demo site for example of behavior.

## Current Behavior

No link is available.  Also, searched for `geoip.php` in my installation, it doesn't exist.

## Possible Solution

Did some files get neglected on the 2.1.1 release?

## Steps to Reproduce (for bugs)

1.  Installed via composer
2.  Site functioning
3.  Created several entries.  Verified that they worked
4.  Went into Dashboard (logged in), Selected "Links"  List of links comes up, but missing the analytics button

## Context

Missing functionality.

## Your Environment

* Version 2.1.1 installed via composer
* Environment:   Server:  FreeBSD 10.3, Apache 2.4.25, PHP 7.0.18  MySQL 5.7.17 
Client:  Windows 10, Browsers:  Chrome 58, Edge 38, IE 11
<img width="135" alt="capture" src="https://cloud.githubusercontent.com/assets/28231900/25567493/00c9ddf2-2dbd-11e7-8281-d31f8d48cf86.PNG">

**Comment by cydrobolt** [comment]
Can you please provide the latest commit hash of the version you're running?

**Comment by DigitalBoffin** [comment]
I didn’t install via GIT.  How would I get you that info?

**Comment by cydrobolt** [comment]
Oh. How did you download the files? Did you download a release? The advanced analytics feature isn't available in the 2.1.1 release. We're still ironing things out before preparing a release. 

You can get the feature by cloning `master` or downloading a copy of `master` from the GitHub repo. You'll then need to follow all the upgrade procedures shown in the "Upgrading" section of the documentation. It's very important that you follow the upgrade procedures. 

You can then edit your `.env` folder to set `SETTING_ADV_ANALYTICS=true` to enable the feature.

**Comment by DigitalBoffin** [comment]
Ok.  Thanks for the clarification.  I wasn't aware that the analytics wasn't included yet.  I will give the `master` branch a shot.

**Comment by cydrobolt** [comment]
No problem, let me know how it goes.

**Comment by DigitalBoffin** [comment]
Got it all up and running.  I had some dependencies to install, but otherwise, no biggie.  Thanks.  One thing that I did notice with this branch is that I have to have full rwx permissions (`chmod -R /www/polr`) on the entire "site" for it to function.  Is this expected?

**Comment by cydrobolt** [comment]
Did you read what the docs said about permissions?

**Comment by DigitalBoffin** [comment]
The only thing I saw in the docs about permissions was setting it to 755 ([Downloading Source Code](https://docs.polr.me/en/latest/user-guide/installation/#downloading-the-source-code))

Is there another location that addresses permissions?

**Comment by cydrobolt** [comment]
You should also `chown` the folder to the user that Apache/nginx is running under, because Polr needs to write to `storage` and to `.env`

**Comment by DigitalBoffin** [comment]
Ok. 

For FreeBSD, that would be `sudo chown -R www:www <polr install dir>`

Out of curiosity, are those those the only two items that need to have write permissions?  I would like to remove the write permissions from any directory that doesn't need it.

**Comment by cydrobolt** [comment]
Yep, those two items should be the only ones that require write permission by the web server.

**Comment by DigitalBoffin** [comment]
Ok great...if you like, I can write up some documentation for FreeBSD

**Comment by cydrobolt** [comment]
Feel free to open a PR!
