### ISSUE TITLE
TokenMismatchException in VerifyCsrfToken.php line 46

### ISSUE THREAD

**Issue by ezbakeapps** [cydrobolt/polr#332]
After completing the setup form, I get the "Whoops! Something went wrong" screen with the leading title as in the subject above.

## Expected Behavior
I was expecting to be taken to my Polr home page. 

It appears to be an issue with Laravel - which I am totally unfamiliar with. I have been through the documentation and reset permissions, etc. I just really don't know where to start for troubleshooting.

I have installed and uninstalled on multiple servers - both public (Dreamhost VPS) and private (LAMP) and get the same issue in all instances. 

You can currently find it at http://vea.link.

Here is the entire error message. Anny assistance would be greatly appreciated!

TokenMismatchException in VerifyCsrfToken.php line 46:
in VerifyCsrfToken.php line 46
at VerifyCsrfToken->handle(object(Request), object(Closure)) in VerifyCsrfToken.php line 20
at VerifyCsrfToken->handle(object(Request), object(Closure))
at call_user_func_array(array(object(VerifyCsrfToken), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))
at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in StartSession.php line 62
at StartSession->handle(object(Request), object(Closure))
at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))
at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
at Pipeline->then(object(Closure)) in Application.php line 1451
at Application->sendThroughPipeline(array('Illuminate\Cookie\Middleware\EncryptCookies', 'Illuminate\Session\Middleware\StartSession', 'Illuminate\View\Middleware\ShareErrorsFromSession', 'App\Http\Middleware\VerifyCsrfToken'), object(Closure)) in Application.php line 1221
at Application->dispatch(null) in Application.php line 1161
at Application->run() in index.php line 28

**Comment by cydrobolt** [comment]
Can you share your current `.env` file?

**Comment by ezbakeapps** [comment]
I'm pretty sure it never gets that far as the env file contents are all defaults. Permissions are 755
APP_ENV=local
APP_DEBUG=true
APP_KEY=,faO^ofvGeJ8|Z.q{mWp=^i}Cmzj+k&K

APP_LOCALE=en
APP_FALLBACK_LOCALE=en

# DB_CONNECTION=mysql
# DB_HOST=localhost
# DB_PORT=3306
# DB_DATABASE=homestead
# DB_USERNAME=homestead
# DB_PASSWORD=secret

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=file

VERSION=2.1.1
VERSION_RELMONTH=December
VERSION_RELDAY=9
VERSION_RELYEAR=2016

**Comment by cydrobolt** [comment]
Does your `storage` folder within your Polr folder have proper permissions? Does the Apache/PHP-FPM server have write permissions on the folder? You should get permissions recursively on the folder. 

Can you do `ls -lah` on your Polr folder and inside your storage folder?

**Comment by ezbakeapps** [comment]
I believe the permission are correct - here is the polr folder:
total 240K
drwxr-xr-x 13 veanea pg5030192 4.0K Mar  9 09:05 .
drwx--x--- 14 veanea adm       4.0K Mar  9 07:38 ..
-rwxr-xr-x  1 veanea pg5030192  371 Mar  9 09:05 .env
-rw-r--r--  1 veanea pg5030192  371 Mar  8 09:01 .env.setup
drwxr-xr-x  2 veanea pg5030192   64 Mar  8 09:01 .github
-rw-r--r--  1 veanea pg5030192   79 Mar  8 09:01 .gitignore
-rw-r--r--  1 veanea pg5030192   23 Mar  8 09:01 .jshintrc
-rw-r--r--  1 veanea pg5030192  244 Mar  8 09:01 .travis.yml
-rw-r--r--  1 veanea pg5030192  18K Mar  8 09:01 LICENSE
-rw-r--r--  1 veanea pg5030192 3.1K Mar  8 09:01 README.md
drwxr-xr-x 12 veanea pg5030192 4.0K Mar  8 09:01 app
-rw-r--r--  1 veanea pg5030192 1.1K Mar  8 09:01 artisan
drwxr-xr-x  2 veanea pg5030192   28 Mar  8 09:01 bootstrap
-rw-r--r--  1 veanea pg5030192  854 Mar  8 09:01 composer.json
-rw-r--r--  1 veanea pg5030192 152K Mar  9 07:41 composer.lock
drwxr-xr-x  5 veanea pg5030192   67 Mar  8 09:01 database
drwxr-xr-x  6 veanea pg5030192  125 Mar  8 09:01 docs
-rw-r--r--  1 veanea adm          0 Mar  8 08:52 favicon.gif
-rw-r--r--  1 veanea adm          0 Mar  8 08:52 favicon.ico
-rw-r--r--  1 veanea pg5030192  549 Mar  8 09:01 mkdocs.yml
-rw-r--r--  1 veanea pg5030192 1022 Mar  8 09:01 phpunit.xml
drwxr-xr-x  6 veanea pg5030192 4.0K Mar  9 07:00 public
drwxr-xr-x  4 veanea pg5030192   41 Mar  8 09:01 resources
-rw-r--r--  1 veanea pg5030192  424 Mar  8 09:01 server.php
drwxr-xr-x  5 veanea pg5030192   59 Mar  8 09:01 storage
drwxr-xr-x  2 veanea pg5030192 4.0K Mar  8 09:01 tests
drwxr-xr-x  2 veanea pg5030192   62 Mar  8 09:01 util
drwxrwxr-x 30 veanea pg5030192 4.0K Mar  9 07:41 vendor

#And the Storage Folder
total 4.0K
drwxr-xr-x  5 veanea pg5030192   59 Mar  8 09:01 .
drwxr-xr-x 13 veanea pg5030192 4.0K Mar  9 09:05 ..
drwxr-xr-x  2 veanea pg5030192   31 Mar  8 09:01 app
drwxr-xr-x  5 veanea pg5030192   61 Mar  8 09:01 framework
drwxr-xr-x  2 veanea pg5030192   51 Mar  9 08:52 logs

**Comment by cydrobolt** [comment]
Is `veanea` the user Apache is running under? Can you make sure?

**Comment by cydrobolt** [comment]
Can you try editing your `.env` file and setting `SESSION_STORE=cookie` and seeing if you can submit the form correctly?

**Comment by ezbakeapps** [comment]
I verified that Apache is running under veanea. Also, setting the SESSION_DRIVER to cookie had no effect. Same error.  When I search for "TokenMismatchException in VerifyCsrfToken.php line 46" , do see some "solutions" but I have no idea if they pertain or where to implement them.  

https://laravel.io/forum/11-14-2014-laravel-5-cant-post, 
https://teamtreehouse.com/community/laravel-5-tokenmismatchexception-in-verifycsrftokenphp-line-46

**Comment by ezbakeapps** [comment]
So I rebuilt a local LAMP server and installed the latest version of Polr from scratch and was able to get it to function - no clue what was different. So I created a new folder on my host and pointed vea.link there and reinstalled Polr from scratch there - but I still get the same error. Must be something with my host? Installing composer on my host seems to go fine, there is just one warning about json already being installed... curl -sS https://getcomposer.org/installer | php
PHP Warning:  Module 'json' already loaded in Unknown on line 0
All settings correct for using Composer
Downloading...

Composer (version 1.4.1) successfully installed to: /home/veanea/vea.link2/compo                                                    ser.phar
Use it: php composer.phar

[ps563479]$ php composer.phar install --no-dev -o
**PHP Warning:  Module 'json' already loaded in Unknown on line 0**
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 68 installs, 0 updates, 0 removals
  - Installing danielstjules/stringy (1.10.0): Loading from cache
  - Installing doctrine/lexer (v1.0.1): Downloading (100%)
  - Installing doctrine/annotations (v1.3.1): Downloading (100%)
  - Installing doctrine/cache (v1.6.1): Downloading (100%)
  - Installing doctrine/collections (v1.4.0): Downloading (100%)
  - Installing doctrine/inflector (v1.1.0): Loading from cache
  - Installing doctrine/common (v2.7.2): Downloading (100%)
  - Installing doctrine/dbal (v2.5.11): Downloading (100%)
  - Installing composer/ca-bundle (1.0.6): Downloading (100%)
  - Installing maxmind/web-service-common (v0.3.1): Downloading (100%)
  - Installing maxmind-db/reader (v1.1.2): Downloading (100%)
  - Installing geoip2/geoip2 (v2.4.4): Downloading (100%)
  - Installing swiftmailer/swiftmailer (v5.4.1): Downloading (100%)
  - Installing psr/log (1.0.0): Downloading (100%)
  - Installing illuminate/contracts (v5.1.28): Downloading (100%)
  - Installing illuminate/support (v5.1.28): Downloading (100%)
  - Installing illuminate/container (v5.1.28): Downloading (100%)
  - Installing illuminate/mail (v5.1.31): Downloading (100%)
  - Installing symfony/routing (v2.7.18): Downloading (100%)
  - Installing symfony/http-foundation (v2.7.9): Downloading (100%)
  - Installing symfony/event-dispatcher (v2.8.2): Downloading (100%)
  - Installing symfony/debug (v2.8.2): Downloading (100%)
  - Installing symfony/http-kernel (v2.7.9): Downloading (100%)
  - Installing symfony/finder (v2.7.9): Downloading (100%)
  - Installing symfony/translation (v2.7.9): Downloading (100%)
  - Installing nesbot/carbon (1.22.1): Loading from cache
  - Installing illuminate/session (v5.1.28): Downloading (100%)
  - Installing illuminate/pipeline (v5.1.28): Downloading (100%)
  - Installing illuminate/http (v5.1.28): Downloading (100%)
  - Installing illuminate/routing (v5.1.41): Loading from cache
  - Installing symfony/var-dumper (v2.7.9): Downloading (100%)
  - Installing paragonie/random_compat (v1.4.1): Loading from cache
  - Installing symfony/security-core (v2.7.9): Downloading (100%)
  - Installing symfony/dom-crawler (v2.7.9): Downloading (100%)
  - Installing nikic/fast-route (v0.4.0): Downloading (100%)
  - Installing mtdowling/cron-expression (v1.1.0): Downloading (100%)
  - Installing monolog/monolog (1.17.2): Downloading (100%)
  - Installing illuminate/filesystem (v5.1.28): Downloading (100%)
  - Installing illuminate/events (v5.1.28): Downloading (100%)
  - Installing illuminate/view (v5.1.28): Downloading (100%)
  - Installing illuminate/validation (v5.1.28): Downloading (100%)
  - Installing illuminate/translation (v5.1.28): Downloading (100%)
  - Installing symfony/process (v2.7.9): Downloading (100%)
  - Installing symfony/console (v2.7.9): Downloading (100%)
  - Installing illuminate/console (v5.1.28): Downloading (100%)
  - Installing illuminate/queue (v5.1.28): Downloading (100%)
  - Installing illuminate/pagination (v5.1.28): Downloading (100%)
  - Installing illuminate/hashing (v5.1.28): Downloading (100%)
  - Installing illuminate/encryption (v5.1.28): Downloading (100%)
  - Installing illuminate/database (v5.1.28): Downloading (100%)
  - Installing illuminate/cookie (v5.1.28): Downloading (100%)
  - Installing illuminate/config (v5.1.28): Downloading (100%)
  - Installing illuminate/cache (v5.1.28): Downloading (100%)
  - Installing illuminate/bus (v5.1.28): Downloading (100%)
  - Installing illuminate/broadcasting (v5.1.28): Downloading (100%)
  - Installing illuminate/auth (v5.1.28): Downloading (100%)
  - Installing laravel/lumen-framework (v5.1.6): Downloading (100%)
  - Installing phenx/php-font-lib (0.2.2): Downloading (100%)
  - Installing phpoffice/phpexcel (1.8.1): Loading from cache
  - Installing symfony/css-selector (v3.0.2): Downloading (100%)
  - Installing tijsverkoyen/css-to-inline-styles (1.5.5): Downloading (100%)                                                          - Installing torann/geoip (1.0.2): Downloading (100%)
  - Installing vlucas/phpdotenv (v1.1.1): Loading from cache
  - Installing maatwebsite/excel (2.1.6): Downloading (100%)
  - Installing league/fractal (0.14.0): Downloading (100%)
  - Installing laravelcollective/html (v5.1.9): Loading from cache
  - Installing dompdf/dompdf (v0.6.2): Downloading (100%)
  - Installing yajra/laravel-datatables-oracle (v6.17.0): Downloading (100%)                                                        Generating optimized autoload files

**Comment by cydrobolt** [comment]
That's really weird! I can't manage to reproduce the error you're seeing. What OS and version of PHP are you running? Is your local LAMP server running the same versions of software as your host?

**Comment by nekloth** [comment]
I got the same error, running on RPi.

I set up the right to 777 on storage folder (even if owner:group is set to www-data:www-data).

I also set up SESSION_DRIVER=cookie (no effect).

```
user@RPi:/var/www/polr $ php -v
PHP 7.0.19-1 (cli) (built: May 11 2017 14:04:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1, Copyright (c) 1999-2017, by Zend Technologies
```

Any idea on how to solve that?

Thanks.
Nekloth

**Comment by sndrr** [comment]
@nekloth And your disk has free space (where the www-folder is)?

From one of the mentioned links:
> I was getting this message because my disk was out of space. df -H pointed this out but not until a lot of other debugging.
> 
> When the disk is full laravel can't save the updated csrf token but return it to the browser where it is then used.

**Comment by nekloth** [comment]
Thanks for the help.

Folder is on fresh new installation using a 250Gb hard-drive. Plenty of free space then...

Any other clue  ?

**Comment by urbels** [comment]
I have the same issue after updating my polr. Did not update for a while. Anyone managed to get rid off that error without reinstalling it completely?

**Comment by cydrobolt** [comment]
@urbels were you able to solve the issue? If updating your code caused the issue, you could try to `git checkout` a commit that worked for you. Without more information, I can't tell what specifically is causing your issue.

**Comment by urbels** [comment]
@cydrobolt No, its still broken and yes, before update it worked. Also I dont remember what was the commit that worked because it was a while ago. Its no so important also as I used that shortener only for myself.

**Comment by urbels** [comment]
I found this https://laravel.com/docs/5.0/routing#csrf-protection

And it seems that this meta tag is not used in polr.

**Comment by deshiloh** [comment]
I have the same error... someone find the solution ?

**Comment by urbels** [comment]
No luck
