### ISSUE TITLE
Problem on installation

### ISSUE THREAD

**Issue by NitroxydeX** [cydrobolt/polr#334]
I'm running into the following issue: 

`SQLSTATE[28000] [1045] Access denied for user 'forge'@'localhost' (using password: NO)`

when i try to access /setup. After some research 'forge'@'localhost' seems to be the default values of the lumen-framework. What do I do wrong? Shouldn't it use the .env file inside the root web directory?

I'm using PHP 5.6.29 with MySql 5.7 on Debian Jessie.

**Comment by cydrobolt** [comment]
Did you follow the docs? You need to copy `.env.setup` to `.env`

**Comment by NitroxydeX** [comment]
yeah I did. Like I mentioned: "Shouldn't it use the .env file inside the root directory".

Most of the needed extension come by default on PHP now, the other ones are installed. I cloned it via git command und run the global composer comment (since I use composer on some other projects too).

Database is created and I copied the .env.setup to .env inside the root web directory.

When I try to access I get the error message. What am I missing?

**Comment by cydrobolt** [comment]
What version of PHP are you running? Can you paste your env file, just in case? Where is located? (can you show an `ls -lah` of the folder it's in?)

**Comment by NitroxydeX** [comment]
I'm running PHP 5.6.29-0+deb8u1 (mixed up my writing with Apache in my first post)
It's located inside the _root_ folder of the domain. where the .setup.env is too.

I'll noticed, while writing this answer that by default the mysql thing is commented out inside the .env file.

Bringing it back in I get the new error `NotFoundHttpException in Application.php line 425:`

Changing the default DocumentRoot to /public solved this.

But changing the documentroot is something I don't really like. It's sad that Polr isn't working without this.

**Comment by cydrobolt** [comment]
That's good. What makes you dislike changing the DocumentRoot? It's a necessary step to run most Laravel-based apps. You could theoretically edit `public/index.php` and move it to the root folder, but I'm not sure why you want to avoid changing the DocumentRoot.

**Comment by NitroxydeX** [comment]
Installation is finished but no tables are in the database. ehh wtf?

**Comment by cydrobolt** [comment]
Did you run the setup script? Did that succeed? 

You could join our IRC channel and ask there if you'd like. That might be more effective. 
http://webchat.freenode.net?channels=%23polr
