### ISSUE TITLE
Is it possible to restrict json only output in .env file 

### ISSUE THREAD

**Issue by saivasanth** [cydrobolt/polr#336]
Is it possible to restrict json only output in .env file ? or  any other config file will do this , i  need to avoid text output

**Comment by cydrobolt** [comment]
You can set the `response_type` to `json` in all your requests. There is no way to remove the `plaintext` response type as an option, but you can avoid plain text responses by correctly setting the `response_code` for all your requests.

**Comment by saivasanth** [comment]
Thanks for your reply.!
