### ISSUE TITLE
Implement CAPTCHA and Enforce usage of strong pass- words.

### ISSUE THREAD

**Issue by saivasanth** [cydrobolt/polr#337]
Hi

we are now using polr , we have some issue in current version , 

1.how to add  CAPTCHA while login ?

2. how to  Enforce usage of strong pass- words.

3. how to validate username and password ,its allowing junk charters ex @$^&%$ 

kindly guide us to integrate this features in our current version. thanks in advance .

**Comment by cydrobolt** [comment]
1) I've implemented this feature as an option in #338
2) You can perform any actions on the password in `UserController` in the `performSignup` function
3) The username field does not allow special characters, but the password field does. It is highly recommended that you allow special characters in the password field.

**Comment by saivasanth** [comment]
hi 
now i have implemented  reCAPTCHA its working fine. Thanks for your reply.
BUT
USERNAME FILED STILL ALLOWED SPECIAL CHARACTERS . i created users i the name of 333### and even i can include <script>alert("XSS")</script> as a name . its tested in our setup. kindly look into this issue it will create major security issue.

**Comment by cydrobolt** [comment]
Sorry, but I'm unable to reproduce this. The username does not allow special characters. Are you running the latest version of Polr? What does UserController look like on your setup?

**Comment by saivasanth** [comment]
`<?php
namespace App\Http\Controllers;
use Mail;
use Hash;
use App\Models\User;
use Illuminate\Http\Request;

use App\Helpers\CryptoHelper;
use App\Helpers\UserHelper;

use App\Factories\UserFactory;

class UserController extends Controller {
    /**
     * Show pages related to the user control panel.
     *
     * @return Response
     */
    public function displayLoginPage(Request $request) {
        return view('login');
    }

    public function displaySignupPage(Request $request) {
        return view('signup');
    }

    public function displayLostPasswordPage(Request $request) {
        return view('lost_password');
    }

    public function performLogoutUser(Request $request) {
        $request->session()->forget('username');
        return redirect()->route('index');
    }

    public function performLogin(Request $request) {
        $username = $request->input('username');
        $password = $request->input('password');

        $credentials_valid = UserHelper::checkCredentials($username, $password);

        if ($credentials_valid != false) {
            // log user in
            $role = $credentials_valid['role'];
            $request->session()->put('username', $username);
            $request->session()->put('role', $role);

            return redirect()->route('index');
        }
        else {
            return redirect('login')->with('error', 'Invalid password or inactivated account. Try again.');
        }
    }

    public function performSignup(Request $request) {
        if (env('POLR_ALLOW_ACCT_CREATION') == false) {
            return redirect(route('index'))->with('error', 'Sorry, but registration is disabled.');
        }
		
		 if (env('POLR_ACCT_CREATION_RECAPTCHA')) {
            // Verify reCAPTCHA if setting is enabled
            $gRecaptchaResponse = $request->input('g-recaptcha-response');
            $recaptcha = new \ReCaptcha\ReCaptcha(env('POLR_RECAPTCHA_SECRET_KEY'));
            $recaptcha_resp = $recaptcha->verify($gRecaptchaResponse, $request->ip());
            if (!$recaptcha_resp->isSuccess()) {
                return redirect(route('signup'))->with('error', 'You must complete the reCAPTCHA to register.');
            }
        }

        // Validate signup form data
        $this->validate($request, [
            'username' => 'required|alpha_dash',
            'password' => 'required',
            'email' => 'required|email'
        ]);

        $username = $request->input('username');
        $password = $request->input('password');
        $email = $request->input('email');

        if (env('SETTING_RESTRICT_EMAIL_DOMAIN')) {
            $email_domain = explode('@', $email)[1];
            $permitted_email_domains = explode(',', env('SETTING_ALLOWED_EMAIL_DOMAINS'));

            if (!in_array($email_domain, $permitted_email_domains)) {
                return redirect(route('signup'))->with('error', 'Sorry, your email\'s domain is not permitted to create new accounts.');
            }
        }

        $ip = $request->ip();

        $user_exists = UserHelper::userExists($username);
        $email_exists = UserHelper::emailExists($email);

        if ($user_exists || $email_exists) {
            // if user or email email
            return redirect(route('signup'))->with('error', 'Sorry, your email or username already exists. Try again.');
        }

        $acct_activation_needed = env('POLR_ACCT_ACTIVATION');

        if ($acct_activation_needed == false) {
            // if no activation is necessary
            $active = 1;
            $response = redirect(route('login'))->with('success', 'Thanks for signing up! You may now log in.');
        }
        else {
            // email activation is necessary
            $response = redirect(route('login'))->with('success', 'Thanks for signing up! Please confirm your email to continue.');
            $active = 0;
        }

        $api_active = false;
        $api_key = null;

        if (env('SETTING_AUTO_API')) {
            // if automatic API key assignment is on
            $api_active = 1;
            $api_key = CryptoHelper::generateRandomHex(env('_API_KEY_LENGTH'));
        }

        $user = UserFactory::createUser($username, $email, $password, $active, $ip, $api_key, $api_active);

        if ($acct_activation_needed) {
            Mail::send('emails.activation', [
                'username' => $username, 'recovery_key' => $user->recovery_key, 'ip' => $ip
            ], function ($m) use ($user) {
                $m->from(env('MAIL_FROM_ADDRESS'), env('MAIL_FROM_NAME'));

                $m->to($user->email, $user->username)->subject(env('APP_NAME') . ' account activation');
            });
        }

        return $response;
    }

    public function performSendPasswordResetCode(Request $request) {
        if (!env('SETTING_PASSWORD_RECOV')) {
            return redirect(route('index'))->with('error', 'Password recovery is disabled.');
        }

        $email = $request->input('email');
        $ip = $request->ip();
        $user = UserHelper::getUserByEmail($email);

        if (!$user) {
            return redirect(route('lost_password'))->with('error', 'Email is not associated with a user.');
        }

        $recovery_key = UserHelper::resetRecoveryKey($user->username);

        Mail::send('emails.lost_password', [
            'username' => $user->username, 'recovery_key' => $recovery_key, 'ip' => $ip
        ], function ($m) use ($user) {
            $m->from(env('MAIL_FROM_ADDRESS'), env('MAIL_FROM_NAME'));

            $m->to($user->email, $user->username)->subject(env('APP_NAME') . ' Password Reset');
        });

        return redirect(route('index'))->with('success', 'Password reset email sent. Check your inbox for details.');
    }

    public function performActivation(Request $request, $username, $recovery_key) {
        $user = UserHelper::getUserByUsername($username, true);

        if (UserHelper::userResetKeyCorrect($username, $recovery_key, true)) {
            // Key is correct
            // Activate account and reset recovery key
            $user->active = 1;
            $user->save();

            UserHelper::resetRecoveryKey($username);
            return redirect(route('login'))->with('success', 'Account activated. You may now login.');
        }
        else {
            return redirect(route('index'))->with('error', 'Username or activation key incorrect.');
        }
    }

    public function performPasswordReset(Request $request, $username, $recovery_key) {
        $new_password = $request->input('new_password');
        $user = UserHelper::getUserByUsername($username);

        if (UserHelper::userResetKeyCorrect($username, $recovery_key)) {
            if (!$new_password) {
                return view('reset_password');
            }

            // Key is correct
            // Reset password
            $user->password = Hash::make($new_password);
            $user->save();

            UserHelper::resetRecoveryKey($username);
            return redirect(route('login'))->with('success', 'Password reset. You may now login.');
        }
        else {
            return redirect(route('index'))->with('error', 'Username or reset key incorrect.');
        }

    }

}`


i have two error now

1. FatalErrorException in /var/www/html/polr/app/Http/Controllers/UserController.php line 63: Class 'ReCaptcha\ReCaptcha' not found

2. username allowed $$$####333

**Comment by saivasanth** [comment]
finally integrate  reCAPTCHA and username and password restriction in signup page 

my Final query

1. how to add  reCAPTCHA in sign-in page ? 
2. how add   alpha_num  in admin page user creation and password limt for min 8 via admin (new user creation via admin panel dont have valadation)

**Comment by cydrobolt** [comment]
1) Look into the code used to add the captcha to the sign up page and add it to UserController@performLogin and login.blade.php
2) Use  
```php
   $this->validate($request, [
        'username' => 'required|alpha_dash',
        'password' => 'required',
        'email' => 'required|email'
    ]);
```
 to validate the username in AjaxController@addNewUser

In regards to the missing recaptcha dependency, please use composer to update your dependencies.

**Comment by saivasanth** [comment]
@cydrobolt  

Thanks for your support.! your comments helped lot to clear our issues.

i would like to contribute something to  polr, can you suggest something for me ?
 
i have that short link expire date option in our polr   is it ok shall i work on that, is any previous work done on this ?

**Comment by cydrobolt** [comment]
It would be great if you could help contribute to our project! No, we haven't worked on expiry dates yet. If you want to add that option, we'd be open to reviewing your PR! 

We have some issues on GH that we need to address, and you're welcome to contribute what you can. :)

Let me know if you need any more help.
