### ISSUE TITLE
Can't install at all :(

### ISSUE THREAD

**Issue by ildarn** [cydrobolt/polr#340]
Hi. Can someone please help me with the installation.
VM: ec2 (amazon linux) with apache and php 7.

The problem: setup page does not want to open at all. Other websites on different virtual hosts open fine.

I am really super confused, because Safari and Chrome just show nothing. Maybe I can not install polr on sub domain?

Chrome says:
This page isn’t working
dev1.brskn.com is currently unable to handle this request.
HTTP ERROR 500

`<VirtualHost *:80>`
`DocumentRoot "/apps/polr/public"`
`<Directory "/apps/polr/public">`
`Options Indexes FollowSymlinks`
`AllowOverride All`
`Require all granted`
`</Directory>`
`  ServerName dev1.brskn.com`
`  ErrorLog "/var/log/httpd/polr-error_log"`
` CustomLog "/var/log/httpd/polr-access_log" common`
`</VirtualHost>`

Please, explain someone :)

**Comment by cydrobolt** [comment]
Can you set APP_DEBUG to true in your `.env` file? Can you share any errors you're getting from your logs?

**Comment by cydrobolt** [comment]
On my end, I'm getting "The provided host name is not valid for this server."

**Comment by ildarn** [comment]
Changed the subdomain back.
ServerName dev1.brskn.com

I will try to set APP_DEBUG right now.

**Comment by ildarn** [comment]
As far as I can see, APP_DEBUG is already = true

```
APP_ENV=local
APP_DEBUG=true
APP_KEY=,faO^ofvGeJ8|Z.q{mWp=^i}Cmzj+k&K
```

**Comment by ildarn** [comment]
`[Thu May 25 19:27:49.268080 2017] [:error] [pid 890] [client MY IP:53317] PHP Fatal error:  require_once(): Failed opening required '/apps/polr/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear7:/usr/share/php7') in /apps/polr/bootstrap/app.php on line 3`

**Comment by ildarn** [comment]
Actually, here are two different errors:

```
[Thu May 25 19:34:11.684183 2017] [:error] [pid 893] [client IP:53501] PHP Warning:  require_once(/apps/polr/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /apps/polr/bootstrap/app.php on line 3
[Thu May 25 19:34:11.684222 2017] [:error] [pid 893] [client IP:53501] PHP Fatal error:  require_once(): Failed opening required '/apps/polr/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear7:/usr/share/php7') in /apps/polr/bootstrap/app.php on line 3
```

**Comment by cydrobolt** [comment]
Did you properly follow the installation docs and install the dependencies with composer?

**Comment by ildarn** [comment]
I think so ...

```
[root@ip-172-26-15-118 bootstrap]# yum install php70-openssl php70-pdo php70-mbstring php70-tokenizer php70-json php70-curl php70-common
Loaded plugins: priorities, update-motd, upgrade-helper
Package php70-common-7.0.16-1.21.amzn1.x86_64 already installed and latest version
Package php70-pdo-7.0.16-1.21.amzn1.x86_64 already installed and latest version
Package php70-mbstring-7.0.16-1.21.amzn1.x86_64 already installed and latest version
Package php70-common-7.0.16-1.21.amzn1.x86_64 already installed and latest version
Package php70-json-7.0.16-1.21.amzn1.x86_64 already installed and latest version
Package php70-common-7.0.16-1.21.amzn1.x86_64 already installed and latest version
Package php70-common-7.0.16-1.21.amzn1.x86_64 already installed and latest version
Nothing to do
```

**Comment by cydrobolt** [comment]
composer dependencies, not system dependencies. 

Please go read the installation documentation from top to bottom.

**Comment by ildarn** [comment]
Sorry. never worked with composer.

Looks like everything is okay now 👍

**Comment by cydrobolt** [comment]
Great! Sounds good :)
