### ISSUE TITLE
Theming support

### ISSUE THREAD

**Issue by tomslominski** [cydrobolt/polr#341]
Expected Behavior
-------------------

Hi. I'm just looking to find out if Polr has any sort of theming support, or whether it's expected that the user should just change /resources/views/ and avoid overwriting that folder when they update Polr. In case it doesn't, do you think this would be a useful thing to add?

Current Behavior
-----------------
I think the right thing to do currently is to overwrite /resources/views/ with our own templates.

Possible Solution
------------------
A theming system, akin to WordPress where the user can select themes, or alternatively just a directory in which Polr will look first for appropriate files (sort of like WordPress child themes).

Context
--------
I have a client who is looking to use Polr instead of YOURLS for their URL shortener because of your inbuilt premium API support and user management - however, we obviously need to customize their site.

**Comment by cydrobolt** [comment]
Yes, you can edit the blade templates in the views folder. If you use git with Polr, git might be able to merge upstream changes without overwriting your changes, although I can't guarantee there won't be any merge conflicts.

**Comment by tomslominski** [comment]
Cool, thanks!
