### ISSUE TITLE
Feature Requests Show unique click and Add an ability to admin to see all user and How many Clicks They got as Per Month 

### ISSUE THREAD

**Issue by starcollon12** [cydrobolt/polr#342]
Hi 
I curious to Know is It possible to Show Unique click and total click for link and Also Add ability to admin to see all user links and Their Total click and Unique click and Short them by months
and JUST one More thing which i found In from US and It show me From France Why This Happens Can You take a look at That

**Comment by overint** [comment]
We are working on adding the ability to see unique hits, geoIP is sometimes inaccurate hence why it might be picking you up as USA incorrectly, but it's not an issue from this project.

**Comment by overint** [comment]
Closing this as it's a duplicate.
