### ISSUE TITLE
NotFoundHttpException in Application.php

### ISSUE THREAD

**Issue by hcaz** [cydrobolt/polr#344]
Newer versions of Laravel the abort helper has being removed leading to a NotFoundHttpException error when called. Due to this the link controller throws an error for short links that do not exist, or have being disabled.

## Expected Behavior
When visiting a short url that does not exist, or has expired the clean 404 page (errors/404.blade.php) should be shown to the user.

## Current Behavior
When visiting a short url that does not exist or has expired, a Larevel NotFoundHttpException error is shown.

## Possible Solution
Change old abort helper functions to full responses with a view passed.

## Steps to Reproduce (for bugs)
1. Setup Polr
2. Visit a un-created url
3. See error page

## Context
Trying to keep consistency on pages across the Polr platform, and show clean error messages.

## Your Environment

* Version or latest commit hash (`git rev-parse HEAD`): 131b9925c24990261c3afc67994f34656432743e
* Environment name and version (e.g. Chrome 39, PHP 7.0, etc): PHP7.1, Apache2
* Instance link (optional): http://duct.me/

**Comment by cydrobolt** [comment]
I get a formatted error message when I go to duct.me/doesnotexist.

I'm not sure what you're trying to change. Are you suggesting that all 404s use the same template?

**Comment by hcaz** [comment]
@cydrobolt See #345. If you are using my instance, it will display correctly, as it is already fixed via that PR. :)
