### ISSUE TITLE
Create QR Code of shortened URL

### ISSUE THREAD

**Issue by c456fa2** [cydrobolt/polr#347]
I think I'd be nice to show the qr code of the shortened URL below the URL in clear text.
The qr code might be generated temporarily as SVG or PNG in php/javascript source.

## Expected Behavior

After submitting the Long-URL the URL is shortened. Below the line with the Short-URL the QR code ought to appear.

## Current Behavior

The URL is only shortened.

## Context

I use polr to share links to my site. If I want to share the link via qr code I have to manually generate it.

**Comment by nprail** [comment]
This would be a great feature!

**Comment by overint** [comment]
#350 was created, however client side QR code generation is prefered so I have created PR #375
