### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by pnexusj** [cydrobolt/polr#349]
how to install polr on shared hosting which do not supports ssh

**Comment by cydrobolt** [comment]
Installing Polr on shared hosting is a difficult task. If your shared hosting provider fulfills all of Polr's requirements, you may be able to install Polr by setting the DocumentRoot to `polr_root/public` and providing the setup script with the proper credentials (i.e MySQL, etc).

You can clone Polr locally, run the proper `composer` commands, then upload the whole folder to your shared host. 

You can also install a 1.x release of Polr (e.g 1.5.1), which should work with shared hosts out of the box.

**Comment by pnexusj** [comment]
thanks its working

**Comment by sibidharan** [comment]
@pnexusj @cydrobolt Please close the issue.
