### ISSUE TITLE
I need to know how I can change the long link of a shortened link using polr..? I created a link and it worked beautifully.  however we had to modify the link that the file is attached to in dropbox, therefore changing the long link address... not the shortened link does not work cause the file is not located in original address.   When i look at my dashboard in polr.. I see the link, but I can't edit the long link address

### ISSUE THREAD

**Issue by dfree71** [cydrobolt/polr#352]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version or latest commit hash (`git rev-parse HEAD`):
* Environment name and version (e.g. Chrome 39, PHP 7.0, etc):
* Instance link (optional):

**Comment by mihawk90** [comment]
As far as I know there is no direct way (yet) to change the long (nor the short) link, see also #173. Edit the link in the database directly (or ask someone who can).

PS: If you can, please edit your post and use a short title, your current ones belongs into the description.

**Comment by cydrobolt** [comment]
It's possible to modify the long link. Simply click the "edit" button next to the long link. You must be on the latest revision of `master`. Without providing more information, there's not much we can do to help. 

What version/commit hash are you running?
