### ISSUE TITLE
Error on install guide

### ISSUE THREAD

**Issue by Zatalyz** [cydrobolt/polr#353]
In https://docs.polrproject.org/en/latest/user-guide/installation/ it say `php composer.phar install --no-dev -o`

But it is not "composer.phar" in actual deposit. So it can't work : 
```
#php composer.phar install --no-dev -o
Could not open input file: composer.phar
```
Update doc or recreate composer.phar ?

**Comment by cydrobolt** [comment]
That step assumes that you downloaded `composer.phar` in the previous step.
