### ISSUE TITLE
Experience with polr on AWS Elastic Beanstalk and S3.

### ISSUE THREAD

**Issue by ildarn** [cydrobolt/polr#354]
Hi.

We are about to move polr from ec2 to Elastic Beanstalk.
But the .env file contains these lines:
```
# FILESYSTEM_DRIVER=local
# FILESYSTEM_CLOUD=s3
```

Question: if I would like to run polr on Elastic Beanstalk and S3, should I change these settings?
I guess, uncomment the FILESYSTEM_CLOUD=s3 line and credentials to
```
S3_KEY=
S3_SECRET=
S3_REGION=
S3_BUCKET=
```
Should we do anything with **FILESYSTEM_DRIVER=local** ?

Thank you.

**Comment by cydrobolt** [comment]
I don't think we do very much in terms of file storage. I don't think it's necessary to change the S3 settings unless you're currently storing files through Laravel.

**Comment by cydrobolt** [comment]
The files we store locally are mostly all cache or session files. If you'd like to remove file dependencies, you can change your session, cache etc drivers to use a non-file driver (e.g DATABASE)

**Comment by ildarn** [comment]
> The files we store locally are mostly all cache or session files. If you'd like to remove file dependencies, you can change your session, cache etc drivers to use a non-file driver (e.g DATABASE)

Yeah, I just was going to mention storage/framework directory.
So, just change these settings on **database** ?
```
CACHE_DRIVER=file
SESSION_DRIVER=file
```
What to do with the **view** folder? It also has many files what are changed.

Any potential performance decreasing if we change it to **database** ?

Thank you very much.

**Comment by cydrobolt** [comment]
Yeah, you can use the database driver instead. There shouldn't be a big difference in performance. I'm not sure how switching to Beanstalk would affect the views you've changed. Unless you're uploading the application code to S3 (which I'm assuming you're not doing), you shouldn't upload your views to S3.
