### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by iamkingsleyf** [cydrobolt/polr#355]
Hello;

I am unable to install, i keep getting error. i use serverpilot on ubuntu 16.04.

```
Forbidden

You don't have permission to access /polr/ on this server.

Possible causes of this error include:

The request was forbidden by rules in the .htaccess file.
The directory you requested does not have an index.html or index.php file.
The permissions on the file or directory are incorrect.
For details about why the request was forbidden, see the Apache error log at:

/srv/users/SYSUSER/log/APPNAME/APPNAME_apache.error.log

```

**Comment by cydrobolt** [comment]
Did you set the proper permissions as per the documentation?

**Comment by iamkingsleyf** [comment]
Yes I did. 

Seems it can't be installed on shared hosting like yoururls

**Comment by iamkingsleyf** [comment]
i guess it can't be installed in a shared hosting environment like yoururls?

**Comment by overint** [comment]
You should be able to install it on shared hosting ok. Could you post the output of the error log?

**Comment by iamkingsleyf** [comment]
Has it been updated? I use plesk

**Comment by overint** [comment]
What error do you get in your logs?

**Comment by iamkingsleyf** [comment]
i have none because its been over 2 months ago

**Comment by overint** [comment]
Ahh, ok. I've run both laravel and lumen on shared hosting before, they are a bit of a pain to set up but it is possible.

**Comment by iamkingsleyf** [comment]
alright. hope it will be made simple to setup in lamp stack with nginx

**Comment by overint** [comment]
We are working on a docker image at the moment, which should make setup very easy.

**Comment by overint** [comment]
It should be pretty easy to run on a LEMP/LAMP stack, that's how i'm running it and i assume most others are.

**Comment by iamkingsleyf** [comment]
@overint i tried it, did not work.
