### ISSUE TITLE
Finishing Install leads to an error

### ISSUE THREAD

**Issue by guillaumedsde** [cydrobolt/polr#356]
Finishing install leads to Error, not sure why or how to know why

## Expected Behavior
It should finish the setup and reload the page.

## Current Behavior
"Whoops, looks like something went wrong."

## Context
Installed using instructions originally for nextcloud but adapted: 
http://howto.wared.fr/ubuntu-installation-nextcloud-nginx/

## Question:
I've enabled APP_DEBUG=true in .env where do I view the debug info?

## Your Environment
Ubuntu 17.04 Nginx php7.0 mariadb

**Comment by ohninedotseven** [comment]
i found it was because registration was disabled- i fixed it by only allowing my domain to register and it seemed to work

**Comment by cydrobolt** [comment]
After enabling `APP_DEBUG`, you should go back to the page that gave you the "Whoops, looks like something went wrong." page to receive more detailed errors. Could you post the stack trace so that we can better assist?

**Comment by guillaumedsde** [comment]
Thanks for the assist, ended up reinstalling from scratch, looking back on the issue, I suspect it was probably my bad nginx configuration skills that resulted in a poorly configured PHP block in the ttrss nginx config.
