### ISSUE TITLE
How To create all shortlink link ? 

### ISSUE THREAD

**Issue by kawaguchimaeda8** [cydrobolt/polr#358]
Is there any script all website short link? So like script for blog or wordpress. Every outgoing link will be on short. 

example script full page script

<script type="text/javascript">
    var go_url = 'http://demo.polr.me/';
    var go_api_token = 'f13aadd5ea608c6c55ee99b2f';
    var go_advert = 2;
    var go_exclude_domains = ['example.com', 'yoursite.com']; 
</script>
<script src='http://demo.polr.me//js/full-page-script.js'></script>

how to make in http://demo.polr.me/ ?

**Comment by cydrobolt** [comment]
I'd suggest you take a look at https://docs.polrproject.org/en/latest/developer-guide/api/ if you'd like to write your own implementation.

I don't think this is a feature we'd want to officially support, although you're welcome to contribute your own script if you'd like. You can make POST requests to the `shorten` endpoint to shorten URLs. You can replace each link's existing `href` attribute with the resulting short URL.

**Comment by kawaguchimaeda8** [comment]
I install in cpanel can not installer . What is this programming?

**Comment by overint** [comment]
You would need to create your own custom script to do this, it's not a feature currently and I doubt it would ever be added.
