### ISSUE TITLE
new table?

### ISSUE THREAD

**Issue by urbels** [cydrobolt/polr#360]
Hey! In one of latest updates something changed but no new table added?

When shorting url I get error:
Error
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'long_url_hash' in 'where clause' (SQL: select * from `links` where `long_url_hash` = 303505756 and `long_url` = https://www.linkqocroqnrncuqurncpqnrcqnr.com and `is_custom` = and `secret_key` = x and `creator` = ? limit 1)

**Comment by cydrobolt** [comment]
Did you migrate your database as described in the documentation upgrade guide?

**Comment by urbels** [comment]
It says that it can't connect to database. I have correct access codes in .env file. Also site works too.

**Comment by urbels** [comment]
halp? :)

**Comment by cydrobolt** [comment]
Make sure your credentials in `.env` are correct and run migrations.

**Comment by urbels** [comment]
false alarm. Triple checked and now it works! Thanks!
