### ISSUE TITLE
[REQUEST] Theme selection

### ISSUE THREAD

**Issue by safeershahul** [cydrobolt/polr#363]
**FIX :** Default/Classic installs the Sandstone theme and not the default one as shown [here](https://github.com/cydrobolt/polr/wiki/Themes-Screenshots)

**FIX :** Deprecated themes in the Wiki

**REQUEST :** Incorporate more themes from bootswatch like [Solar](https://bootswatch.com/solar/) and [Cosmo](https://bootswatch.com/cosmo/)

**Comment by cydrobolt** [comment]
If you would like, you can submit a PR to `setup.blade.php` to add these themes. Let me know if you need any assistance.

**Comment by overint** [comment]
PR created #373

**Comment by overint** [comment]
@cydrobolt This can be closed now.
