### ISSUE TITLE
Feature requests for improving Polr

### ISSUE THREAD

**Issue by awesomeghost** [cydrobolt/polr#365]
Features request i need for my url shortener.
## Expected Behavior

- let us add pages easily from admin area like terms and conditions, our custom about instead of editing the blades and routes.php manually
- api rate limiting could let us choose how many request per hour, day, and for example you can rate limit every endpoint different limits like create url 50 per hour and get a link info 100 per hour
- let us choose the pattern for short links generation and not only numbers from the admin area like enable capital letters or etc customize
- let us add seo description, meta description is missing
- let us protect with password links if choosen and feature is enabled
- let us to pick another bootstrap theme after finishing setup in admin area if we wish
- let us add descriptions to pages they seem very empty (optional not needed)
## Current Behavior

feature s aren't available and i need them 
## Possible Solution

feature s should be added to release my shortener 
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Cuz i need to release my shortener and these features are important for me
## Your Environment

* Version or latest commit hash (`git rev-parse HEAD`): Latest Polr version downloaded yesterday from source with git clone
* Environment name and version VPS, PHP 7.0
* Instance link (optional):

**Comment by awesomeghost** [comment]
Oh and i forgot these ones more
- let us limit the amount shortened urls can be made by the same account, ip, (to avoid spam)
- let us restrict shortening to only specific hostnames e.g. They can only shorten from site1.com and site2.com (if enabled )

**Comment by overint** [comment]
Hi awesomeghost,

I think it would be much easier if you created a separate issue for each feature, as it's not easy to track so many in one ticket.

**Comment by msetyon** [comment]
A way to AB Test feature would be nice, similar to http://na.gg

**Comment by overint** [comment]
Going to close this, feel free to open more issues for the individual requests you have.
