### ISSUE TITLE
/vendor/autoload.php Error when installing.

### ISSUE THREAD

**Issue by saivasanth** [cydrobolt/polr#367]
We are facing installing issue. when we install polr then it thorws 

> Warning: require_once(C:\xampp\htdocs\polr\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\polr\bootstrap\app.php on line 3

**Comment by cydrobolt** [comment]
Follow the docs and install the composer dependencies.
