### ISSUE TITLE
url with parameters: parameters are ignored?

### ISSUE THREAD

**Issue by chrisschd** [cydrobolt/polr#370]
I try to shorten url via API but the parameter are missing, when a add the url on the webform it works.

## Expected Behavior
http://example.com/api/v2/action/shorten?key=API_KEY_HERE&url=https://google.com&id=1234&custom_ending=CUSTOM_ENDING&is_secret=false

=> example.com/0 => Redirect on https://google.com&id=1234

## Current Behavior

=> example.com/0 => Redirect on https://google.com
(&id=1234 is misssing)

## Possible Solution
Encoded URL:
http://example.com/api/v2/action/shorten?key=API_KEY_HERE&url=https%3A%2F%2Fgoogle.com%26id%3D1234&custom_ending=CUSTOM_ENDING&is_secret=false

But then a get a invalid or missing parameter Exception :(

Any Idea how I can create shorten url with parameters via the API Interface? Thanks

**Comment by lingdu0001** [comment]
+1

**Comment by overint** [comment]
You can make post requests to the api which would not be affected by this issue, is this a suitable workaround for you?

**Comment by lingdu0001** [comment]
Thank you for you reply, but it doesn't work as well.

**Comment by overint** [comment]
Could you let me know the case where using a post request would not work?

**Comment by lingdu0001** [comment]
https://www.example.com/views/web/wechat/invitePatient.html#invite_patient_section?expertCircleId=909&orgNumber=1

**Comment by lingdu0001** [comment]
@overint 
https://www.example.com/views/web/wechat/invitePatient.html#invite_patient_section?expertCircleId=909&orgNumber=1

**Comment by overint** [comment]
I tested shortening the link you provided via the API as a post request, and it works fine.
![](http://puu.sh/y8V7w/aa9c98949b.png)

**Comment by lingdu0001** [comment]
I tested it on my java project, and i  will try another way to send post request. Thank you!  @overint

**Comment by overint** [comment]
No worries!

**Comment by sndrr** [comment]
@lingdu0001 Is this issue resolved? If it is, please close it.

**Comment by lingdu0001** [comment]
I will close it now.Thank you

**Comment by lingdu0001** [comment]
This issue is resolved ,but I have no access to close it. Would you please close it ?Thank you!
@sndrr
