### ISSUE TITLE
Password handling is broken

### ISSUE THREAD

**Issue by Vertux** [cydrobolt/polr#371]
It seems that the handling of complex passwords is broken. It took me an hour to find out, that my complex passwords were not correctly processed by Polr. 

![bildschirmfoto 2017-10-05 um 15 26 31](https://user-images.githubusercontent.com/10457918/31230510-8ab7a3d4-a9e4-11e7-9f6a-5a0bdb27efa1.png)

Because of this issue the installation could not completed successfully. The database access failed because of a "wrong" password.   

## Possible Solution
- Modified password handling
- A hint in the installation documentation to not use special character for the password (bad) or to always enclose the password in single/double quotation marks.
- A meaningful error message ( not: "Ups something went wrong ;-) )

## Steps to Reproduce (for bugs)
Use the password in the image above.

## Your Environment
- Ubuntu 16.04
- git rev-parse HEAD : 514d475ed01a1ef9365c258ae51a028941a67f38

**Comment by cydrobolt** [comment]
Added double quotes around key values in #372. The patch should allow certain special characters to appear.
