### ISSUE TITLE
increment clicks via api

### ISSUE THREAD

**Issue by vesper8** [cydrobolt/polr#380]
I use polr via api only, including for handling the redirections

I hit a route, do a lookup via the api, and then do the redirect all in my app. Doing a lookup doesn't seem to increase clicks by its own. How can I have the clicks increase when using only the api?

**Comment by overint** [comment]
PR Created #382

**Comment by cydrobolt** [comment]
I don't think this is a feature we'd like to support. Using Polr simply for the API is a novel usage pattern and it doesn't make sense to officially support analytics for users who use it in this manner.

If you'd like, you're totally welcome to create your own implementation of this feature and use it on your own installation. However, I don't think it makes much sense to add this functionality anywhere in the official codebase.

imo, using Polr "only for the API" defeats its purpose in a way, and that's not a pattern we'd like to support.

**Comment by vesper8** [comment]
@cydrobolt Let me explain my use-case a little better then maybe you could reconsider allowing @overint's PR

I have my shortener url which is https://fogn.me and my polr installation which is https://polr.fogn.me

Right now both of them accept short links. For example my new short-link "v2" works with both https://fogn.me/v2 and https://polr.fogn.me/v2

If you hit the latter then the clicks will be incremented naturally. If you hit the former then an api lookup is done by my app and if the shorturl is a valid link, then the redirect is done by the app.

Now to get around this issue I was having I am simply having the former redirect to the latter.. so now both urls result in clicks being incremented but the former results in a lookup + 2x redirect whereas the latter is just a normal redirect

Now why do I need to do this? Simply.. I want https://fogn.me to load an app-related route.. and ONLY if you pass it a polr short-url then it acts as a polr redirect

I couldn't have achieved this if I installed polr directly on https://fogn.me, this gives me the flexibility of using my short domain for both polr redirects and app-related routes.
