### ISSUE TITLE
Make client validation before user submitted?

### ISSUE THREAD

**Issue by tdtgit** [cydrobolt/polr#383]
I can make a PR for client validation if you guys accept it :)

## Expected Behavior

Required long URL, username, password before user submit for reduce server load.

## Current Behavior

Show error, required field after user submitted, after a reload page.

## Possible Solution

Add `required` attribute to `input` element or any jQuery plugin you suggest

## Context

Useless server load & requests.

**Comment by overint** [comment]
This is a good idea, and should be pretty simple to implement. Will PR soon :)
