### ISSUE TITLE
Can't proceed through setup

### ISSUE THREAD

**Issue by cgass** [cydrobolt/polr#387]
I've been trying to get Polr working and every time I browse to the /setup page, it shows what appears to be PHP code (see attachment). I believe I've installed all prerequisites, setup my database, and setup virtual hosts correctly. 

![screen shot 2017-11-06 at 2 20 23 pm](https://user-images.githubusercontent.com/7819353/32462141-f612c87a-c2fd-11e7-9298-b34b8100a095.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version or latest commit hash (`git rev-parse HEAD`):
* Environment name and version (e.g. Chrome 39, PHP 7.0, etc):
* Instance link (optional):

**Comment by cydrobolt** [comment]
Can you please describe your setup? Are you using `nginx` or `apache`? What version of `php` are you running?

**Comment by cgass** [comment]
I'm using apache2 on Ubuntu 16.04.3 LTS

Version 7 for php-common and plugins
Database is mysql-server version 5.7

I've tried running polr on Centos 6.9 and 7.0 as well. Every time I've gotten to the part where .env is copied to the root directory, I get the same PHP output when I try browsing to setup.

**Comment by cydrobolt** [comment]
What does your Apache config / VirtualHost look like? Can you take a look at this as well? https://stackoverflow.com/questions/12142172/apache-shows-php-code-instead-of-executing

**Comment by cgass** [comment]
I solved the issue. PHP Engine was disabled in my PHP plugin config file. Thanks for the help - Polr is pretty sweet :)

**Comment by sndrr** [comment]
@cgass Could you close this issue?

**Comment by overint** [comment]
@cydrobolt Can we close this, it's resolved.
