### ISSUE TITLE
how do I debug?

### ISSUE THREAD

**Issue by urbels** [cydrobolt/polr#389]
My installation worked fine but today it throws error 503.

No apache errors or smth. Turned on debug in .env but still nothing.

**Comment by cydrobolt** [comment]
This sounds like a problem with your load balancer or web server, rather than a problem with Polr itself. Were you able to resolve the issue? If so, please close it :)

**Comment by overint** [comment]
503 generally means there was a problem with the web server (or further upstream). 
Regardless, I think this issue can be closed now @cydrobolt
