### ISSUE TITLE
Issue with email link

### ISSUE THREAD

**Issue by Calvinism** [cydrobolt/polr#391]
Not sure if anyone else have this issue. I'm using zoho mail to send out activation and lost password. I checked on zoho mail for the mail send out is a working link but on the receiving end, on gmail, it's only text and not a link. But it's still a html format not plain text. Issue is on gmail?

Hello calvin!

You may use the link located in this email to reset your password for your account at T-RF.
https://t-rf.com/reset_password/calvin/9c44c5f1ebcb42466ee9634dd9bdfe6507e0f29bcddd8575acb20fa67fd395ede3fdcc29fe3b35d62616f45d9351d48fcdd3 Links

Thanks,

The T-RF team.

**Comment by cydrobolt** [comment]
That might be due to differences in how each browser interprets the HTML that we send in our emails. There's not much we can do on our end to control how they handle our emails.

**Comment by Calvinism** [comment]
Yes I understand. I tested on yahoo mail and it's showing as a link. Looks like gmail is blocking the display of links for security purpose.
