### ISSUE TITLE
Cannot view admin page over SSL in a consistent manner

### ISSUE THREAD

**Issue by LoZio** [cydrobolt/polr#395]
Even if you set APP_PROTOCOL="https://" in the .env file, you are continuously redirected to http:// pages

## Expected Behavior
If I login via SSL connection, the app must remain on SSL

## Current Behavior
I set up a reverse proxy with SSL using AWS ELB. I can reach the login page via secure https.
After login I'm back to clear http. If I manually change to https it works until I use one of the links in the menu, that are all http and not https

## Possible Solution
Maybe you're trying to guess the protocol using ports or headers, but since there is a setting in the env only that should be used.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
AWS ELB, with ELB offloading the SSL

## Your Environment

* Version or latest commit hash (`git rev-parse HEAD`): e47c07fcbbe0fbb67c4f5ac92766d43d6f692e23
* Environment name and version (e.g. Chrome 39, PHP 7.0, etc):PHP 7.0.25, Aws Linux, Chrome/FF/Edge/IE all behave the same

**Comment by justdotJS** [comment]
Use CloudFlare or some redirect to forcefully redirect HTTP to HTTPS. It's almost certainly not a Polr bug.

**Comment by sndrr** [comment]
When I set the .env to https:// all the links on the public frontpage (and the ones after login) are SSL/TLS-links. So I cannot reproduce this behaviour.

@LoZio Does your host forward all http-traffic to https?

**Comment by LoZio** [comment]
I have setup the variable as HTTPS:// and all links in the page are HTTP://, easy to see in the html source.
BTW using relative links there should be no issue in using one or the other

**Comment by LoZio** [comment]
![image](https://user-images.githubusercontent.com/869890/33899388-a622d1cc-df6b-11e7-9deb-446fb104205a.png)

This is the source from the page that is reached via https (with valid SSL certificate and all the stuff...)

**Comment by sndrr** [comment]
And this is mine, so I have trouble reproducing :frowning_face: :
![screenshot_2017-12-12_21-56-08](https://user-images.githubusercontent.com/5821198/33908293-366934c6-df88-11e7-9674-39e08edfd7e0.png)

From my ```.env```:
```
# Protocol to access your app. e.g https://
APP_PROTOCOL="https://"
```
Did you reach your dashboard over https? Did not look into the code too extensively, but they are all doing something like ```<li class="visible-xs"><a href="{{ route('admin') }}">Dashboard</a></li>``` (see [resources/views/snippets/navbar.blade.php](https://github.com/cydrobolt/polr/blob/master/resources/views/snippets/navbar.blade.php#L24))

Is anybody else having the same issues?

**Comment by LoZio** [comment]
Trust me, I know the difference between http and https pretty well.
![image](https://user-images.githubusercontent.com/869890/33925773-b3f65894-dfdb-11e7-8334-5e34b6a806eb.png)

and this is the setting
![image](https://user-images.githubusercontent.com/869890/33925845-02164318-dfdc-11e7-9a23-db43dea89119.png)

I suppose there is some problem having the SSL layer offloaded to the load balancer, and the app somewhat assumes to be using http (in fact it is) instead of https.

**Comment by andrewimeson** [comment]
@LoZio are you passing a header (like `X-Forwarded-Proto: https`) back from the load balancer to the web server (and making the web server trust it) to let it know what protocol the request comes in on? If not, you may need to need to do that for it to work.

In the screenshot you posted the quotation mark after `https://` is a different color, which might mean that you have a smartquote somewhere in there where it should be a normal quote.

**Comment by LoZio** [comment]
The header is present, it is automatically added by AWS ELB. I don't know how to make the server trust it.
This is the same feeling I had and that's what I was saying in the "Possible solution" and next posts.
About the color I already noted that and did some checks. It is my nano that colors it that way. I deleted the line and rewrote it with vi and it is all the same.

**Comment by andrewimeson** [comment]
@LoZio if you're using Apache httpd for the polr server, something like following in your Apache config may work
```
SetEnvIf X-Forwarded-Proto "https" HTTPS=on
```

**Comment by LoZio** [comment]
You got it @andrewimeson . The app or the underlying framework guesses the protocol and is not succesfull without this header set. I hope this will find its way to the docs (perhaps together with the way to configure the trusted proxies, #343).
Thank you and merry Christmas!
