### ISSUE TITLE
API quota check performs full table scans

### ISSUE THREAD

**Issue by iurisilvio** [cydrobolt/polr#403]
I have a deploy with ~1 million links and growing. Creating new links is really slow now.

With a clean database, I was able to generate ~1000 links/minute, but now it generate ~50/minute.

How can I increase writing performance?

I'm using MariaDB with the master branch up to date.

**Comment by sndrr** [comment]
I suppose you have all the database optimizations in play? Ramdisk for temp tables, enough memory for the whole database in RAM and a fast (SSD) disk?

**Comment by iurisilvio** [comment]
Yes, the machine has only 30% RAM used and SSD.

Today I tried to switch some MySQL flags, had some success increasing buffer pool size and write io threads:

```
innodb_buffer_pool_size = 2147483648
innodb_write_io_threads = 16
```

I found the rate limit checker is slower than any other query (~0.7s). The query don't use an index, scanning all my 10^7 links and returning ok. Obviously it is critical only for large databases.

```
# Query_time: 0.774936  Lock_time: 0.000021  Rows_sent: 1  Rows_examined: 1163781
select count(*) as aggregate from `links` where `is_api` = '1' and `creator` = 'me' and `created_at` >= '2017-12-20 22:10:04';
```

I did a pull request to avoid the query when `$api_quota == -1`. I was creating ~1 link/s, with this change more than 10.

Didn't tested, but creating an `created_at, creator` index can improve this query a lot.

**Comment by cydrobolt** [comment]
Thank you for the PR! Avoiding the quota check for an unlimited quota seems like a good step towards improving the performance of the endpoint. 

Creating an index could also significantly improve the performance of the quota check. Perhaps comparing the performance impact of the query with and without the indexes can help us narrow down a solution.

**Comment by iurisilvio** [comment]
I created an index with `created_at DESC, creator, api` and now queries for last minute data are really fast.

It is the complete solution for this problem, when you don't want to remove api quota.

**Comment by iurisilvio** [comment]
Added another PR to create the index.

I did some tests with my large database, it is really fast to count last minute data.

I even removed my last patch to check if the performance is still good. I reduced my server a bit,

```sql
# Query_time: 0.001529  Lock_time: 0.000020  Rows_sent: 1  Rows_examined: 668
SET timestamp=1513869458;
select count(*) as aggregate from `links` where `is_api` = '1' and `creator` = 'me' and `created_at` >= '2017-12-21 15:16:38';
```

Query time 0.001 instead of 0.7.

**Comment by cydrobolt** [comment]
Sorry for the late reply.

Thank you for your contribution! Merged both PRs.
