### ISSUE TITLE
Feature request: Button or ui element to auto-copy short URL from links list / admin page

### ISSUE THREAD

**Issue by ricopags** [cydrobolt/polr#409]
Basically like goo.gl does it:

![image](https://user-images.githubusercontent.com/1474765/35663452-88d005b8-06da-11e8-8192-4e71157d4df5.png)

This would save a lot of time. If not the usability of auto-copy, at least a setting to enable showing the full url instead of just the tail end.

If this is trivially easy and already something I should know how to do, I apologize :D Happy to learn

**Comment by DT27** [comment]
#414

**Comment by ricopags** [comment]
Hi I don't know how to tell if this request I filed was correct, I see #414 has "remove role form session when user logout" approved but "add 'copy to clipboard' button" isn't approved/integrated/pulled? Is that right?

Thanks to @DT27 for helping get this done, and @cydrobolt for the wonderful project! I'm sorry for my github ignorance if this is a bad place to put this

**Comment by ricopags** [comment]
@cydrobolt I plan on using the API with Wordpress but the plugin doesn't currently work. Is the plugin a separate github project or would filing an issue here be ok?

**Comment by overint** [comment]
I'm going to close this issue since #414 has been merged.

Which plugin are you referring to?
