### ISSUE TITLE
http exception in application.php

### ISSUE THREAD

**Issue by SajjadSayyadi** [cydrobolt/polr#410]
hi ,

I Have This problem in Last Setup

<img src="https://user-images.githubusercontent.com/35324757/35611505-776134ec-067a-11e8-93ad-c43cce76e19f.jpg">

**Comment by MichSimi** [comment]
+1

**Comment by cydrobolt** [comment]
You need to provide more details for us to help you. What are the instructions to reproduce this issue? Have you tried reinstalling your instance? Have you tried using a different browser? What kind of server are you using to serve Polr?

**Comment by SajjadSayyadi** [comment]
Hello
Yes, I've installed it several times
But the problem is not solved
Installing it is very complicated and difficult
Please give me your email address so I can send you login details
I'm really tired

**Comment by MichSimi** [comment]
check where the .env file is written in line 189 -> "app/Http/Controllers/SetupController.php"
$handle = fopen('../.env', 'w');
i solved this error changing the path to '../polr/.env'

**Comment by SajjadSayyadi** [comment]
😞 Sorry not resolved
Give me an email address to give you access to the host
Maybe I'm wrong

**Comment by SajjadSayyadi** [comment]
please send me an email

Sajjadpb@ymail.com

**Comment by SajjadSayyadi** [comment]
Hello
I finally installed it with the help of Michelle
But the current problem ,setup is not complete the database
Please give me a database file to import it

my website address is  3bc.ir

**Comment by overint** [comment]
@SajjadSayyadi 
You can just remove the `.env` file, and copy the `.env.setup` file to `.env`, which will restart the install process.
