### ISSUE TITLE
Missing links responds with HTTP Status 200 instead of 404

### ISSUE THREAD

**Issue by sc0rp10** [cydrobolt/polr#413]
## Expected Behavior
Missing links should responds with 404 HTTP status.

## Current Behavior
If i set `SETTING_REDIRECT_404=false` and visit some nonexistent url like http://demo.polr.me/im_not_found I got page that says '404 This page could not be found.' but server returned HTTP status 200.
This is incorrect behavior tha

## Possible Solution
Change https://github.com/cydrobolt/polr/blob/master/app/Exceptions/Handler.php#L54 to the following code:
```php
return response(view('errors.404'), 404);
```

**Comment by cydrobolt** [comment]
Thanks for pointing this out! Would you be interested in sending a pull request to fix this issue?
