### ISSUE TITLE
URLs aren't sanitised when creating/updating links

### ISSUE THREAD

**Issue by spammy23** [cydrobolt/polr#419]
## Expected Behavior
When displaying redirects, URLs should be sanitised

## Current Behavior
URLs aren't sanitised when being shown to the user

## Steps to Reproduce
1. Create redirect with url `https://example.org?x="<i>italic"`
2. Open link management page
<img src="https://i.imgur.com/8AT3vV1.png"/>

The same can be done to execute some JS by entering `https://example.org?x="/><script>alert(/xss/)</script>"`

## Your Environment
* Version or latest commit hash (`git rev-parse HEAD`): b80e422275530234ed9d4d767484a24567f91565
* Environment name and version  Firefox 59.0a1, Polr 2.2, PHP 7.2.2

**Comment by spammy23** [comment]
Closed by #420, commit df4688b2b07118da2530cb010c4a1728246aaf29

**Comment by cydrobolt** [comment]
I was able to test this bug locally; it looks like URLs are passed through the URL validator, but the long URLs can still be used as attack vectors for XSS because inputs like `https://example.org?x="<i>italic"` are still valid URLs.

Merged #420

**Comment by spammy23** [comment]
I feel that it's a valid URL but it shouldn't be parsed as HTML on the client
