### ISSUE TITLE
Request multiple links via API to reduce calls

### ISSUE THREAD

**Issue by enkota** [cydrobolt/polr#425]
Hey!

I am using the API to pull in data about that particular link. However, on one page of my app I would like to display data for multiple links. At the moment I've only been able to figure out how to request one (multiple times). Is there a way to output an array of API link data via the endpoints?

Thanks,
Scott

**Comment by iurisilvio** [comment]
I want that too. A bulk url shortener can improve a lot the performance. I generate ~100k links/day. It is 100k calls with some latency. If each call have a 0.1s latency + overhead, it is ~2h useless waiting.

**Comment by iurisilvio** [comment]
I don't have much Laravel / PHP experience, but let me know if you need any feedback about your solution.

**Comment by overint** [comment]
Also happy to help out if required.

**Comment by cydrobolt** [comment]
Implemented the `shorten_bulk` endpoint in #443. Updated documentation is available at https://docs.polrproject.org/en/latest/developer-guide/api/

**Comment by iurisilvio** [comment]
Great! I upgraded my polr deploy and will integrate the shorten_bulk ASAP to give you some feedback.

**Comment by enkota** [comment]
Thanks @cydrobolt sorry for the delay! Will check this out today.
