### ISSUE TITLE
upgrade from v2.11 has damaged site functionality

### ISSUE THREAD

**Issue by fsantiago07044** [cydrobolt/polr#433]
i was running v2.11 and followed the site upgrade instructions, starting with git pull. this was done today. 

my site runs on nginx 1.13.10 / centos 7.4 / php 7.0.29 / mariadb 10.2.14

My browser is Chrome Version 65.0.3325.181 (Official Build) (64-bit)

when i updated, i received commit b29c5d51a92d44a712f300dd9c3e13e0a0945628

now, when i log in and select dashboard from the menu, i get the basic list of admin links such as:

Home
Links
Settings
Admin

but clicking on any menu / link produces nothing.

my chrome browser console reports:

angular.min.js:118 ReferenceError: Handlebars is not defined
    at b.$scope.init (AdminCtrl.js:288)
    at Object.<anonymous> (AdminCtrl.js:307)
    at Object.invoke (angular.min.js:41)
    at S.instance (angular.min.js:89)
    at p (angular.min.js:65)
    at g (angular.min.js:58)
    at g (angular.min.js:58)
    at g (angular.min.js:58)
    at g (angular.min.js:58)
    at g (angular.min.js:58)

what happened? Thanks. also, my site is not public and requires login.

**Comment by fsantiago07044** [comment]
i should add that it does still work though. existing links work and i am able to create new ones and they function fine as well. i just can't access any dashboard or settings / admin panels.

**Comment by cydrobolt** [comment]
Did you encounter any merge conflicts during the upgrade process? Have you tried clearing your browser cache and trying again?

**Comment by fsantiago07044** [comment]
On April 2, 2018 11:55:46 AM EDT, Chaoyi Zha <notifications@github.com> wrote:
>Did you encounter any merge conflicts during the upgrade process? Have
>you tried clearing your browser cache and trying again? 

You're right. It was my cache. Thanks and sorry for wasting anyone's time. It works fine. 
--

Thanks,

Fabian S.

OpenPGP: 3C3FA072ACCB7AC5DB0F723455502B0EEB9070FC
