### ISSUE TITLE
Can't run setup

### ISSUE THREAD

**Issue by captainwasabi** [cydrobolt/polr#436]
## Expected Behavior

can run setup

## Current Behavior

from error.log...

PHP Fatal error:  require_once(): Failed opening required '/var/www/polr/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/polr/bootstrap/app.php on line 3

## Steps to Reproduce (for bugs)

1. follow installation instructions from documentation on Ubuntu 16.04

**Comment by overint** [comment]
You did not run composer install.

**Comment by captainwasabi** [comment]
Correct, that fixed it.  Then I recommend the following change to the installation document:

Instead of "Downloading the Source Code" say "Download the Source Code"
Instead of "Installing using Composer" say "Install using Composer"

Looking at it in hind sight I understand, but not being a web dev guy I did not know what composer was and when I read that I thought "I'm installing using the source code so I don't need to install using composer." Not realizing that composer is HOW you install using the source code.

Anyway, YMMV,.  But Thanks for the help and thanks even more for a great project!

**Comment by LazosPlaying** [comment]
same thing happened here, even though I'm more like a Junior web dev, but I just skipped it (silly me :/ ) so yeah.. please point that out for others. Also @captainwasabi just close the issue 😋

**Comment by captainwasabi** [comment]
Closed
