### ISSUE TITLE
LinkHelper::longLinkExists(...) performs expensive lookup over non-indexed columns

### ISSUE THREAD

**Issue by Jonnx** [cydrobolt/polr#438]
Scenario: You are using polr to programmatically create custom links from another application. You now have ~2+ million rows in the links table. Inserting new links takes a massive amount of time and the database CPU is sitting at 100%.

## Expected Behavior
Link insertion should be fast and not cap out database CPU.

## Current Behavior
Link insertion is slow and not caps out database CPU.

## Steps to Reproduce (for bugs)
1. generate 2 million links
2. but polr under load of shortening about 10 links / second

## Context
I tried to shorten many links and it didn't allow it

## Your Environment
Load Balanced Docker, with PHP 7.0

## Issue
Following Implementation: ```LinkHelper::longLinkExists```

```
$link_base = Link::longUrl($long_url)
            ->where('is_custom', 0)
            ->where('secret_key', '');

        if (is_null($username)) {
            // Search for links without a creator only
            $link = $link_base->where('creator', '')->first();
        } else if (($username !== false)) {
            // Search for links created by $username only
            $link = $link_base->where('creator', $username)->first();
        } else {
            // Search for links created by any user
            $link = $link_base->first();
        }
```

none of those columns are indexed

**Comment by cydrobolt** [comment]
What version of Polr are you running? What's the latest commit hash of the code you're running? 

`Link: :longUrl` performs a lookup using the link's crc32 hash, which is indexed.

**Comment by Jonnx** [comment]
@cydrobolt that would explain it, the version we are on does not due that. but i did find a second problem after temporarily disabling the ```LinkHelper::longLinkExists``` check. 

After that a second slow query showed up:
```
select count(*) as aggregate from links where is_api = ? and creator = ? and created_at > ?
```

which i assume is the rate limiting check, even though the keys have a rate limit of -1. so my 2 suggestions would be

1) do not calculate rate limit when it is set to -1
2) performance issue still exists for normal users so adding a compound index on ```links.is_api```, ```links.creator```, and ```link.created_at``` to resolve the issue (this did the trick for us)

**Comment by cydrobolt** [comment]
The API rate limit check's performance issues are also fixed in master.

**Comment by Jonnx** [comment]
perfect then i am gonna close this
