### ISSUE TITLE
Switching local instance to Elastic Beanstalk - Receiving 'failed to open stream: Permission denied'

### ISSUE THREAD

**Issue by seantcanavan** [cydrobolt/polr#446]
I've copied my `.env` file and project directory structure from a working local installation to Elastic Beanstalk. I'm using the [deployment script](https://github.com/codeship/scripts/blob/master/deployments/elastic_beanstalk.sh) defined by [CodeShip](http://codeship.com/) which zips up the polr directory and then deploys directly via the Elastic Beanstalk CLI to AWS. I've temporarily modified the `.env` file to `DEBUGGING=true`.

## Expected Behavior
When I copy the URL of the beanstalk Apache / PHP web server instance and browse to it I expect there to be no errors.

## Current Behavior
When I visit the URL of the BeanStalk instance provided by AWS  I receive [two](https://imgur.com/X1jIiVv) [errors](https://imgur.com/Y2Mm63Y) on the same page. 

## Steps to Reproduce (for bugs)
1. Deploy Polr locally and finish configuring for MySql / MariaDB - verify everything works
2. Create a new [Amazon RDS MariaDB](https://console.aws.amazon.com/rds/home?region=us-east-1) instance and update `.env` with the new connection string and username / password. Verify those credentials work on local via `mariadb -h {rdsurl} -u {rdsuserlogin} -p` and verify that `polr` database exists via `use polr`.
3. zip up working project directory with updated `.env` configured for AWS RDS access
4. deploy to elastic beanstalk with PHP 7.1 running on 64bit Amazon Linux/2.6.6 (easiest way to do this is via direct upload and deploy via [AWS web console](https://console.aws.amazon.com/elasticbeanstalk/home?region=us-east-1) just to reproduce)
5. visit {assignedbeanstalkurl}/setup

## Context
Working on launching a fully hosted Polr instance in the cloud!

## Your Environment
* Version or latest commit hash (`git rev-parse HEAD`):
Unsure - git versioning was removed. Probably version 2.0+ of Polr however.

* Environment name and version (e.g. Chrome 39, PHP 7.0, etc):
PHP 7.2 (via Elastic Beanstalk), Amazon RDS running MariaDB 10.2.12, Chrome Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by seantcanavan** [comment]
I realize there's a good chance this might be an AWS configuration issue but it's got be stumped for quite a while now so I thought I'd run it by you guys since the documentation has no mention of AWS hosting and there's only a single google result for "polr elastic beanstalk" which doesn't provide a ton of guidance!

Any thoughts, ideas, or insight here would be invaluable.

**Comment by overint** [comment]
That file look like a hash, so a view cache or session file?
I don't think anything is written in the root (apart from setup, but you can do that manually).

**Comment by seantcanavan** [comment]
Ah you've helped me immensely @overint. The issue is related to Elastic Beanstalk not having access to create folders at runtime - only files. This is based off the default permissions that Beanstalk runs your web app with.

The core of the issue is the required folders in the Polr source code that contain `.gitignore` files. Because they aren't committed to source they aren't zipped up and deployed to EBS. 

Because they aren't zipped up to EBS they don't exist when deployed. And the EBS deployment doesn't have appropriate permissions to create all the folders that weren't pushed as part of the code deploy.

The fix is to remove all the .gitignore files from the empty sub-directories. I'm no bash expert by any means but here's a decent attempt:

- `git clone polr`
- `cd polr`
- `mv .gitignore ../` 
- `find . -type f -name ".gitignore" -delete`
- `mv ../.gitignore ./`

**Comment by seantcanavan** [comment]
Getting a new error now `PDOException in Connector.php line 55:
SQLSTATE[HY000] [2002] Connection timed out` but I believe this should be able to be solved on the Amazon side. Thanks again for all the help!
