### ISSUE TITLE
Feature request: phpinfo

### ISSUE THREAD

**Issue by LoZio** [cydrobolt/polr#447]
Add a page (in the authenticated section) with phpInfo() and maybe some details of the configuration: db host, session storage, ...

## Expected Behavior
A link to a page with that information, may be in the actual about page

## Current Behavior
--
## Context
This solves the problem of checking the actual PHP configuration, modules, host where the request is going. Useful in multiserver deployment.
Currently I'm evaluating using php-fpm instead of mod_apache and to get this info I added a phpinfo file here and there to test.

## Your Environment
2.2.0

**Comment by cydrobolt** [comment]
This is another feature that could easily be implemented on your own instance, but that doesn't belong in Polr.

If you'd like to expose a page with `phpinfo`, it's very easy for you to add this information to `/about` or `/admin`. However, I don't think this belongs in Polr. Exposing this type of debug information is out of the scope of our project and it is up to the individual user to determine if they'd like to expose this type of information.
