### ISSUE TITLE
Feature request: "I'm alive" page

### ISSUE THREAD

**Issue by LoZio** [cydrobolt/polr#448]
Add an url to check the service availability

## Expected Behavior
An url like "/alive?mykey=123456" that checks all the needed dependencies giving back, one per line, the results, like:
DB connection: ok
Redis connection: ok
Free disk space: 1.8G ok
...

A failed check results in "ko" instead of "ok", so you can trigger an aler if a "ko" is present in the page.

## Context
You define the key in the config, so that no other people can use that url.
You can setup an external poller to check this URL to be sure the server is up.
Currently if you check the Login page you only know php is working (not bad) but if you loose the database you seem to be up but you're not.
Also checking redis or any other dependency can be done here.
Minimum space tro trikker ok/ko should be a variable.

## Your Environment
2.2.0

**Comment by overint** [comment]
I don't think is something we would be adding into the master, it's something you could easily add if you needed.
@cydrobolt

**Comment by LoZio** [comment]
I can add it yes, and actually did somehow (bare php). But this prevents pulling the code without fiddling with added files.
I don't know laravel so I can't integrate code with the project in an easy and clean way.
As of today you cannot be sure the service is up, you can check login or get stats but no single/simple to configure for external pollers/way to know if it is all running smoothly and this is a requirement for production environments.

**Comment by cydrobolt** [comment]
I agree with @overint. I think this is something that can be easily implemented on your own instance if you'd like. I don't think it makes sense for us to implement this type of feature, as each instance has its own structure and it would be difficult to build a "status page" that understands the specifics of every Polr instance (i.e, how the database is set up, how the site is served, etc).
