### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by Nevercold** [cydrobolt/polr#449]
Hello,  Where can I change settings for the mail server? sorry if this is wrong here is the first time on github

**Comment by Nevercold** [comment]
I found it. But the Mailserver attitudes do not go although they are exactly in the forum where it goes.

**Comment by overint** [comment]
I'm not sure what you mean?

**Comment by Nevercold** [comment]
Here comes: "stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed" at password reset or when registering.

**Comment by Nevercold** [comment]
@overint

**Comment by cydrobolt** [comment]
You can edit your `.env` file to change Polr's SMTP configuration.

**Comment by overint** [comment]
> stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

Sounds like there are some issues with your PHP setup, likely not related to Polr.

**Comment by Nevercold** [comment]
How can I make self-signed certificates with the mail server are allowed?

**Comment by Nevercold** [comment]
New Error https://hastebin.com/otutetihex.php :/

**Comment by Nevercold** [comment]
Its works now.
 #Closed

**Comment by Nevercold** [comment]
Next Problem: Where can I translate the page xdd @overint @cydrobolt

**Comment by overint** [comment]
There is currently not translation support, however there is a WIP PR here:
https://github.com/cydrobolt/polr/pull/423

**Comment by Nevercold** [comment]
Can one adjust that the link instead of domain.de/1 automatically for example domain.de/d4564 is?
