### ISSUE TITLE
SETTING_PUBLIC_INTERFACE=false does not prevent creating links using API

### ISSUE THREAD

**Issue by ameshkov** [cydrobolt/polr#469]
The only thing controlled by `SETTING_PUBLIC_INTERFACE` is the index page. This does not actually prevent guests from creating shortlinks.

## Expected Behavior
If `SETTING_PUBLIC_INTERFACE` is set to false, the API must respond with 403 error when an unauthorized user attempts to create a short link.

**Comment by cydrobolt** [comment]
Users are prevented from creating links if `SETTING_SHORTEN_PERMISSION` is set to true (i.e "user must be logged in to create links"). Although it does make sense to prevent logged out users from creating links if the public interface is hidden, there exists an explicit setting that already provides this functionality, so it may be unnecessary and confusing to associate `SETTING_PUBLIC_INTERFACE` with `SETTING_SHORTEN_PERMISSION`

**Comment by ameshkov** [comment]
Got it, thank you!
