### ISSUE TITLE
Edit Front-Page?

### ISSUE THREAD

**Issue by MrUnknownDE** [cydrobolt/polr#473]
Hello,

I apologize for my english.

But I have a question. Is it possible to change the public interface, so create a new page or change something.

Best regards
Johannes K. | MrUnknownDE

**Comment by cydrobolt** [comment]
Polr is an open-source project; you can directly edit the page you would like to change. For example, you can edit https://github.com/cydrobolt/polr/blob/master/app/Http/Controllers/IndexController.php or https://github.com/cydrobolt/polr/blob/master/resources/views/index.blade.php to update the front page.
