### ISSUE TITLE
Serving polr from localhost/polr-app-name/public results in 404 for javascript/css assets

### ISSUE THREAD

**Issue by ratatatKE** [cydrobolt/polr#475]
## Expected Behavior
After installing polr, I should be able to go to polr-project-name/public and interact with polr experiencing the rich html and css formatted pages.

## Current Behavior
Going to polr-project-name/public folder results in unformatted pages. Inspecting the console shows that css and javascript assets are returning 404 not found. However, using `php artisan serve` results in expected behaviour above. 

## Possible Solution
I definitely cannot run `php artisan serve` for production even on a VPS (*it's just complicated), current implementation of polr should be able to serve the application from the polr-project-name/public folder. This way, I can just add a virtualhost to the public folder and everything proceeds as normal.

## My Environment
I am working on XAMPP for windows with polr-project under localhost. I will however move it to an ubuntu installation for production purposes.

**Comment by overint** [comment]
This would be to a misconfigured web server.
Can you post your apache config file(s)?

**Comment by ratatatKE** [comment]
Hi @overint , I am running other Laravel based websites (at least six) with the same Apache/XAMPP web server and they work fine, since it's not a new apache server am spinning up, am sure the configuration is fine since I use Vanilla XAMPP with php 7.0.31. 

Please see below my .htaccess configuration for the polr project if it may help troubeshoot. This .hatccess file is in the \public directory.


<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>

**Comment by ratatatKE** [comment]
It's the vanilla polr .htaccess that came from the github repository. Nothing has been changed.

**Comment by ratatatKE** [comment]
I understand this behaviour having interacted with other projects i.e. Laravel Lumen. 

If you try to serve it in the folder in localhost in your development machine.. It will fail and show those 404 errors for files.

However once you push the project to production _(And am assuming that we are all using Virtual Private Servers)_ pointing your virtual host to the public folder, this project should run perfectly okay as though you were using `php artisan serve` on local development.

I haven't tested it, have just connected the dots.
