### ISSUE TITLE
Can't change admin password

### ISSUE THREAD

**Issue by filhocf** [cydrobolt/polr#478]
I did a installation and forgot the admin password. So, I tried to change directly in the mysql.

I tried some cases like:

- update users set password="mypass" where id=1
- update users set password=md5('mypass') where id=1
- update users set password=password('mypass') where id=1

and in all cases, I can't log in.

Some tip or suggestion?

Since now, thanks in advance.

**Comment by steveroot** [comment]
I'm sure there's a better answer, but if you're in a hurry maybe you can create a new installation (eg on a virtual machine) then copy the hashed password from that install. Though I cold see that might not work if the password is generated with values unique to each installation.

**Comment by cydrobolt** [comment]
Try a bcrypt hasher: https://www.browserling.com/tools/bcrypt

**Comment by filhocf** [comment]
\o/

Thank you, @cydrobolt ! Is exactly this encode.

**Comment by overint** [comment]
I wouldn't suggest inputting you password into a website.
I would just create a quick PHP script that uses the `password_hash` function to create a hash so it's not exposed over the internet.

**Comment by zar69** [comment]
Hello,
To reset my password I've used the build in route **/reset_password/{username}/{recovery_key}** and got the values from the query SELECT username, recovery_key FROM users;
Best regards.
