### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by filhocf** [cydrobolt/polr#480]
I want to translate your tool for Brazilian portuguese (pt-BR), but taking a look, I see that all strings are hardcoded. 

Do you have some intention to give support for translations, @cydrobolt ?

**Comment by klezm** [comment]
I'm working on implementing a i18n solution making use of one of the many translation services like transifex, lingohub, phraseapp etc.
once i've set it up, you can easily add a translation. i expect it to be ready in the next weeks.

**Comment by filhocf** [comment]
![image](https://user-images.githubusercontent.com/952596/46498381-a9875880-c7f3-11e8-9eae-d372d26c5bab.png)

**Comment by klezm** [comment]
I just asked the guys from Phraseapp and they told me I have to add you via your email adress.

**Comment by filhocf** [comment]
@klezm , can you add me? filhocf @ gmail.com .
