### ISSUE TITLE
What are the difference between Public and Secret link?

### ISSUE THREAD

**Issue by RoldanLT** [cydrobolt/polr#486]
What does secret link differ from public?

Thanks!

**Comment by overint** [comment]
Can you clarify your question with screenshot and such please

**Comment by RoldanLT** [comment]
This
**
![image](https://user-images.githubusercontent.com/6730496/46904676-cbcb5580-cf1a-11e8-83da-3b83614d7055.png)
**

**Comment by overint** [comment]
I believe that's when you are using incrementing endings, it adds some radom data to the end of the url so people can't guess it.

**Comment by RoldanLT** [comment]
Okay Thanks!.

**Comment by hermann-san** [comment]
I think it would be good to explain the difference on the website, maybe with "mouse over" text

**Comment by CreativeNotice** [comment]
Yep, it would be beneficial. This should be clarified in the documentation too. I took a few minutes of Googling around to find this thread.
