### ISSUE TITLE
Error: The Link Appears To Be Already Shortened

### ISSUE THREAD

**Issue by julianengel** [cydrobolt/polr#506]
## Expected Behavior
You enter the URL, click shorten and it should give you the shortened link. 

## Current Behavior
A red error message appears in the top right corner, saying the link I am trying to shorten already appears to be shortened. (tried many links from youtube, facebook, google, non work locally but they do in the demo)

## Possible Solution
Unaware what could be causing this. Tried on 3 different droplets. 

## Steps to Reproduce (for bugs)
Just followed installation instructions, once tried using the docker image. 

1. Official Install
2. Log In
3. Try And Shorten Link

## Your Environment

* Version or latest commit hash (`git rev-parse HEAD`):
* Environment name and version (e.g. Chrome 39, PHP 7.0, etc):
Chrome: Latest
Safari: Latest
Server: Ubuntu 18.4
Server2: Linux Alpine Latest

**Comment by trudslev** [comment]
Mine works just fine. What link are you trying to shorten?

**Comment by julianengel** [comment]
Hey... Yes, it was an issue with the way I was installing it I think. I deleted everything and followed those instructions https://github.com/mackmoe/polr_pronto and it works now!

Thanks for your help!
