### ISSUE TITLE
option to generate https links instead of http one needed

### ISSUE THREAD

**Issue by harcesz** [cydrobolt/polr#515]
## Expected Behavior

If the Polr install has https enabled, the generated links should start with https and not http. 

## Current Behavior

Even if Polr is accessed via https and the target address is https, polr gives a http short address.

## Possible Solution

Adding a setting for admins to choose http or https link generation. 

## Steps to Reproduce (for bugs)

1. input any address
2. ??? 
3. not encrypt!

## Context

We use Polr for an advocacy organization, using shortened links on social media. Users click on them, to get to campaign pages, which themselves are encrypted, so apart for domain, a third party on the same network would not know, what particular campaigns a user might be engaging with. But clicking a shortened link currently causes a possible spill of sensitive information - particular campaign, for say abortion or LGBT rights, as they are redirected back to the encrypted site. This can be an actual threat for some of our users. 
Currently our campaigners need to manually edit that, and in a fast paced work environment, that does not always happen, as we recently discovered. Fixing it software-side would solve the issue. <3 

## Your Environment

Polr 2.2.0

**Comment by hbh7** [comment]
I believe in the setup, I saw an option to use https instead

**Comment by zubinraj** [comment]
I was able to use the below environment variable/setting to make it https. The domain also has to be https.
APP_PROTOCOL=https://

**Comment by harcesz** [comment]
indeed, this can be fixed in web/env thanks
