### ISSUE TITLE
PHP7.4: ErrorException: Trying to access array offset on value of type int [Solution]

### ISSUE THREAD

**Issue by romtamk** [cydrobolt/polr#554]
I'm opening an issue here in hopes that some people might see it, so that they can easily know how to fix.

## Current Behavior

When we run /setup with PHP7.4 and click **Install**, an error is thrown. When we turn on debug, we see:
`ErrorException: Trying to access array offset on value of type int`

## Possible Solution

Implement the fix from [this commit](https://github.com/symfony/symfony/pull/32806/commits/5f451e6f7074976aae60a65ba144fff684b7b48c), located at `/var/www/polr/vendor/symfony/console/Input/ArrayInput.php`

## Your Environment

* Version or latest commit hash (`git rev-parse HEAD`): f9622d733b554154a39e9a716c5c134da35acba
* Environment name and version (e.g. Chrome 39, PHP 7.0, etc): PHP 7.4

**Comment by ngunyimacharia** [comment]
Is there any way this can be permanently solved? Bump up the dependancies?
