### ISSUE TITLE
Missing vendor files

### ISSUE THREAD

**Issue by littleluce** [cydrobolt/polr#564]
I'm getting the following error upon setup if the debug is turned on. It seems like some package is missing, but I'm not sure where to install it from?
```
include(/polr/vendor/composer/../doctrine/dbal/lib/Doctrine/DBAL/VersionAwarePlatformDriver.php): failed to open stream: No such file or directory
```

**Comment by ddrght12345** [comment]
You need to run `composer install` in the root of the polr directory

**Comment by eluce2** [comment]
I'm installing this on a shared server so I don't have access to run composer. Shouldn't all the files be included in the release that I downloaded?

**Comment by ddrght12345** [comment]
Composer is a package and dependency management tool for PHP.
The idea behind it is you upload only 1st party code (what *you* write) and let the tool do dependency resolution for you.

That said, you can download this code locally (or somewhere you have access to CLI) and run `composer install` there. It will download all the dependant files which you can then upload to your host.

**Comment by cydrobolt** [comment]
@ddrght12345 is right, you can run `composer install` locally then upload the entire folder to your shared server.
