### ISSUE TITLE
Version still shows 2.2.0 instead of 2.3.0

### ISSUE THREAD

**Issue by svrnwnsch** [cydrobolt/polr#585]
## Expected Behavior

Show the current released version in `.env.setup` and `util/version.py` and potential other places where version is used.

## Current Behavior

The mentioned files still show version 2.2.0

## Your Environment

* Version or latest commit hash (`git rev-parse HEAD`): master b198170

**Comment by cydrobolt** [comment]
Fixed, thanks!
