### ISSUE TITLE
How to configure sqlite?

### ISSUE THREAD

**Issue by Pixdigit** [cydrobolt/polr#593]
## Expected Behavior

Presence of a toggle switch in the setup to use sqlite instead of mysql.

## Current Behavior

The installation docs say, one could use polr with sqlite. Though in the interactive installer one could only configure a MySQL server.

## Possible Solution

Add documentation how to configure sqlite in .env file or even add switch in setup ui.

## Steps to Reproduce (for bugs)

1. Follow installation instructions
2. Open setup page

## Context

I only use this personally and don't mind the side-effects of using sqlite.

## Your Environment

* Version or latest commit hash (`git rev-parse HEAD`):
stable (2.3.0)
* Environment name and version (e.g. Chrome 39, PHP 7.0, etc):
Ubuntu 18.04 LTS with PHP 7.4

**Comment by ahangarha** [comment]
As far as I see, Polr works well with sqlite though as per documentation it is not recommended. To use sqlite, you should manually edit `.env` file and set `DB_CONNECTION=sqlite`. Then manually make an empty file `database/database.sqlite`. Just keep in mind that you need to configure other items manually in `.env`.
