### ISSUE TITLE
I can not install

### ISSUE THREAD

**Issue by jethcrew** [Cydrobolt/polr#64]
no puedo instalar el script, tiene base de datos ? donde se configura la base de datos, el host y lo demas ?

**Comment by jethcrew** [comment]
I can not install the script, database? where the database, the host and the rest is configured?

**Comment by Cydrobolt** [comment]
Hello Jethcrew!

Can you elaborate a little bit? You need MySQL, and you have to create a database for Polr through commandline or PHPMyAdmin.
After you have your MySQL database configured, you will need to place Polr in your web server's directory, for example, `/var/www`. Once that is done, you can navigate to your website, and Polr should redirect your browser to the installation script, which is `/http://site.com/path/to/polr/setup.php`

Let me know if you have any more issues. IRC is usually a better form of communication if you need help setting up Polr. (#polr on irc.freenode.net) http://webchat.freenode.net/?channels=#polr

**Comment by 00875** [comment]
I have the same problem. I connot login into my account after install.
nginx/1.7.9
PHP-fpm/5.5.9
MySQL/5.6.21
MCrypt, MySQLi, MySQLnd installed

**Comment by Cydrobolt** [comment]
@00875
If you are getting a blank screen, you probably did not set up your database correctly. Delete your `config.php` and reinstall. (Make sure MySQL is running)

If that does not solve the issue, I suggest you enable debugging by setting `$debug` to 1 in `lib-core.php`

Let me know what error messages you receive with debugging enabled.

**Comment by karibuTW** [comment]
Works great from my side (Lamp server)

I've done a short tutorial to explain how to install it.
http://freedif.org/polr-fancy-and-modern-url-shortener/

**Comment by Cydrobolt** [comment]
@karibuTW Cool, awesome!

**Comment by Cydrobolt** [comment]
Closing due to lack of response from ticket creator.
