### ISSUE TITLE
Use a templating engine (instead of markup in PHP code)

### ISSUE THREAD

**Issue by fwilson42** [cydrobolt/polr#65]
We should eventually use a templating engine for markup.

## Reasons
- Easier editing
- Easier theming
- Maintainability

## Possible solutions
- [**Twig**](http://twig.sensiolabs.org/): PHP5, good docs, variable escaping
- ~~[**Blade**](http://laravel.com/docs/4.2/templates): what Laravel uses~~
- ~~[**Smarty**](http://www.smarty.net/): well, it works~~
- ~~**PHP itself**: at least let's separate templates from logic~~

## What needs to be done
- [ ] Load/autoload twig where needed
- [ ] Convert and render templates
- [ ] Start development on themes!

**Comment by Cydrobolt** [comment]
:+1: 
Switching to a templating engine is definitely desired; more complex and varying themes require many differences in the way pages are rendered.

Looking over Twig's documentation, it seems like a fitting template system.

**Comment by tejasmanohar** [comment]
:+1: for Twig

**Comment by cydrobolt** [comment]
Blade implemented in 2.x
