### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by ketheriel** [Cydrobolt/polr#69]
Hi,

I've setup polr for testing (if we move on, it will remain on our intranet); When I try to go to the admin dashboard, it takes too long and fails to connect to: https://raw.githubusercontent.com/Cydrobolt/polr/notices/anotices

This is most likely because we're behind a proxy machine. The server has proxy properly configured in /etc/profile.d. Does POLR support proxy? Where do I configure the proxy?

NM

**Comment by Cydrobolt** [comment]
Hi @ketheriel

If the PHP server cannot reach the update server, you can simply disable the check in `admin/index.php`

You can try routing it somehow, but your best bet is just to remove the check. We're doing a massive rewrite for 2.0, so the current updater won't be of much use.

Replace lines 91 to 109 with the contents of line 95
(admin/index.php)

 https://github.com/Cydrobolt/polr/blob/master/admin/index.php#L91

**Comment by ketheriel** [comment]
I did... it's working fine. I also noticed that the link to Dashboard and Settings is the same (so the contents). This is as expected right? Other than that, working fine :)

Thanks for your work!

**Comment by Cydrobolt** [comment]
Yup. The settings and dashboard links are expected to be the same for now,
until our huge update comes along :)
