### ISSUE TITLE
Config file for installation

### ISSUE THREAD

**Issue by ramon-villain** [Cydrobolt/polr#73]
How am I enable to install the app, if I have no parameters or template for config.php? I understand ignoring config.php in production, but this development branch should provide a example file, or am I missing something?

**Comment by Cydrobolt** [comment]
Hi Ramon,

The config file is generated by `setup.php`, there is no need to manually edit any files. After you place the package on your server, navigate to `setup.php` and follow the instructions.

**Comment by zwebmedia** [comment]
Hi there, may I ask is this information still current? I will open my own issue, but I am reviewing all the previous issues before doing so. I access /setup per the V2.2.0 instructions and I am getting a db error, so just wondering if I should be looking for setup.php, which I can't find. Thanks.

**Comment by overint** [comment]
No @zwebmedia 
The correct path is `/setup`.
