### ISSUE TITLE
Hash string instead of counting up?

### ISSUE THREAD

**Issue by furukama** [Cydrobolt/polr#76]
Is it possible to generate e.g. a 8 character hashstring instead of the numbers in the shortened URL? So that there would be polr.co/2ab376 instead of polr.co/1 and so on?

**Comment by Cydrobolt** [comment]
Yeah, that could possibly be implemented as an option -- are you interested in such a feature?

Currently, there is a "secret" URL option which creates URLs similar to the one you described, much harder to guess. Choose "link options" and it will appear.

**Comment by sckasturi** [comment]
side note: it's polr.me, not polr.co




–Srijay Kasturi
http://techfilmer.com

**Comment by Cydrobolt** [comment]
For instance, a secret URL for this issue is http://polr.me/1pj?X1jU
