### ISSUE TITLE
Support Dashes and Underscores in URI

### ISSUE THREAD

**Issue by michaelpawlak** [cydrobolt/polr#77]
Please allow for the use of dashes and underscores in the URIs for Polr. These are supported on all websites and should be allowed via your application.

**Comment by Cydrobolt** [comment]
Dashes and underscores should be supported in shortened URLs, however, they are not allowed in custom URL endings. Which type of URLs are you talking about, and can you provide an example?

**Comment by michaelpawlak** [comment]
Chaoyi,

I was attempting to use underscores in URIs, not the FQDN portion of the
URL. I believe this is what you are calling the URL endings. An example
listed below.

---

EXAMPLE

http://foo.bar.baz.qux => http://go.foo/bar-baz

OR

http://foo.bar.baz.qux => http://go.foo/bar_baz

---

If this is hardcoded somewhere in your code, could you point to where I
might find it, so I can modify it directly as a work around?

Also, what do you mean by "shortened URLs". Your application only appears
to be able to provide the above mentioned logic, provided in my example.
Unless of course I am missing something, which could very well be the case.
Thanks.

*Michael Pawlak*
CompTIA: A+, Linux+, Network+
MCTS: 70-680 Windows 7, 70-640 Active Directory, 70-642 Network
Infrastructure

Web Systems Administrator | Colovore LLC
E: mike@colovore.com
C: 408.316.2154
 <http://www.colovore.com>

**Comment by Cydrobolt** [comment]
I see. You are trying to use symbols in the "endings"
It is checked in `createurl.php`, at this line: https://github.com/Cydrobolt/polr/blob/master/createurl.php#L91

It only allows alphanumeric endings because unrestricted use of symbols could can cause issues. If you are interested in removing the restriction or writing a workaround, try line 91 in `createurl.php`

**Comment by michaelpawlak** [comment]
​Chaoyi,

Why not instead validate that the URL endings contain the all of the valid
URI characters? You could use some like the below listed code.

---

FROM:
if(!ctype_alnum($customurl)) {
    echo "<b>Symbols or spaces are not allowed in a customized URL -
alphanumeric only. <a href='index.php'>Try again</a></b>";
    die();
}

TO:
if (!preg_match('^[\pL\pN\-\._~:\/\?#\[\]@!\$&'\(\)\*\+,;=%]+$',
$customurl)) {
    echo "<b>Custom Link must be an RFC compliant URI. <a
href='index.php'>Try again</a></b>";
    die();
}​

---

​If you want, I can do a pull request and submit this?​

**Comment by goeroe** [comment]
Where is this handles in the new version? I would need to make - (hyphen) available in the endings

**Comment by goeroe** [comment]
I found it...

Changed:
``
static public function validateEnding($link_ending) {
        //$is_alphanum = ctype_alnum($link_ending);
        //return $is_alphanum;
        $is_valid_ending = preg_match('/^[a-zA-Z0-9-]+$/', $link_ending);
        return $is_valid_ending;
    }
``
in the AjaxController.php

**Comment by cydrobolt** [comment]
@goeroe hey! Thanks for taking a look at this. It looks like you found the right method. I could only find the method in `LinkHelper`, though. Did you mean `LinkHelper` or were you able to locate it in `AjaxController`?

https://github.com/cydrobolt/polr/blob/master/app/Helpers/LinkHelper.php#L71

**Comment by goeroe** [comment]
LinkHelper idd. I don't know why I said AjaxController... Updated previous post

**Comment by cydrobolt** [comment]
Gotcha. @goeroe could you submit a pull request with those changes?
