### ISSUE TITLE
Large number of shortened URLs in per page in the admin tab

### ISSUE THREAD

**Issue by umpc** [Cydrobolt/polr#84]
In the pagination in the admin tab, the number of shortened URLs returned on each page increases on a bell curve, and peaks at the middle numbered page.

Perhaps this could be fixed by setting a fixed number (like 10 or so) of returned URLs per page?

**Comment by Cydrobolt** [comment]
Hmm, this shouldn't be happening. Every page should be limited to 30 URLs each. Could you try counting them to see if there are in fact 30 on each page or if there is a bell curve? The URLs are word-wrapped, so longer links can create the impression that more links are on each page.

I'll double check when I get to my computer and see if a bell curve is actually forming. I encountered a similar issue when testing, but it was more if a linear curve than a bell curve, and I thought I fixed it (perhaps it came back).

**Comment by umpc** [comment]
I saw that the first page does always list 30 URLs, but that this goes up on the next page, which lists around 60 URLs.

The amount of URLs listed rises as the page number approaches the median and then falls as the page numbers approach the last page.

My last page isn't completely full of URLs, so my next to last page lists 37 URLs.

**Comment by Cydrobolt** [comment]
It should be fixed now :)
