### ISSUE TITLE
API Database

### ISSUE THREAD

**Issue by Lucianss** [Cydrobolt/polr#85]
Please add in the setup file the option to create API database, I get an error.
It says that the email thinghy cannot be duplicated this is the code that gives the error, what should I do?

                  `email` varchar(50) NOT NULL,
                  KEY `email` (`email`),

**Comment by Cydrobolt** [comment]
Hey @lucianss!
Thanks for trying Polr! Can you describe how the problem can be reproduced (step by step)?

Do you get this error when installing Polr, or when trying to add users to the API table?

**Comment by Lucianss** [comment]
It won't install it directly from setup.php, had to install it myself, to insert the table to the database.
I get the driver error, but I removed that part of code that gives the error so I could install it.
I also can't login Fatal error: Call to undefined method mysqli_stmt::get_result() in /home/u377305290/public_html/lib-auth.php on line 101
So, when I want to add it myself the problem is that the email part is duplicated and it won't let me upload it to the phpmyadmin, these 2 lines:

   `email` varchar(50) NOT NULL,
     KEY `email` (`email`),

Removed this line too so I can install it, that's it, but also please help me fix the login part, I can't access the dashboard..  Fatal error: Call to undefined method mysqli_stmt::get_result() in /home/u377305290/public_html/lib-auth.php on line 101 - handle-login.php
I removed this code so I could install it:

			if (!$mysqlnd) {
				echo "<br /><br /><p>Error: You don't seem to have the <code>MySQL native driver. </code>
				<br />You should install it and restart your server in order to use Polr properly. <br />
				On Ubuntu-based distros: <code>sudo apt-get install php5-mysqlnd</code><br />
				On Fedora-based distros: <code>sudo yum install php-mysqlnd</code>, or if you get errors, <code>sudo yum remove php-mysql && yum install php-mysqlnd</code><br />
				For most Windows computers, the native driver should come by default for PHP >= 5.4.
				<br />For more information, click <a href='http://php.net/manual/en/mysqlnd.install.php'>here</a></p>";
				die();
			}

When I want to registed a new account (handle-register.php) I get this: 

Fatal error: Call to undefined method mysqli_stmt::get_result() in /home/u377305290/public_html/lib-core.php on line 53

Also clicks won't update, when I go to the stats page..
For more informations please go to this link and check how it works, not that good tho..
https://sevo.cf/

**Comment by Cydrobolt** [comment]
@Lucianss Thanks for the information. It seems like the difficulties you are experiencing are due to your PHP or MySQL version, which is likely outdated. The `mysqli_stmt::get_result()` function which seems to be unavailable on your host should be included in recent versions of PHP and MySQL/MariaDB.

May I ask what host you are on, and what your PHP and MySQL versions are? 
`phpinfo();` might be helpful.

**Comment by Lucianss** [comment]
the host name is Hostinger http://hostinger.ro
PHP Version: 5.3
MySQL Version: 5.1.61

**Comment by Cydrobolt** [comment]
Hmm, yeah. It seems to be the lack of `mysqlnd` on your system, as the setup warning showed. Your host seems to offer PHP 5.4 -- could you possibly switch your website to PHP 5.4? As of version 5.4, `mysqlnd` became the default driver. That may help fix these issues.

More info: http://php.net/manual/en/mysqlnd.install.php

**Comment by Lucianss** [comment]
I switched to PHP 5.5 nothing changed.

**Comment by Cydrobolt** [comment]
Hmm. There is a temporary workaround you could try, but it might be easier to change hosts as the `mysqlnd` driver is rather prominently used in Polr. Is it possible for you to contact your host and ask them about the `mysqlnd` driver?

**Comment by Lucianss** [comment]
I sent a ticket, but it's low chance that they will enable it. Thanks!

**Comment by Lucianss** [comment]
Also this is the error I get when trying to login so I  can access the ucp - using xampp server (latest)


Notice: Undefined variable: wsn in C:\WS\htdocs\lib-core.php on line 20

Notice: Undefined variable: host in C:\WS\htdocs\lib-core.php on line 23

Notice: Undefined variable: user in C:\WS\htdocs\lib-core.php on line 23

Notice: Undefined variable: passwd in C:\WS\htdocs\lib-core.php on line 23

Notice: Undefined variable: db in C:\WS\htdocs\lib-core.php on line 23

**Comment by Cydrobolt** [comment]
You are getting that error because `config.php` was not located. Maybe you forgot to also bring that file over (or haven't set it up yet?)

**Comment by Lucianss** [comment]
Yes, I forgot that but when config.php is there..

Notice: Undefined variable: wsn in C:\WS\htdocs\lib-core.php on line 20

Notice: Undefined variable: host in C:\WS\htdocs\lib-core.php on line 23

Notice: Undefined variable: user in C:\WS\htdocs\lib-core.php on line 23

Notice: Undefined variable: passwd in C:\WS\htdocs\lib-core.php on line 23

Notice: Undefined variable: db in C:\WS\htdocs\lib-core.php on line 23

There seems to be a problem. Contact an administrator to report this issue.
Error:
No database selected

It says that the database is not selected

**Comment by Cydrobolt** [comment]
Are you sure you set it up correctly? You need to also have a MySQL server running locally, and you need to provide those correct credentials in set up :)

**Comment by Lucianss** [comment]
I'm sure I set it up corectly.. But it doesn't work.

**Comment by Cydrobolt** [comment]
Hmm. I'm not sure why it is not working. Can you paste the contents of your `config.php` file located on your local XAMPP server?
