### ISSUE TITLE
[Feature Suggestion] Add more location stats

### ISSUE THREAD

**Issue by Lucianss** [cydrobolt/polr#87]
I would like to see an map that shows the countries and where the click are from as well as their source (when you use the link on your website to show to show that website url).

What is the difference between Polr and PaaS? Whitch one is better?

**Comment by Cydrobolt** [comment]
Hi, thanks for the suggestion! While Polr strives to be lightweight and minimal in its design, that may be a good idea for a long-term bulkier option. 

As for Polr vs Polr-PaaS, Polr PaaS is a much more legacy version of Polr that is no longer updated and should not be used to host your own shortener, as it was essentially a past code dump from the customized code powering my own instance of Polr, http://polr.me

Polr PaaS used to be ahead of Polr SH (this project), but that is no longer the case and Polr PaaS is outdated and no longer updated.

**Comment by Schokobecher** [comment]
Another thing that I noticed:
Everyone can check the stats of a link, even if the Polr instance is using 

> $li_show_front = true;
> $li_index_redirect = '';
> $li_shorten_only = true;
> $regtype = "none";

Which makes it somewhat private.
Maybe another option to only let the creator of the link and admins see the stats?

**Comment by cydrobolt** [comment]
We would be down to add this in 2.0. 
@Schokobecher could you make a new issue for this?

**Comment by cydrobolt** [comment]
Implemented in #279
