### ISSUE TITLE
All shortened links beginning with the letter "t" in nginx result in a 404

### ISSUE THREAD

**Issue by umpc** [Cydrobolt/polr#88]
Just change location /t {} to location /t- {} in .nginx-config to have the request forward to where you intended, even though I understand that it is now for a historical function.

**Comment by Cydrobolt** [comment]
Hmm, can you show me where this is? Looking at this line: https://github.com/Cydrobolt/polr/blob/master/.nginx-config#L22, it seems like /t-{} is correct.

**Comment by Cydrobolt** [comment]
Nevermind, found it! Does this fix it?
