### ISSUE TITLE
config.php example needed

### ISSUE THREAD

**Issue by danielatik** [Cydrobolt/polr#92]
Hello!

I'm trying to install polr in a site with FTP access only because ssh is not available.

I would like to run setup.php but I've not mysqlnd installed on the server. For this reason I would like to know if I could run setup.php (using a config.php example) filling the database fields manually.

Any help will be welcome.

Thanks!! ; )

**Comment by Cydrobolt** [comment]
@danielatik unfortunately, `mysqlnd` is required for many functions beyond the setup script, such as the admin panel. You can opt to install Polr without `mysqlnd` (remove the MySQLnd check from the `setup.php` script, just delete the whole if statement), but you will be unable to use the admin panel.

**Comment by danielatik** [comment]
Thanks for your fast answer! I'll try first activating SSH into this server for access and install mysqlnd. Cheers! ; )

**Comment by danielatik** [comment]
I'm in! Finally I could activated SSH but now I cannot install MySQLnd.

I've RedHat 4.4.6-4 and try to install with "sudo yum install php55-mysqlnd" or "sudo yum install php-mysqlnd" but "No package php55-mysqlnd available."

I'm looking how to install it in this version of Linux :/

**Comment by Cydrobolt** [comment]
I think the package is `php5-mysqlnd`, not `php55-mysqlnd`. Have you tried that?

**Comment by danielatik** [comment]
Yes... the same message "No package php5-mysqlnd available." :(

**Comment by danielatik** [comment]
Well, the PHP version of this server is:  5.3.28

**Comment by umpc** [comment]
Hello. I happened to see this thread and decided to look for RHEL 4 packages for mysqlnd.

Here's what I've found. (I'm not familiar with rpm or else I'd list the install command as well.)

RedHat EL 4 	rpms.famillecollet.com/enterprise/4/remi/x86_64/php-mysqlnd-5.3.10-2.el4.remi.x86_64.rpm
RedHat EL 4 	rpms.famillecollet.com/enterprise/4/remi/i386/php-mysqlnd-5.3.10-2.el4.remi.i386.rpm

**Comment by Cydrobolt** [comment]
Ah yes. PHP 5.3 requires the inclusion of mysqlnd at compile time, if I recall correctly. However you should still be able to get it from an external repository (you found the repo, not sure if it is still up to date).

However, PHP 5.3 is 2 years old, and upgrading to a more recent version would be advisable.

**Comment by Cydrobolt** [comment]
```
wget http://rpms.famillecollet.com/enterprise/remi.repo -O /etc/yum.repos.d/remi.repo
yum --enablerepo=remi-test install php-mysqlnd
```
might be better than installing the RPM directly since the versions don't seem to match.

**Comment by danielatik** [comment]
yes thanks to all, I'm checking out the right version because I cannot update to php5.5
Thanks for all!! ; )

**Comment by Cydrobolt** [comment]
@danielatik keep us updated!

**Comment by danielatik** [comment]
I could not install yesterday. I'll check this out tomorrow. I'll keep you informed. Thanks to all crew.

**Comment by danielatik** [comment]
Hello all!

Finally I can install the mysqlnd removing the line exclude

**Comment by Cydrobolt** [comment]
Sweet!
