### ISSUE TITLE
Set-Up doesn't create User

### ISSUE THREAD

**Issue by mihawk90** [Cydrobolt/polr#95]
Hello,

I found this project just recently (through ShareX), and I'm having an issue setting it up. I downloaded the latest release 1.4.1 and went through the set up. After multiple failed attempts to login I found that there was no user created in the the MySQL. In fact, none of the tables had any content, though I assumed this to be normal due to no data being available yet.

`$debug` was enabled by default for me right after the download, but there were no MySQL errors. The tables are created just fine, just no content there.

I am using MariaDB 10.0.12, nginx 1.9.4, php 5.6.12.
I also tried with Apache (don't know which version, it's an old install), with the same result.

I dug around a little and let the script `die()` just before the insert, giving me the strings being inserted into the database. I tried executing the Query in HeidiSQL, and got this message:

> /* SQL Error (1364): Field 'theme' doesn't have a default value */

The table is created with theme NOT NULL, the same with IP, so this obviously wont work (except when I'm missing some magic :D). The Setup just assumes that the query runs fine, but it's not.

Pasting the `$_POST['t']` into the theme field and a random ip into the ip field made it so I could login, seems it's starting sessions twice but that's another issue obv. :)

**Comment by Cydrobolt** [comment]
That's really interesting! Thanks for pointing out the `$debug = 1`...turned it off by default. I recently set up an instance, and didn't have this issue. 

As per the theme, I think we should allow a blank string value (not sure if this is mapping to NULL in newer versions of MariaDB), which I'm unsure why it's not accepting the blank theme argument.

**Comment by Cydrobolt** [comment]
You can make a PR if you find something that works well in your environment. Otherwise, could you reproduce the error on https://c9.io and share the environment?

**Comment by mihawk90** [comment]
Hm well, as the [NULL Value](https://mariadb.com/kb/en/mariadb/null-values/) Documentation says:

> NULL represents an unknown value. It is not an empty string, or a zero value. These are all valid values, and are not NULLs.

I don't know for sure, but I think this was the case for MySQL for a long time as well, it might as well just be a configuration setting though.

Also what I didn't mention, I had to set the `varchar` of `theme` to 100 (or anything other), because the value in the option selector had 68 characters but the field is limited to 65 (depends on the theme of course, I used the Cloudy Night theme).

Getting the theme into the DB isn't really an issue, but I'm having difficulties getting the IP back. Since you are defining the variable to use in an input box I wanted to use PHPs variable Variables (awesomely creative name by the way), but that won't work with Superglobal Arrays, which $_POST happens to be one...

**Comment by Cydrobolt** [comment]
Yeah, you are right. Setup doesn't really take quite as many precautions. It's expected that an unauthorised user shouldn't be performing setup. However, that assumption could be wrong so we should escape the input there as well.

**Comment by Cydrobolt** [comment]
Also, the theme is actually stored in a config variable, so it's not affected by the limit

**Comment by mihawk90** [comment]
Hm ok, thought something like that. Then again on a multi-user setup each user could use their own theme, that's what I thought the Database field is for ;)

Either way MySQL would throw an error if the input string for a field is too long and wouldn't complete the query, doesn't hurt bringing up the limit a little :D 

---

Anyway, still thinking about how to get the IP, as you can see I just put a dummy IP in there for now (which should be fine for Setup), but I need to see how you did it on other occasions (since you also store IPs for created links there should be a way :D ).

**Comment by Cydrobolt** [comment]
@mihawk90 can you explain what you mean with "how to get the IP"? I'm assuming this has to do with `$_SERVER['REMOTE_ADDR']` not existing on nginx? I'm sure there's a different way it can be done.

**Comment by mihawk90** [comment]
nono $_SERVER variables are defined by php, not the webserver :D The difference is just that php runs as a separate process not as a module, but that doesn't play any role.

The thing is we let the user choose which variable to use for getting the IP, by default that is `$_SERVER['REMOTE_ADDR']`, it could be something different though for example if you use CloudFlare, you would use `$_SERVER['HTTP_CF_CONNECTING_IP']` for example.
The problem is I don't know (or am too stupid to see it right now) how to get the value out of the user defined variable. If it were always the same I would just be using $_SERVER['REMOTE_ADDR'] of course, but since it is user defined I need to get the variablename first and then the value out of that.

Usually one could do this with PHPs [variable Variables](http://php.net/manual/en/language.variables.variable.php) like `$$ip`, where `$ip` contains the variable name to use (`$_SERVER['REMOTE_ADDR']` in our case). The problem with that is that PHP won't allow using this with superglobal variables like $_SERVER, $_POST, $_GET etc.

So maybe I'm just overthinking things or just don't see it right now, but I don't know how to use the user-defined variable for that :D

**Comment by Cydrobolt** [comment]
Ah. You can simply reference `$ip` if `lib-core.php` is included. It injects the user's IP directly into each document in the form of `$ip` based on the user defined variable.

**Comment by mihawk90** [comment]
Ah well, thought something like this but didn't have the time to check it yet :)

I'll get a PR ready soon-ish that fixes this issue, I hope :)

**Comment by Cydrobolt** [comment]
:+1:
